### ISSUE TITLE
Old and new tool dilemma

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1180]
No issue. More a collection of thoughts and questions before i continue here.

A tool should just exist ONCE in the ui in best case. And it should just exist ONCE at all.

We have many double tools now with the new tool system. A prominent example is the select methods box, circle and lasso

Now the dilemma. Old Box select works different than the new box select. It activates once. And disappears after usage. This means that you can do some polygon modeling, press B for box select, select what you want to select, and continue directly with the tool that you had in use before the box select. Without any further action.

On the other hand, it's a double tool. We don't need two box select tools. One is enough. And the old hotkey isn't even longer visible in the UI, which would have been a reason to keep the entry for the old tool.

For me that's a 90 to 10 to remove the old select methods. But then we already run into the next dilemma. What to do with the old hotkeys? Remove them since the tool isn't in the UI anymore anyways? Or keeping them as secret hotkeys? Or shall we reassign the old hotkeys to the new tools? And also what to do with the editors where we don't have a tool shelf?

Needs a bit more thinking and a bit more experimenting.

![tooldilemma](https://user-images.githubusercontent.com/13919702/67364874-b860ba80-f570-11e9-8864-4a7be1048831.jpg)

**Comment by Draise14** [comment]
I personally, and have worked months, with a fusion of both tools to the same hotkey/workflow where I could. I have suggested this before, and will suggest again:

1. Move original operator to toolshelf under the right dropdown category
2. Rename original operator to "legacy"
3. If there is a hotkey on legacy, make the legacy operator activate on "click+drag", and normal press on the new operator. If the "click+drag" doesn't work, move hotkey to the new operator only. 
4. If an original operator gets removed by Blender, remove it. But we shouldn't. All API operators should be exposed, nothing hidden. This is the BFA way.  

**Example:**
W press: 
Transform widget mode
W + drag : 
Legacy mouse+key modal transform mode

I have made my personal bforartists map this way, and it works really well, especially when it comes to WER transforms. Any other way doesn't feel as good at all. Not the legacy WER system, nor the "autodesk" WER widget activation way.  

## Why?
- Because then each operator will now be, at least in name, unique. 
- All operators will then be in the same place in the UI, legacy with new. 
- All similar operators can be used in a similar way, putting key press and default toolshelf display as priority to the new operator; and keeping the legacy operator in the toolshelf sub menu + drag operation on keypress if there is a hotkey (so it's easier to phase them out when the phase out is official in the API). 

## Possible Issues:
- Edit mode>Legacy Loopcut activation doesn't work with drag (and the legacy loopcut is superior to the new Loop Cut as you can scroll to add more loops)
- Not all operators can go to the same hotkey with a drag press, but most can. 
 
# Counter against issues:
If click+drag doesn't work when there is a hotkey assigned to something legacy, then just move hotkey to the new operator, or remove hotkey. 
All operators (new and old) should be exposed in the tool shelf, even if double.
Let the removal of legacy operators should be up to the source code devs, not us. It would be too hard to track the unseen changes to API otherwise.

**Comment by ReinerBforartists** [comment]
Fair points all. That's what makes it so hard to come to a good conclusion here :)

**Comment by Draise14** [comment]
Oh, and for editors with no toolshelf, I'd make sure there is a menu that implies "tools" in the header, with exception to Outliner, as Rclick shows all. But I know the VSE will get a toolshelf in 2.82, the image editor has one, the 3D view, the node editor, the compositor editor. The animation editors don't have have a toolshelf - also the console, script, and others, but they are a different paradigm where principal actions are not tool orientated but action orientated. The outliner and properties editor neither, but that too is a different paradigm. 

Ultimately.. a toolshelf is to make actions accessible on mouseover, or to make secondary things easier to get to without needing to go into a header list and sub list to use it.

**Comment by Draise14** [comment]
And to add.. I would just.. keep the BFA 1 mentality! The toolshelf had all the tools. The headers had some tools that wouldn't go into the toolshelf, but it was consistent throughout the entire UI if that was the descision.

**Comment by ReinerBforartists** [comment]
The BFA 1 tool shelf is the long term goal. But we have a very long way to go. I am not even sure if we can manage to reintroduce tabs here. The new code is wicked. This fish may be too big for us. We will see.

> Let the removal of legacy operators should be up to the source code devs, not us. It would be too hard to track the unseen changes to API otherwise.

This has nothing to do with the API. The operators would still be there. they are required for the new tools anyways. We would just remove the menu entries and the hotkeys. 

But how much similar box select methods do you really need? This just complicates everything unnecessarily and pollutes the menus. And we cannot let the Bforartists development in the hands of the Blender developers ^^

**Comment by Draise14** [comment]
If the tool is the same operator you call in python, why are there two? 

I was referring to.. having the two operators still exposed till one disappears later in time, as it is in the roadmap of Blender. Just make it easier to access the default, till the python code disappears from the source and API documentation, which we don't edit. We "hide" the legacy operator inside the toolshelf submenu of the functional entry instead of completely removing it from the UI but yet still have it accessible in the console and API for no reason.  

**Eg.** 
- Transform W will have one entry in the toolshelf, and a submenu with the legacy modal transform. Both are useful, and making them work together is.. I can't go back to one or the other. 
- Box B select will be in the select entry with box select mode and legacy box select. One is a mode, the other is an instant. Which is more useful, not sure? I like just cliking and dragging with a hotkey (ctrl+drag) and it's custom and different, yet still great. 

I personally think each double entry should be an **individual task** in itself, with an evaluation of which would stay and how, as two operators in the same toolshelf area or as a fusion to one and remove/hide the less useful one. 

Once a single double entry passes it's feature request/evaluation task stage, then it becomes a task. One for that one single operator. It's too big a debate to blanket solution every single double operator with one plan of action that will cause issues to funcionality (as not all new operators are better). 

I do like minimization, but not at the cost of missing functionality. 

Though yes, tabs and panels would make this work easier.....

**Comment by ReinerBforartists** [comment]
>If the tool is the same operator you call in python, why are there two?

The items in the text menus uses a direct access to the operators. The items in the tool shelf calls this very same old operators with a wrapper class. You can see this in the keymap.

Here the box select from the select menu.

![oldentry](https://user-images.githubusercontent.com/13919702/67425622-a6b2fd80-f5d8-11e9-999b-4f4f368eefd9.jpg)

And here the hotkey from the tool shelf: 

![toolshelfentry](https://user-images.githubusercontent.com/13919702/67425640-afa3cf00-f5d8-11e9-8a81-b0a03ec3c37f.jpg)

**Comment by ReinerBforartists** [comment]
> I personally think each double entry should be an individual task in itself, with an evaluation of which would stay and how, as two operators in the same toolshelf area or as a fusion to one and remove/hide the less useful one.
> 
> Once a single double entry passes it's feature request/evaluation task stage, then it becomes a task. One for that one single operator. It's too big a debate to blanket solution every single double operator with one plan of action that will cause issues to funcionality (as not all new operators are better).
> 
> I do like minimization, but not at the cost of missing functionality.

Yeah, we need to check it at a case by case base. In case of box select we would miss the ability to call the tool while another tool is active. The question is if this is any gain to the workflow. You box select anyways.

**Comment by ReinerBforartists** [comment]
Thanks for your thoughts and ideas Draise. I will keep them in mind when starting the tool shelf branch :)

Let's postpone this one for now to get it out of the way.

**Comment by ReinerBforartists** [comment]
This one has fulfilled its purpose. I will try to take care about the mentioned points

Closing. But not forgotten!
