### ISSUE TITLE
Outliner - Box select versus Drag n Drop

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1221]
The box select obsession of the Blender devs is plain crazy. In the outliner i always box select with left mouse. But for drag n drop, which is in the outliner as important as selection, i need to hold down Shift. Which is in the rest of the UI duplicate.

I would say we need it the other way around. Make box select with an action key like shift or control, and drag n drop the natural behaviour. This needs further thinking though. We need to stay consistent with the rest of the UI.

So postponing for now. Revisiting this at a later point.

**Comment by Draise14** [comment]
This is not valid. With Tweak on box select, you can click and drag on items without a modal, and the box select only works on empty space.

**Comment by ReinerBforartists** [comment]
We will see :)

At the moment i am at the toolshelf.

**Comment by Draise14** [comment]
Righteo. 

Just some more thought... keeping it consistent with the rest will... 
1. be impossible to make consistent without a modal since Box select is now a tool mode elsewhere. 
2. changing it to a modal will make usability more keyboard focused, as the outliner actually is now consistent with most software: where you click off something and drag and you can box select.. like you should... Some other areas of the UI are like this also (eg. File Browser) which also make it inconsistent ultimately. 

So.. here is the example tweak fix with Lclick working on both. 
![L click interactions](https://i.imgur.com/0M2pLSh.gif)

**Comment by ReinerBforartists** [comment]
Thanks Draise. Your idea is not forgotten ;)

We currently do it the Blender way. And that's holding shift to drag. 

As told, i am at the toolshelf now. And this means a ton of changes in the keymap. We would run into merge conflicts when we tackle this issue now. So i have postponed this issue.

**Comment by ReinerBforartists** [comment]
We have just fixed a box selection issue in the outliner here: https://github.com/Bforartists/Bforartists/issues/1306

I would say this makes this taks here obsolete. Closing, won't touch it twice.
