### ISSUE TITLE
Wireframe Colors in display or in shading tab?

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#123]
We have the wireframe colors by default in the display tab in the objects tab in Properties editor. In the sidebar we have it in the Shading tab though. That's inconsistent.

This one needs further thinking. Options we have:

Put wireframe colors into own panel in both, sidebar and properties editor. But what's with the wiretools then?
Put wireframe colors into the Display panel in sidebar. Then we would need to put the Wiretools also there.
Leave it as it is, and live with the inconsistency.
*Insert Idea here*

![displayvsshading](https://user-images.githubusercontent.com/13919702/38185120-e42ae332-364c-11e8-8828-b83c362584b8.jpg)

**Comment by Draise14** [comment]
Ehm.. like the Armature display options.. I would love to have all display options in the Properties sidebar, where they are easy to access without annoying tab switching and categorize neatly into the viewport display - because.. they are all viewport option toggles for objects/items.

**Comment by ReinerBforartists** [comment]
As told before, this is impossible. Object related settings needs to be in the Properties editor. 

That we have the wireframe colors in the sidebar is already a inconsistency that i would have loved to avoid.

**Comment by Draise14** [comment]
Ah. Not technically possible? But it can be removed from the side bar? I guess there is the answer. 

Move all wireframe and object based visibility to the object properties tab and only have common object visibility toggles in the sidebar.

And Yes. .. I would,  like the object name and transform panel in the sidebar, to have those object display options in the side panel because you know those only work on active and you don't hardly use these option's from a properties view tab. Specially in animation and rigging.

**Comment by Draise14** [comment]
This may require rethinking the Wiretools... which has proven super useful and a featire point of BFA. Maybe because with the side panel is naturally attributed to viewport control and object control from that sidebar and then go to the properties object tab exclusively for delta and other advanced object toggles.

**Comment by ReinerBforartists** [comment]
Everything is technically possible. The big Mess that the Blender devs call a UI is technically possible. What is not possible is to convince me to make the mess even bigger ;)

The wireframe colors is a border case. It is both, a view setting and a object setting. So the only thing that i could do here is to remove it from the sidebar to have it consistent again. Which i don't want. The task here is to make the location in both places consistent.

**Comment by Draise14** [comment]
I agree there. ...  

A new Object Display tab in sidebar for everything object display related could work no? Move Wire tools/wireframe to that area also and keep Display panel alone?  

Then rename object properties tab area to "Object Display" to not confuse with viewport "Display"? 

I think maybe it's just not clear what "display" is for because it's everywhere with so many different contexts.

**Comment by ReinerBforartists** [comment]
Yeah, that could be a possible solution. But introduces yet another panel. Ah, it remains complicated. I will think about this for a few more days i guess ^^

**Comment by ReinerBforartists** [comment]
I will leave it as it is.
Closing.
