### ISSUE TITLE
The tooltips on tabs show two lines instead of one line. 

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#1293]
Reporting for Bforartists 2 alpha 080, running on Windows 10 64 bit Version 10.0.18362 Build 18362.

Hover the mouse on any one of these tabs:
![image](https://user-images.githubusercontent.com/9047168/70169859-a6d30c80-16f1-11ea-996f-96ebc1cf3a3d.png)

A tooltip will appear. It shows two lines. [BUG]
The top line is blank, except only one period.
![image](https://user-images.githubusercontent.com/9047168/70169790-82773000-16f1-11ea-875b-ac74b9d12baf.png)

**Desired:** It should show only one tooltip line.

**Comment by ReinerBforartists** [comment]
Thanks for the report. Let's have a look what we can do here :)

**Comment by ReinerBforartists** [comment]
Related: Rework Tooltips #1031

**Comment by ReinerBforartists** [comment]
Hm, not this easy. Now i know why i have left the dots alone. We either display the tooltips with their headers everywere. And this shows some hiccups like here. Or we do it the Blender way. Then i have to readd the tool name to a few thousand tooltips by hand again. Hm hm hm.

**Comment by ReinerBforartists** [comment]
This problem is in more than one place.

![lightprefs](https://user-images.githubusercontent.com/13919702/70306757-f99ee800-1807-11ea-9023-adca9c3f77ea.png)

**Comment by ReinerBforartists** [comment]
Fixed in master

I would have loved to add a description to those buttons too. But the current Blender code design does not allow this. I was able to keep our tooltips with the tool names intact, and remove the empty string with the dot at the end in the Properties tab buttons. 

Blender does not show the "Plane" Label at the button yet, and at many other buttons. There you have to guess the tool name from the button name. But we have them as icon buttons too. As told, it would have been several thousand tooltips again without a tool name in the tooltip.

![fixed](https://user-images.githubusercontent.com/13919702/70312697-73d56980-1814-11ea-911b-ad2fdedb9b6f.jpg)
