### ISSUE TITLE
[Freature Request] Persistent/sticky Menu Option

### ISSUE THREAD

**Issue by stickynoteme** [Bforartists/Bforartists#1307]
Hi, as a visually impaired user who uses windows magnifier at 150% with a limited field of vision [40% of the working screen.] to work on the computer it is incredibly frustrating that menus dismiss themselves when the mouse is no longer over them as the mouse is used to scroll objects into the visual field of the viewer.

It would be nice if there was an option to make all menus sticky so that way they would be persistent until a mouse click is made somewhere on screen

**Comment by ReinerBforartists** [comment]
Hi stickynoteme,

The idea is nice. But such a feature is most probably behind the scope of what we at Bforartists are able to do. Best is to ask this the Blender developers.

Kind regards
Reiner

**Comment by ReinerBforartists** [comment]
Ah, forgot to say, you can create hotkeys for complete menus. That way you can call them under the mouse. And they will stay open until you move the mouse. All you need is wm.call_menu plust the python name of the menu. Have a look in the keymap manager.

You could also have a look at the pie menus. But i haven't investigated into that chapter yet.

**Comment by Draise14** [comment]
Another workaround, I know it's not great, is by making your own quick favorites menu list, then using the hotkey to pull that list up. Since it's floating, you can stick to it. You loose icons here though. The other, as mentioned, is building your own pie menus. They can be triggered and held open. [There is a paid pie menu editor addon from here](https://blenderartists.org/t/pie-menu-editor-1-16-4/662456)

Tearable menus and pinnable menus has been a feature I've wanted for a while now, but it's not tehcnically possible yet. in [Rclickselect](https://blender.community/c/rightclickselect/Dkdbbc/) it has been requested often and should be voted.

**Comment by ReinerBforartists** [comment]
Closing this issue since there is nothing that we can do here.
