### ISSUE TITLE
Outliner - Missing Collection Visibility toggle in Scene View

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1364]
# Issue
![bforartists_2020-02-12_09-55-25](https://user-images.githubusercontent.com/35357409/74346648-e0716500-4d7d-11ea-9b39-f17901b5750d.png)

This may be a regression, but the visibility toggles are not showing up nor toggling in the scene view of the outliner, again. 

# Solution
Make sure the visibility toggles in scene view of the outliner is working. 

## Details
Build from master Bforartsits 2 - date 10.2.20

**Comment by ReinerBforartists** [comment]
Thanks for the report. But this seems to be no bug. Blender behaves the same since version 2.80. 

You could report it as a bug to Blender. And then let's see what they think. But here is nothing to fix for me.

![samebehaviour](https://user-images.githubusercontent.com/13919702/74356998-85f8f880-4dbf-11ea-8a6a-17e438a0fd51.jpg)

**Comment by Draise14** [comment]
Ah, I was downloading 2.83 dev build to just test it. You beat me to it. I might have to change me defaults on visibility toggles then.... I also just realized you can't keyframe the eyeball, only the screen visibility, more defaults changing. I'll make a new task.
