### ISSUE TITLE
Shader editor, remove default box select.

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1385]
The active tool and the default here is tweak, but lmb simply box selects. This is unwanted behaviour.

![shadereditorboxselect](https://user-images.githubusercontent.com/13919702/75111580-df70eb00-563b-11ea-935b-3f1c2546715f.jpg)

**Comment by ReinerBforartists** [comment]
Hm, can of worms. This is more complicated than thought. The select methods already includes tweak. Which would make the tweak tool obsolete.

When we remove the box select, and keep the tweak as the default, then we need to press B to box select all the time. This would be consistent with the rest of the UI, but slowest.

When we remove the box select, and set box select as the default, then tweak is simply obsolete. You can tweak with box select. And also the tweak left any box select method is obsolete then. 

@Draise, i would love to hear your opinion at this one here too.

**Comment by Draise14** [comment]
Ah! Thanks for asking me these things! 

Methods: 
1. B to Box select (permanantely activate the box select tool till you toggle back): 3D View, Animation Editors, Texture/UV editors
2. Lclick + Drag on empty space to Box Select: Node Editor, Outliner, Text Editor (highlight text)

I'd prefer the second option globally. But I still haven't gotten it to work in the Animation Editors and 3D View without a modal hotkey held down.. like the Lasso Select. 

I think the outliner and node editor having the box select on Lclick should be the standard, as it's more consistent with every single other OS and software out there. I'm more frustrated in dragging something off screen when I have it selected when all I wanted was to select a group of something with box select out of instinct. The only issue is that in 3D view, transformation is more the desired expectation when clicking and dragging. So having a modal for box select would make sense, like the Lasso Select. 

Since both areas are 2 paradigms: one is 2D manipulation, the other 3D manipulation - having the box select activate not on B, but like the Lasso Select would make sense to me for 3D (update the 3D view hotkey to momentarily box select with a modal press+drag then toggle back to tweak on release). Having every other 2D editor work default to like the outliner and node editor (press and drag in an empty space to box select) would also make sense (so update the Animation Editors to work this way.)

**Comment by ReinerBforartists** [comment]
Okay, that's already how it works at the moment when i understand you right. But what's with the tweak tool then? Isn't that obsolete in this case?

**Comment by Draise14** [comment]
Yeah. I think so.. I don't see much of a use in the node editor when the box select is also the tweak tool.

**Comment by ReinerBforartists** [comment]
So the better solution is to remove the tweak tool then :)

Lemme sleep a few nights over this if i don't find a pitfall here ...

**Comment by ReinerBforartists** [comment]
Leaving things as they are at the moment. The tweak tool is obsolete, but does not disturb really. I cannot say what changes we will have at the tool shelf in the future here. And tweak and its hotkey D is currently the default to escape the other tools. D for Default ...
