### ISSUE TITLE
Crashbug with console window open and closing Bforartists.

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1441]
Windows only. From time to time Bforartists crashes when the console window is open and you try to call the properties or to quit the software. This is completely random. And not to reproduce so far, which makes it really hard to catch. It happens once, then for several tries and quite a while not.

Normal users will most probably never run into this. Needs nevertheless a task now.

**Comment by ReinerBforartists** [comment]
Pic or it didn't happen ...

![crash](https://user-images.githubusercontent.com/13919702/78470508-70061500-772a-11ea-8b9e-9d919de3c9a1.jpg)

**Comment by Draise14** [comment]
What are the possible steps?

Could this be because it paused the console in mid execution? The white thick cursor looks like it is placed. When it is placed it sometimes pauses the console process. This makes BFA not responsive. I do this to pause batch renders. To un pause you press Enter. The header of the console may say "select Bforartists". 

Thought it was normal behaviour?

**Comment by ReinerBforartists** [comment]
Ah cool, you found the way to reproduce it. And even cooler, this crashes in Blender too \o/

Thanks buddie. Will make a bug report to Blender tomorrow :)

**Comment by Draise14** [comment]
Not sure if I should celebrate or cringe.

**Comment by ReinerBforartists** [comment]
Y not both :D

Reported :)

https://developer.blender.org/T75431

**Comment by ReinerBforartists** [comment]
Ah, closed as invalid. Expected behaviour ...

So let's close this one too. It remains nasty,  but at least i know now what to avoid.
