### ISSUE TITLE
Video Sequencer - Proxy tab checkboxes need to be L aligned. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1466]
# Issue
![bforartists_2020-04-20_13-02-21](https://user-images.githubusercontent.com/35357409/79950986-85bf4e00-843d-11ea-8753-33e42f9ced88.png)

Another few rascals.. These are right aligned (terrible) and should be left aligned. This could be a regression. 

# Task
Move them left.

**Comment by ReinerBforartists** [comment]
Ah these funny merges ^^

**Comment by ReinerBforartists** [comment]
Draise, are you using the official version here, or the devbuild? I have this picture here. Still some work to do, we have a merge regession here i guess, but left aligned:

![proxy](https://user-images.githubusercontent.com/13919702/79952079-1fa4ec00-847a-11ea-8ec5-48620d10c783.jpg)

**Comment by ReinerBforartists** [comment]
Ah yes, that's from the official release version. There we have it wrong aligned.
![release](https://user-images.githubusercontent.com/13919702/79952391-a659c900-847a-11ea-9ed9-2972ded73f58.jpg)

**Comment by ReinerBforartists** [comment]
This problem is much more general. They have changed the code again. Now the props with decorator are as a whole right aligned again, with the checkbox at the left of it.

Unfunny. This is at the one side a step into the right direction. Since now the checkboxes are at the left side again even in Blender. But we battle once more against the Blender solution with its right alignment in general.

Either way, the original task here is invalid. The checkboxes are left aligned in the latest devbuild. I will make a new task for the split issue now.

![splitproblem](https://user-images.githubusercontent.com/13919702/79954643-e53d4e00-847d-11ea-80c6-490b926dde52.jpg)
