### ISSUE TITLE
3D View - Sculpt Mode - Piew Menu and Transform hotkey conflict

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1485]
# Issue
The hotkey W is for transform, but in Sculpt mode, it's also for the Sculpt Pie menu when activated via the offical addon. This may need to be resolved for user choice compatibility. 

![bforartists_2020-04-25_21-11-57](https://user-images.githubusercontent.com/35357409/80295575-7429bf00-8739-11ea-9c46-2e77e86a09c4.png)
![bforartists_2020-04-25_21-00-25](https://user-images.githubusercontent.com/35357409/80295577-75f38280-8739-11ea-8162-5db2cf34ead3.png)
![bforartists_2020-04-25_21-14-26](https://user-images.githubusercontent.com/35357409/80295649-28c3e080-873a-11ea-89e0-bed3ced7eec9.png)

# Task
Evaluate if viewport pie menus should be activated by default, and map BFA and the pie menu's accordingly, putting priority to transform. 

With that said, an alternative with the Pie menu entry is map it do D like the tweak (but in sculpt mode only, actually free) and have the addon turned on by default. 

The other is.. modifying the addon to give it options to the user like some other addons (Machine Tools is one example). 

The other is double W for the pie menu or transform... not ideal. 

The other is.. double Rclick will bring up a combo of the context menu + pie menu? Sounds too ambitious...

**Comment by ReinerBforartists** [comment]
Ah, hotkey conflicts with Blender defaults. How i hate them ...

**Comment by ReinerBforartists** [comment]
Hm, we would need to rewrite the addon here. Not happy about this.

**Comment by ReinerBforartists** [comment]
Thought about this intensively again. 

The dilemma is, we can not change our main navigation to fit the needs of a Blender addon. And i am not really willing to start maintaining more and more addons that does not work with Bforartists. This would add a ton of workload and responsibility to us. We do this already with a handful of the official addons, and even with this few we loose our changes from time to time with the merges. At one point it starts to slip through.

You can turn off the W key in the addon. So that it does not conflict anymore. You loose of course the pie menu for the brushes then. But they reside already at the left of the workspace. So you loose a working workflow that you might be more comfortable with, but not the tools.

Alternatively you could switch to the Industry Compatible keymap. But i think they also use the WER keys.

Bforartists is in general made that you use as few hotkeys as possible. And that's the whole story with the pie menus. It adds a ton of new hotkeys. When our few hotkeys still conflicts with a Blender addon, then this is of course unfortunate. But we cannot solve this at our end. The addon developer is responsible here. 

As sorry as i am, closing.
