### ISSUE TITLE
Remove the orthographic views buttons (duplicate function!)

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#1487]
The orthographic views buttons are redundant, because the same function is already provided by the widget. 

The widget provides X,Y, and Z and their opposite views (represented by fainter circles). Clicking on the circles is equivalent to clicking on the buttons.

In fact, the widget also allows us to change the angle, which the buttons cannot do.

Also, the widget is right next to the orthographic views buttons. Thus there is no benefit of having these buttons at all.

Removing the buttons will reduce the clutter.

**Comment by ReinerBforartists** [comment]
It's an addon. You can turn it off :)

I had more than one user request for this buttons. The widget is a pain to use. Even i forget sometimes what hotkey shows what orthoview. And digging in the sub menus is no go. So i have readded the addon from Bforartists 1 since i personally missed it in my workflow too much.

I agree that it adds a bit of noise. But as told, you can turn the addon off if you want. It is called align view buttons. I may have a look in the future though if we can make this functionality to toggle from the settings panel. But for now we have a thousand other things to do first, unfortunately.

![alignview](https://user-images.githubusercontent.com/13919702/80303768-93186780-87b2-11ea-8447-81b527363603.jpg)

**Comment by raindropsfromsky** [comment]
Actually there are three major problems in this addon as well:
1. The views are not so different (not recognizable instantly as left/right/top/bottom etc)
2. The selected button is not highlighted at all.
3. When we select a view from the widget, it is not reflected in the toolbar!

**Comment by ReinerBforartists** [comment]
Yes, i know. It has its flaws and needs improvements. But the one click solution is unbeatable :)
