### ISSUE TITLE
The widget does not distinguish between the +ve and -ve direction of all three axes

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#1488]
Try this:

**Step-1:** Turn the widget so that we can see all six circles.
![image](https://user-images.githubusercontent.com/9047168/80304049-6a539a80-87d1-11ea-9fcf-160c8beb5208.png)

**Step-2:** Click on the dark red circle. (+ve x-axis)

**Step-3:** Repeat Step-1

**Step-4:** Click on the light red circle (-ve x-axis)

The widget looks practically similar in steps 2 and 4. There is a very small difference in the diameter of the circles, but this is not easily discernible.

If we repeat the experiment with the other axes, the same problem can be observed.

**Desirable:** Make the difference easily discernible.
For example, let the negative axes have hexagones or squares instead of circles.
Or let them have a white line border.
![image](https://user-images.githubusercontent.com/9047168/80304446-7b9da680-87d3-11ea-87f9-c2dbf2e12eba.png)

**Comment by ReinerBforartists** [comment]
Thanks for the suggestion. This is better reported to the Blender devs though. It's their widget. When it's about me then i would remove this buttons all together ...

**Comment by raindropsfromsky** [comment]
Done! (added to the Maniphest)

**Comment by ReinerBforartists** [comment]
^^

**Comment by Draise14** [comment]
I like this widget, use it all the time. If it was the signature house in BFA, it would be really fun, with some extra arrows to jump to the other sides and also some rotate view clockwise and anticlockwise would be handy, but yeah. I wouldn't know where to start to know how to edit these things. 

Autodesk has perfected this widget, so it's easy to click on a particular alignment in one click from the widget, instead of two clicks to flip to the other side like this Blender one. Hopefully Blender updates this.

**Comment by ReinerBforartists** [comment]
Okay, let's close this issue now that it's reported to Blender.
Thanks for the idea anyways.
