### ISSUE TITLE
Header menu - top or bottom? Request for default theme consistency in all layouts. 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#149]
I noticed in Blender and BFA, the header menus are alternating between top and bottom per view per layout. There are so many alternating header menus that muscle memory is per view per layout based and not overall software based in one consisten way - tiring the mouse memory to multiple areas for the same consistency in use - and what's more, new windows or duplicate windows are also inconsistent per layout. 

I was wondering if it were possible to create a default theme that had all Header menus in the top or bottom, even on new windows - which will require a new user settings default and testing. 

**Task:** 
Create default user settings with all header bars to the top or to the bottom

**Comment by Draise14** [comment]
3D View and Image Viewer have them to the bottom and most others are to the top, just to name a few inconsistencies. 

General concept is that the header is to the top, being a "head"er.

**Comment by ReinerBforartists** [comment]
As told, everything at the top would be one big spot of noise. That's why i have placed the headers for the 3D view and the animation editors at the bottom. The rest is at the top.

The riddle with the default is also solved. There is none. When you drag open a new editor from an editor that has the header at the bottom, then the new editor type will also have the editor at the bottom. And vice versa.

Nothing to fix here. Closing.
