### ISSUE TITLE
The alignment of labels is faulty: The parameters and its attributes are mixed up in one column

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#1491]
The alignment of labels is faulty: The parameters and its attributes are mixed up in one column
In this respect, the alignment of labels is superior in Blender 2.90, as compared in the screenshot below:

![image](https://user-images.githubusercontent.com/9047168/80309489-0510a100-87f3-11ea-9e3e-48ab1c21b6de.png)

In the first example, Blender clearly shows three attributes (x, y, %) for a parameter: Resolution.
The alignment makes this clear. 

Similarly, at the bottom, it has three attributes for Frames: Start, end and step.
Again, this is clear from the alignment.

But the alignment of B4a is not clear at all. Because of left-aligned labels, the resolution and aspect entries get mixed up.

**Desired:**  Re-align the labels as Blender 2.90 does

**Comment by ReinerBforartists** [comment]
We don't do it the Blender way. We align left. This is intended ^^

**Comment by Draise14** [comment]
They have introduced a new layout system this week to label and sublabel parameters. 

like it could be

1. group label (resolution; row)
2. sub label + properties (x, y ,percent; columns)

It does feel off because of the label mixed with X "resolution X" which makes it dis-aligned.

**Comment by ReinerBforartists** [comment]
But i find my solution still better readable. Left aligned.

**Comment by ReinerBforartists** [comment]
Let's reopen it. It seems that there is still the need to discuss it.

**Comment by raindropsfromsky** [comment]
> They have introduced a new layout system this week to label and sublabel parameters.

That is what I mean by "parameter" (=which takes a label) and "attributes" (which take the sub-labels).

If you see carefully, Blender layout has three columns.
1. The left-most column has the label.
2. The middle column has the sub-labels. These are right-aligned.
3. The right column has the value field.

IMHO the right-alignment of the middle column makes it look good.

**Comment by ReinerBforartists** [comment]
In this case it might even an improvement, yes. But i can unfortunately not cherry pick that way.

I have meanwhile had a look at the code again. And i cannot right align this props without to realign the rest at the right too. Like in Blender. So it's either our solution with left aligned text in general. Which in my opinion is in general better readable, even with such oddities here. Or we trash our solution and use the right aligned text like in Blender. And for me the culprit is that all the checkboxes are then aligned in the middle instead of the left side.

As an example:

![left](https://user-images.githubusercontent.com/13919702/80337499-4d16de80-885a-11ea-955e-25f1646c9a69.jpg)

**Comment by ReinerBforartists** [comment]
Haven't found a solution to this dilemma here. Our text is left aligned. And this case here is not to solve. Sorry.

Closing.
