### ISSUE TITLE
Animation Editors - Snap dropdown needs a button and icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1541]
# Issue
![image](https://user-images.githubusercontent.com/35357409/81755845-87e65c80-947f-11ea-8864-590f9d969dea.png)

Right now the frame snapping in the animation editors (NLA, Drivers, Fcurves, and Dopesheet) all have a dropdown list with no icons. The header of the 3D view has a little magnet button to turn on the snap on and off. 

Version:` devbuild-03-05-2020`

# Solution
A quick toggle for on/of and/or icons in this list might be nice. 

### Notes
This might be a regression?

**Comment by ReinerBforartists** [comment]
Don't see a regression here. Blender has it this way too. This tool is not the snap tool, it is settings to adjust autosnap. So i do question if it makes sense to change it at all.

**Comment by ReinerBforartists** [comment]
Fixed in master

Added some icons. We reuse two icons here at the moment. Wasn't in the mood to shape two new ones for this. But it should not be a problem. Usually you don't change this menu too often. And there is the text too.

![icons](https://user-images.githubusercontent.com/13919702/81917170-220be900-95d5-11ea-9a34-8c19ff85a055.jpg)

**Comment by Draise14** [comment]
Thanks for this. When I see things without icons, I go.. ah damn, I have to read now. You've spoiled me. ;)

**Comment by ReinerBforartists** [comment]
Yeah, once you've seen it you can't make it unseen ^^
