### ISSUE TITLE
Move Lock camera to view out of the subtab

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#160]
You might to zoom out the passepartout to reach areas out of the camera view. Weight painting your grass for example. So it was no good idea to hide it in the lock subtab. 

Move it out of the subtab.
![lockcameratoview](https://user-images.githubusercontent.com/13919702/38690939-a9a08dda-3e7f-11e8-89e8-ed4e53857f4e.jpg)

**Comment by Draise14** [comment]
YES YES YES. I was too afraid to suggest this one, but that is a huge toggle I use all the time every day all day. Glad you felt the same.. Having it expanded with all of that panel options all the time was making it slow to get to.

**Comment by ReinerBforartists** [comment]
You are always welcome to report roadblockers :)
I thought of removing the subtabs completely here. But then it looks crowded again :/

**Comment by Draise14** [comment]
Maybe instead of "Lock" sub panel, go with "Advanced" and do some organization. 

Frist three in the Lock section with Focal length could be the top level, and the advanced level could be the rest. Once you set the view depth, you don't change it that often if ever at all (unless with ridiculously heavy scenes).

**Comment by ReinerBforartists** [comment]
Yeah, but the subtab doesn't make much sense with just two items then ...

**Comment by Draise14** [comment]
They both would be dropped to two halves potentially.

Top level:

- Local Camera (2 rows)
- Lens (1 row)
- Lock Camera to view toggle  (this could be a double row icon with Lock Camera Layers instead of tickbox)
- Lock Camera and Layers (2 rows with previous, or 1 row is double column icon - total 4-5 rows)


Advanced Subtab would have: 

- Clip sliders (two rows)
- Camera Object Lock (two rows)
- (optional) Render border? (5 row s total)

**Comment by ReinerBforartists** [comment]
We can't move Clip into a subtab. Users regularly run into import problems where the mesh is factor 100 too big ...

**Comment by Draise14** [comment]
Ah, in that case yeah, a sub tab with only 3 lines doesn't make sense when all else is at 7 or more lines. No subtab would be needed... 

How about hiding lines when things are not active and make some toggles double column? Like what you've been doing elsewhere? Why show greyed out options when it's evident that it's not toggled elsewhere? 

Just thoughts.. even just moving that lock up and out would be nice.

**Comment by ReinerBforartists** [comment]
Yep, good hint. So we will most probably remove the subtab here, and try to hide the not active props.

**Comment by ReinerBforartists** [comment]
Fixed in workflow branch
https://github.com/Bforartists/Bforartists/commit/30d667e134c06163031c58fe78f0b1c5155ea2c0

![lock](https://user-images.githubusercontent.com/13919702/38916512-f22b893a-42e7-11e8-9ea7-2cee1805d65d.jpg)
