### ISSUE TITLE
Global - Add buttons-links to relevant documentation in UI

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1600]
# Feature Request
![bforartists_r44kFB37dH](https://user-images.githubusercontent.com/35357409/84161243-ae72c580-aa34-11ea-9ef0-e59335323798.png)

I've had a quick look at textools addon and one thing that came up immediately (and helped me learn the addon faster) was it's button in the panel headers to the relevant documentation, a help button. 

This is genius. 

I know the documentation is very dense and comprehensive for BFA right now - a strong selling point, it is very useful, just hard to access/use in the age of interactivity. I wonder if we could atleast add a button-link in the editors+panels to their relevant documentation and chapters

## Reasons
- Documentation is interactively linked to the UI and easily discoverable
- Documentation is easier to access relative information directly without needing to dig through multiple PDF or search engines or indices manually.
- We hit the target that the software is artist friendly, as it can be easy to learn without tutorials or forums or trial and error, but just clicking through the UI and loading the relevant documentation. 

# Task
- Plan where to add help links as a consistent UX design filosophy
- Create a preference toggle somewhere to show or hide these quick links (optional) with a conditional, so you have a learning mode, and a using mode. 
- Add them to the UI where relevant.

This could be a big task, but a super user friendly task.

**Comment by ReinerBforartists** [comment]
Wellll ... Blender had this idea before us. And we would quickly end in the situation that Blender currently is. Their links leads to 90% to nirvana :)

We had to fix already one deadlink to the old Blender 1 manual ...

**Comment by Draise14** [comment]
Can these link opening things work with local files stores in the LOCAL or USER folder? In that case, they wouldn't break. 

I guess you'd maybe need a quick online wiki with a single address, so the link updates to anchored sections of the same page, then it would be easy to update.

**Comment by ReinerBforartists** [comment]
Sure. But who maintains such a local manual divided into single operators then? Because that's what you need. Every operator with its own chapter and a corresponding link. Two years and we are still not finished with at least the online version. And you still haven't finished the Sphinx version. Not even the promised chapter for the Video editor. 

Everything is possible. But we have to take the manpower into account too. And this task would be a killertask that eats manyears like nothing. Because it is not done with writing it once. It needs updates and maintenance. Blender has this man power. They have a similar system. And it fails.

**Comment by Draise14** [comment]
Good point. It's a practical and nice idea, but a feat.

**Comment by ReinerBforartists** [comment]
Yes. This job is simply too big and not manageable. So let's close this issue :)
