### ISSUE TITLE
mirror editing problem

### ISSUE THREAD

**Issue by mahmoud-alfall** [Bforartists/Bforartists#1671]
why the mirror editing in the header doesn't work with extrude or loop cut, etc. it just works with move , scale and rotate. is there's a way to solve this without using mirror modifier?

**Comment by Draise14** [comment]
This is... an issue in the Blender architecture right now, the closest thing to fix this is using the Auto Mirror addon included with BFA. With this, you can slice and mirror objects with a single click instead of using the modifier with multiple clicks and booleans or geometry cuts. You can do it either with a live system that you can apply later, or do it with freeze to keep on modeling assymetrically. 

![image](https://user-images.githubusercontent.com/35357409/87679608-02fb1600-c742-11ea-97f5-76f02e950fae.png)

**Comment by ReinerBforartists** [comment]
That's indeed a Blender feature. And there is little that we can do here. We just try to improve the UI. Features is a completely different field.

You could make a suggestion at Right Click select. And hope that a Blender developer picks up the ideas.

Closing.

**Comment by mahmoud-alfall** [comment]
Thanks a lot

في الخميس، ١٦ يوليو، ٢٠٢٠ ٦:١٤ م ReinerBforartists <notifications@github.com>
كتب:
