### ISSUE TITLE
Apply scale warning

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1696]
Just had the idea to implement a warning when you do an operation that requires a scale of 1 and you haven't applied scale yet. UV editing for example. 

This is just a rough first idea. Maybe it leads to nowhere. Maybe we can get away with placing the existing apply buttons at a more prominent place. Maybe an addon will do the trick. That way you could turn on or off popup warnings.

**Comment by ReinerBforartists** [comment]
Or maybe we can implement an auto apply every time the scale is different than 1. Or a switch to set the scale to 1 after scaling the dimensions in object space.

**Comment by Draise14** [comment]
That toggle to automatically apply it after the operation would be swell.

**Comment by ReinerBforartists** [comment]
Here's the link to the script directly: https://blender.community/api/storage/file/59/59ee2b501de2fb001513f45c/b6/b66fee6f10544b84b2089c4732f482a5.py

**Comment by Draise14** [comment]
I have been trying this addon out a few months now. Right now you can't apply scale to a linked mesh data, like multiple instances, and it will throw an error if on. But in general, it is useful - but also it is important to turn off when animating, rigging, and doing other work like layout.

**Comment by ReinerBforartists** [comment]
I don't really want to integrate the addon. In case we integrate it then we need to maintain it. And i hold it like Blender here.

What it is useful for is to provide example code for our planned warning. When somebody wants the functionality of the addon, then he should imho use the addon.

**Comment by ReinerBforartists** [comment]
Thanks for your experience here Draise. This makes me wonder though if we even should do this task. You name already a few cases where it is not recommended to apply scale at all. And when we throw a warning, then the user might ruin his work by following the advice.

Hmmhmmhmm.

**Comment by ReinerBforartists** [comment]
We could also ask if we are allowed to include the addon. So that power users can activate it if needed. It's always this tradeoff between don't wanna maintain third party content versus this feature is so super useful ...

**Comment by Draise14** [comment]
Hmm.. yeah, tricky. 

Maybe we can make a warning and optional apply in the warning when switching relevant modes. Ei, go to sculpt mode, and the warning pops up when the object selected is not 1,1,1. 

If the item has multiple users, maybe we can also give the option to "Make single, then apply scale" to whatever is selected, instead of just bug out (addon does this).

But if you are in Pose mode or Object mode (maybe?), the warning is not relevant, neither in texture paint, weight paint, or a number of other modes - so in this case the object context would make it work correctly where it is relevant. 

I don't know what the answer here is, but maybe something small like.. apply scale when starting to sculpt, keep it small, see if it helps the UX of that particual issue in the workflow - either a warning, or a toggle to either warn or auto apply whenever you sculpt - either in preferences or in the sculpt tools options.

**Comment by ReinerBforartists** [comment]
Decision time. 

Fun fact:  a script exists that does what we need. So there is no need anymore to develop the feature. Including the script would be possible, but the author offers the script at Gumroad. Officially for free, but people can spend a few bucks. And i don't want people to steal their income. On top of that, i am not happy with maintaining third party addons anyways.

 And so the decision is easy. This taks has become obsolete. Closing.
