### ISSUE TITLE
Mac build

### ISSUE THREAD

**Issue by seanr** [Bforartists/Bforartists#1814]
@ReinerBforartists don't really know how to reach you anywhere but here since you're not on the Discord (it'd be hugely helpful if you got on there!). Let me know what I need to do to get this out. I have a working Mac version in a typical dmg installer with the new splash as the background and whatnot. I'd like a couple of other people to test it.

**Comment by ReinerBforartists** [comment]
That's great. Many thanks :)

I hear you with Discord. I always try to think at it, but then yet another day is gone and i haven't found the time for. The tracker is always a good place to contact me. Or by PM at our homepage. Or you could write me a mail. 

The only thing you need to do is that you upload the installer somewhere. I download it then, and upload the installer to our webpage.  Do you have a place to upload the file? If not then we will find a solution.

Testing is a bit difficult since we don't have a mac user in our team. That's most probably our users then ^^

Looking forward to the Mac file :)

**Comment by seanr** [comment]
I tossed it up here: https://drive.google.com/file/d/13Qf9vfACOkGZq9u7UoNEq3AnHBllgHhg/view?usp=sharing

What's your email? I'm more likely to use here than email, but going to the website to send a PM is a non-starter. I'm already in Discord literally all the time, and there are a lot of other folks doing Python stuff around there too. I strongly suggest you take the minute or so needed to do it - that's where the user base is.

**Comment by ReinerBforartists** [comment]
Thanks for the download and the time and effort to create the Mac version. Our Mac users will surely be very happy. I have downloaded it, and will upload it now, marked as Beta :)

My email is reiner.prokein(at)posteo.de

**Comment by ReinerBforartists** [comment]
The file is up. Again many thanks :)

Closing this issue as resolved. I will reopen it in case we get some trouble reports.
