### ISSUE TITLE
No icons in menu and graphics glitch

### ISSUE THREAD

**Issue by Wikinggaffa** [Bforartists/Bforartists#1819]
I downloaded bforartists yesterday and the menu missed icons and there is a graphics glitch. See images.

Intel core i7 dual 2,6Ghz, 8 GB ram. Windows 10 (1909).
Intel something graphicscard and a Nvidia card. 

I also downloaded blender yesterday and there is no issue.

![Bforartist1](https://user-images.githubusercontent.com/62139521/93019675-d005bf00-f5d8-11ea-8a2e-939165a7e415.PNG)
![Bforartist2](https://user-images.githubusercontent.com/62139521/93019678-d300af80-f5d8-11ea-8442-21bb444e9819.PNG)
![Bforartist3](https://user-images.githubusercontent.com/62139521/93019682-d5630980-f5d8-11ea-8a5e-2146d91118b8.PNG)

**Describe the bug**
A clear and concise description of what the bug is, and how to reproduce it.

**Desktop (please complete the following information):**
The Operating system. Windows 7, 8, 10, Linux, Mac ? What graphics card? 

**Screenshots, Example Files**
If applicable, please add Example material. A screenshot, a blend file, Or even a short video.

**Comment by ReinerBforartists** [comment]
Thanks for the report Wikinggaffa.

This is a known Blender bug, which is is already fixed in the Blender master. And also our developer version that i have uploaded today should have this fix already included.

https://developer.blender.org/T80327

We will most probably see a Blender point upgrade soon. And then we will also update Bforartists.

Kind regards
Reiner

**Comment by ReinerBforartists** [comment]
Closing this report since we already have a report for it here: https://github.com/Bforartists/Bforartists/issues/1808
