### ISSUE TITLE
3D View - Inconsistent sliders in the Overlays dropdown

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1837]
# Issue

> I know this is nitpicking, but is there a reason, or conscious thought, why Tracks->Size has clickable carrots, and Wireframe and Normals do not?
> Wireframe and Normals are the only two i ever adjust (since I dont like the default values), annd I seem to have to adjust them quite a bit... vOv ... lol
 
![image](https://user-images.githubusercontent.com/35357409/94323702-76987b00-ff5c-11ea-933d-62352a1d488a.png)

From a Discord user. Has a point, they are inconsistent in UX. 

# Task
Make the sliders UX consistent, so you can click and slide and use the buttons to increment them.

**Comment by ReinerBforartists** [comment]
Yeah, sure, worth a look :)

**Comment by ReinerBforartists** [comment]
The whole panel has another inconsistency. The name of the slider should be in front of the silder, not inside of the slider. That's the old Blender method.

**Comment by ReinerBforartists** [comment]
Haha, now i know. C code.

-.-

**Comment by ReinerBforartists** [comment]
Okay, Why the slider shows extra clickable carrots is something that you better ask a Blender developer. I have no idea. It's just one of the proofs that the one and same thing is always implemented in several different ways. And dare you you overlook one of it when you want to change this thing ^^

Separating the issue with the name of the sliders.

**Comment by ReinerBforartists** [comment]
This fish is too big for me. I cannot find where it hides, sorry. I can't even find the icons. This could be because they most probably use the < and > letters here instead icons.

As told, please ask the Blender developers.

**Comment by ReinerBforartists** [comment]
Gotcha. Right after closing the issue i had the right thought. I have a foot in the door. 

source\blender\makesrna\intern\rna_space.c

Line 3831 
prop = RNA_def_property(srna, "normals_length", PROP_FLOAT, PROP_FACTOR);

When i replace the PROP_FACTOR by PROP_NONE, then we get the carrot buttons.

Now we need to investigate what the PROP_FACTOR is good for. And if it make sense to keep these buttons in this sliders. They increment currently by 0.01 steps. Not really useful.

There's by the way much more content with and without carrot buttons. And i still think this issue is best reported to the Blender devs. And be it to have a statement why they treat the sliders different.

**Comment by Draise14** [comment]
Eh... if we keep triangles, that all sliders have triangles. If not, then remove the triangles from the other - but that is a very tall order, as most of the UI has carrots on mouseover. 

I like the triangles, at least we know it's like a slider where you can click and slide it - it shows functionality with no hidden features of a slider. 

For consistency sake, all sliders should not show the triangle carrots unless moused over, like elsewhere in the UI.

**Comment by ReinerBforartists** [comment]
Thanks for your ideas Draise :)

They don't show it anyways until you hover with the mouse over it. But the question is if we should show triangles in sliders where they make absolute no sense. As told, then they are nothing else than visual noise then, disturbing. 

I'm currently to 90% convinced to leave this as is, since the change would make things worse. I search for good arguments for the change. To have everything equal looking is imho not enough reason for a change.

**Comment by Draise14** [comment]
Well.. if they aren't showing till you hover over, great!

**Reason 1:** One of our user artists requested it, we should do it for us as artists. 
**Reason 2:** Consistency is our ethos. Blender would leave it as is because "it looks better". 
**Reason 3:** The carrots are hidden unless you mouse over, great! No noise in the first place. When you mouse over, even if increments are small, you can tell it's a slider from the consistent iconography (another of our ethos) and not just an inconsistent bar that might not look like any other slider in the UI, risking user confusion and feels broken. 

The alternative: remove all carrots from the dropdown menus everywhere, so then any 3D View dropdown won't contain the carrots in a consistent way, then we know those sliders are like that per the system of dropdowns. It won't feel broken because it was a design choice, won't have any extra noise, and it will be consistent to all dropdowns.

**Comment by ReinerBforartists** [comment]
Okay, Still not fully convinced. But task stays open :)

I would love to be able to increase the value when clicking at one of the buttons. Since i found a button that only increases 0.001 steps instead 0.01. But i can simply not find where this is defined.

**Comment by ReinerBforartists** [comment]
The more i think about it the more i doubt the value of this change. It would be an enourmous job to go through all available sliders.

It would be a nice to have. But that's simply too much work and would produce lots of C code that might cause damage with every merge. And just a handful users would even notice this change.

**Comment by Draise14** [comment]
Ah.. hmmm.... oh well. Maybe it should be reported to the Blender devs then. It does feel messy, but if it's too hard to do and maintain......... yeh. I understand..

**Comment by ReinerBforartists** [comment]
Yes, please poke the Blender devs here :)

**Comment by ReinerBforartists** [comment]
Closing this issue therefore. We won't fix it.
