### ISSUE TITLE
Timeline/Dope sheet/NLA editors - slider covers button to call sidebar

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#1867]
The slider covers the button to call the sidebar here.

I could swear i had this reported already. But it is not to find. Anyways, Blender has no content in the sidebar anymore in the dope sheet editor. We have. So it's our responsibility to fix this bug i guess.

![dopesheetslidercoverssidebar](https://user-images.githubusercontent.com/13919702/95433600-7337c300-0950-11eb-9401-327be16b6ee5.jpg)

**Comment by ReinerBforartists** [comment]
Also in NLA Editor. In Graph and Driver Editor it works fine.

**Comment by ReinerBforartists** [comment]
Reported to Blender

https://developer.blender.org/T81532

**Comment by ReinerBforartists** [comment]
No movement. Postponing.

**Comment by iyadahmed** [comment]
Ok got progress, but also startup.blend caused issues like with uvmargin

Newly created dopesheet and timeline arras work great, but the timeline area that is already open in the startup file doesn’t

**Comment by ReinerBforartists** [comment]
Hey Iyad,

It should work to save the startup.blend, and compile with this changed startup.blend again. But you might need to do this for all templates, and depending of the change you might need to go through all included workspaces first too.

The default template is stored in release\datafiles\. The other templates are in release\scripts\startup\bl_app_templates_system\ . And when you save the startup.blend then it gets created in the appdata directory. In my case C:\Users\x\AppData\Roaming\Bforartists\Bforartists\2.92\config

In this special case it would be better though to let the Blender developers fix this issue. There might be more involved than just resaving the startup.blend . Maybe you can also commit a patch to Blender.

Also note that we have feature lock. Means i will not merge pull requests at the moment. I am in the middle of preparing Bforartists 2.60. Blender has released Blender 2.91 yesterday.

**Comment by iyadahmed** [comment]
oh great,  indeed saving startup is the easiest I should close the timeline area and create new one and save it, I was looking for something like a script or so, this should be something that is done often.

ok great, will work on other issues now after pushing and pr this.

**Comment by ReinerBforartists** [comment]
Crazy that such a thing is tied to a startup.blend ...

**Comment by iyadahmed** [comment]
indeed the problem is the area and its all properties including scrollbar props is stored in the file, I fixed the issue by changing a property of scrollbars of dopesheet and timeline (it turned out they are the same entity "SpaceAction") 
so actually it is not only startup blend but any blend created with a version that had the issue

so it is actually one line change in C, we could do this the other way and change how all scrollbar is drawn, but then we need a way to know if we are in timeline or dopesheet, so it would be more changes in C and not straightforward.

when the startup blend is loaded, it already has a timeline, this one still has the old issue, but if one creates a new timeline the new one won't have the issue.

someone on blender.chat suggested to use a versioning_290.c that will apply changes to blend files with version 2.90 when loaded, it seems to be the right way, looking into this now.

**Comment by iyadahmed** [comment]
hmmm the issue seems to be fixed in master

**Comment by iyadahmed** [comment]
no it wasn't hmm

**Comment by ReinerBforartists** [comment]
Pull request is still open. I'll fix the templates once i find the time for.

**Comment by ReinerBforartists** [comment]
We reverted this code, so this task becomes valid again

**Comment by ReinerBforartists** [comment]
I think we should close this issue. We tried it already, without luck. I don't want to run twice into the same trap.

The issue is reported to Blender. And this problem goes really deep. So it's up to the Blender devs to fix it.
