### ISSUE TITLE
3D View - Lights defaults to have Contact Shadows turned on

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#1903]
#Issue
![image](https://user-images.githubusercontent.com/35357409/97060916-9e2e3380-155a-11eb-8f76-3740ae92d812.png)

Right now, when you create a light, the contact shadows in Eevee mode are turned off. Meaning shadows look broken in first use. Unless you know what they are, you wouldn't know how to fix bleeding shadows. Every project I have to turn these on. Another user asks why these are off - I mentioned it might be due to hardware limits - but if you're good to go to use Eevee, you should be good to go to use contact shadows. 

# Request
Turn contact shadows on as a default for all lights.

**Comment by ReinerBforartists** [comment]
Green with this change

**Comment by ReinerBforartists** [comment]
Ah. I just knew i had overlooked something.

When you do a change at the C codebase, then please add a comment where the change is not obvious. Background is, i do a merge every sunday. And for the python part it is clear that most of the changes comes from us. But not for the C part. We do as few changes here as possible. And when a snippet from us is not commented then it can happen that it gets lost with the next merge.

I don't comment changes at tooltips or icons in the c files since here the difference is very obvious.  But for not so obvious changes it is very important to mark them with a comment, like this default here. 

I usually comment such changes in the c code with a

/* bfa - insert reasoning here*/

Task: add a comment to the change.

**Comment by iyadahmed** [comment]
Oh ok will add the comment today, it makes sense to do because it is not
always obvious what the code does, without doing research.

**Comment by ReinerBforartists** [comment]
Indeed. I learned it the hard way, i have lost functionality while merges before ^^

**Comment by iyadahmed** [comment]
great, just got home fixing it now :)
