### ISSUE TITLE
switch to dope sheet operator switches to timeline in some cases

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2023]
if timeline was chosen at first, then something else than dopesheet, switch to dopesheet operator switches to timeline
here's a gif from master
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25552173/100384507-42067580-3018-11eb-8877-f01660bc438e.gif)

**Comment by ReinerBforartists** [comment]
Huh, scary :D

**Comment by ReinerBforartists** [comment]
Hm, no idea. Unassignging.

**Comment by iyadahmed** [comment]
maybe the problem is in the operator

**Comment by ReinerBforartists** [comment]
It is one of these issues that should not happen but happens. The operator is always the same. And so i have no idea what the cause could be. Maybe because some of these "editors" are in real just sub content of other editors, and not own editors. I don't know.

Let me sleep a few nights over this. Maybe i will find the cause.

**Comment by ReinerBforartists** [comment]
Still no idea XD

Digging ...

**Comment by ReinerBforartists** [comment]
My code doesn't work. I have no idea why. 
My code works. I have no idea why,

Fixed :)
