### ISSUE TITLE
Blender 2.63 execution error

### ISSUE THREAD

**Issue by Kumaran7** [Bforartists/Bforartists#2026]
Blender 2.63 crash on startup,shows "EXCEPTION_ACCESS_VIOLATION".i'm using old GPU Amd 5450 whic is not currenty supported by blender. maya 2020 works great and smooth and openGL test show my gpu can support upto openGL 4.5.i dont have enough money to buy new GPU now,please do some thing to fix this error.i can use old verson,but new blender 2.91 have more features that i cant use that makes me stressed out.please dont say "your gpu is not supported".

My spec: i3 3220,Hd 5450,win 10.
Bfor ver:Latest 2.6.0

**Comment by ReinerBforartists** [comment]
Hi kumaran7,

Thanks for the report. We are Bforartists, not Blender. And the current version is 2.60, not 2.63. So i am not sure if you really mean Bforartists.

Looking at your specs it's really simple though to tell what the problem is. Your gpu is not longer supported. And there is nothing that we can do, sorry. When Blender does not work for you, then Bforartists will not work for your neither. We are based at Blender, and always use the newest version.

I would suggest to buy hardware that is supported.

Kind regards
Reiner
