### ISSUE TITLE
Node Editors - iconize add menus

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2043]
We have an add menu in every node editor. I was never able to add an icon here, the content of this menus is an array, which is then shown as a menu. And i have never found a way to connect icons to it.

The node arrays can be found in \release\scripts\startup\nodeitems_builtins.py
The NODE_MT_add menu is in Release\2.92\scripts\startup\bl_ui\space_node.py
And the def draw_node_categories_menu is in release\scripts\modules\nodeitems_utils.py

@iyadahmed , do you maybe know a way to connect the arrays with icons so that we can iconize the add menus here too?

![addmenu](https://user-images.githubusercontent.com/13919702/100846768-3505de00-347f-11eb-8551-b794ca4ca32d.jpg)

**Comment by iyadahmed** [comment]
Investigating into it after finishing the other task

**Comment by iyadahmed** [comment]
![image](https://user-images.githubusercontent.com/25552173/105544361-9588fd00-5d03-11eb-99a8-fa6c962a2264.png)
it turned out this is as easy as setting icon of layout operator in release/scripts/modules/nodeitems_utils.py
we could define a dictionary to map from node type to icon, what would be better is to somehow make use of the node header icons we added earlier #1609
![image](https://user-images.githubusercontent.com/25552173/105544527-c10be780-5d03-11eb-8f9a-4afde743f50e.png)

**Comment by iyadahmed** [comment]
Progress

![image](https://user-images.githubusercontent.com/25552173/108002216-90b02400-6ff7-11eb-97e5-7145994414ee.png)
![Screenshot 2021-02-16 004218](https://user-images.githubusercontent.com/25552173/108002225-9443ab00-6ff7-11eb-895a-6878fb8e2995.png)

**Comment by ReinerBforartists** [comment]
Nice =3
