### ISSUE TITLE
Vertex Paint, Texture Paint Mode - Tool Header UX - Colour Dropdown - Make consistent with Grease Pencil Vertex Colour Panel

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2058]
# Request
Current system in texture paint and vertex paint mode:
![image](https://user-images.githubusercontent.com/35357409/101275319-c40e4100-3772-11eb-8a4d-2fae1937df44.png)

It's a colour picker.. great. 

Current system in Grease Pencil draw mode:
![bforartists_Nt3r9x1fS1](https://user-images.githubusercontent.com/35357409/101275315-beb0f680-3772-11eb-9b8a-78fdf7fb4d83.png)

Wow, it has a pallete manager AND both colours along with the swap (Vertex Colour Mode)

This clearly needs to be setup to be flattened out accross colour painting modes to be a consistent feature consistent colour picking UX. 

# Task
- Investigate if possible
- Add the dual colour and swap (or just the single colour properties)
- Add in the colour pallete manager but with less exposed colours (two or 4 rows, might not be possible)
- Discuss if the stroke mode and mix facter from the GP panel is redundant, or necessary, in the colour picker. If it isn't, this probably should be reported as a new task for the Grease Pencil Vertex drawing mode. 

### Notes
Updating this panel to the other colour painting modes could be a good alternative to this task: #2057

Reason being is that the dual colour and swap is now present in the drop down, and the colour picker is a sub popup just like in the property shelf, making the colour experience consistent with vertex colours in Grease Pencil mode. 

### Alternative Mockup
If we do expose the dual colour switcher and pickers in the task #2057, then the grease pencil dual colour picker inside the panel will redundant and the GP vertex colour panel will have to be modifierd.

Here would be the alternative mockup for the colour selecting UX for all paint modes if the task #2057 is implemented. 
![image](https://user-images.githubusercontent.com/35357409/101275535-5105ca00-3774-11eb-9507-e5148e821b64.png)

**Comment by ReinerBforartists** [comment]
Please just one task at once :)

This design with the palette makes sense for the grease pencil in vertex paint mode. The one color calls the whole panel with the palette so that you don't have to open up the sidebar. I had already a look if we could do the same with the regular color and mesh objects while fixing #2057 above, and the answer is unfortunately no. The grease pencil is simply differently implemented here.

To reduce the palette visually is technically not possible from what i know. It enumerates the colors. We cannot stop in between. And it is imho also no good idea. When you want to have a look at a palette then you better show the whole palette. And not just a fraction of it.

Third point, the switch between the first and secondary color is fixed with #2057 

So nothing left to do here. At least for now. Thanks for the post. But closing :)
