### ISSUE TITLE
Node editor - Box select with tweak tool

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2090]
@Draise, i seem to remember that we had this one working already, but reverted it on  request. I just can't remember for what reason anymore. Do you remember what the reason was?

The culprit here is, i have the tweak tool activated. I want to TWEAK my selection, not to BOX SELECT it again. So clicking in the off should either deselect everything, or with mouse movement move the selected nodes. Like in the 3d view.

In the current way you need to select your selection again and again when we click in the off. Or aim very carefully not to hit the empty space instead. Which then draws a rectangle again ...

This means of course that we need to activate the rectangle tool every time we want to box select something. But that's imho the better way compared to get nagged to death by the box select tool all the time.

![nodeeditor](https://user-images.githubusercontent.com/13919702/101882589-6163dd80-3b96-11eb-856d-5fb68b62e406.jpg)

**Comment by Draise14** [comment]
Reason we disactivated the ability to drag nodes when not clicking on them  (click+drag to move selected anywhere) was because of the accidental mess when click dragging in the space. 

Current system: 
1. To move, click the node, move it by click+drag on the node. 
2. To move a group, select the nodes, move it by click+drag the group.
3. To unselect, click off
4. To select, click on node or click+drag on empty space for box select. 

This is consistent with other software and puts priority on non-accidental movement of nodes. 

Why?
1. Because if you have a node or group of nodes selected and you could click+drag to move, they move.. a lot. If they are off screen and you do this by accident, you've messed up your tree without even noticing. 
2. When you can click+drag selected nodes when clicking off them, you can't connect the nodes and causes bugs, as a miss-click will not drag a noodle, but drag the entire node. Again, messing up the tree.

**Comment by ReinerBforartists** [comment]
Ah, right. Now i remember the discussion. Thanks :)

Well. I don't think the default is this important here. We can also make it Box. Tweak is just one hotkey away.

But to have a way to move things with tweak by clicking in the off is imho an improvement. I had today the situation that i had to zoom out quite a lot. And click dragged in the off then accidentally. And the rectangle opened up ... 

That's why i made this task then :)

**Comment by ReinerBforartists** [comment]
Now if i just could remember what hotkeys and changes it was XD

**Comment by ReinerBforartists** [comment]
Related Shader editor, remove default box select. #1385

We might need to remove the box select now ...

**Comment by ReinerBforartists** [comment]
Oh my. Seems taht the select methods are global. It is not possible to make Box Select default in the node editor and Tweak in the 3d view from what i can see. Still at investigating how i managed to get tweak to be the default at all. I have forgotten it ...

**Comment by ReinerBforartists** [comment]
Gotcha, Gave me quite a bit headache to remember how the default tool is defined ^^

Fixed in master. Node editors starts now with the box select method by default. So no difference to the previous workflow. But with tweak tool it's now possible to tweak the layout a bit more comfortable, in the same way than in the 3d view, with dragging in the off without immediately deselecting the nodes.

[umbauten.txt](https://github.com/Bforartists/Bforartists/files/5786961/umbauten.txt)
