### ISSUE TITLE
Image Editor - hide disfunctional tools and settings for render result

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2142]
When you have a render result in the image editor, then a few things doesn't work. You can't paint, you can't mask. You can't edit it externally (Image menu). And a few things are greyed out, as usual. Resize for example

Either we hide this functionality away, if possible. Or we make it working. Note that i am not sure how much of this task can be done by us. But we should try.

![imgeditor](https://user-images.githubusercontent.com/13919702/103147404-f64d0600-4754-11eb-9a77-1a04ed05da5b.jpg)

![paint](https://user-images.githubusercontent.com/13919702/103147405-f9e08d00-4754-11eb-864a-7fb4169ac5fe.jpg)

**Comment by ReinerBforartists** [comment]
See also this discussion here: https://devtalk.blender.org/t/new-render-window-discussion/16180

**Comment by ReinerBforartists** [comment]
Scratch the "make them working" part. We miss the resources for that.

**Comment by iyadahmed** [comment]
There's an idea for making it work, we can just make an operator that duplicates the render result so that it becomes a "regular" image, then it performs the operation on that

Not sure if it will work just an idea

**Comment by ReinerBforartists** [comment]
Interesting idea for sure. And non destructive. It would not be the render result anymore then though ...

**Comment by iyadahmed** [comment]
> Interesting idea for sure. And non destructive. It would not be the render result anymore then though ...

Right..., but then render result is supposed to be "special", so that idea serves well an an easy fix, but removing them is easier indeed

**Comment by ReinerBforartists** [comment]
Yes, that's the problem here. The render result is a special kind of image. 

It's all about the workflow. The render preview is usually just to show the render result. So we don't need the tools then.

On the other hand, i find the idea to duplicate the image in general not this bad. Could also come in handy with painting textures. And every image editor has this functionality. I don't see it in the Image editors here in BFA / Blender though. And how useful this could be is something to figure out then.

@Draise14 , what are your thoughts here?

The problem with this editor type here is that the Blender devs loves to make it pretty complicated. The UV editor, the Image editor and the preview window to show the rendered result is all one editor. They share lots of code. And so we could run into trouble, no matter which route to go. 

We will see.

**Comment by Draise14** [comment]
Hmmm... I never was for the idea of splitting the image editor into three fragmented systems. I think Blender convoluted things here for not much benefit. 

I would hide non-functional features of a particular modes of the image editor for now to focus their features/workflow though. 

Ideally I would like texture painting, and all image editing features in all modes as one single editor - and if anything, only use one image editor to rule them all. Having two extra modes and editors for the same image data (2D based images set or generated) isn't that obvious - other than it's relationship with other editors and their modes (3D edit mode, 3D texture paint mode, and render result/composite result). Specially since the system is tied together as the one and the same in the datablocks. 

Fragmenting the 2D image editor just adds editor switching time (wasted) to the pipeline.  


Right now the image editing UX is.. not obvious: 
**Example A:** Bake a texture, then paint in 3D or 2D, but if the UV needs correction during a UV bleed, I'd need to switch editor modes. Do another render bake, then paint updates again - I'd need to switch the editor again back and forth. 
**Example B:** I render a scene to do paintovers for conceptualization, pushing it through the compositor. I need to to a 3D paintover again, but before I do that, I would need to fix some UV's on camera projected geometry on my concept art. Now.. that flips through all 3 editors, render, then UV, then texture paint all in one sitting just to do one adjustment. 
**Example C:** I render out a frame with all my lighting, but I need to do feedback on the scene without re-rendering, so I would like to do a paintover, either in 3D space or in the texture paint mode of the image editor of that particular render. I then have to switch editor modes multiple times to just set UV's to get the GP working, o camera project 3D texture paint and set that up, or have to re-render any changes instead of just directly painting on a render result for feedback. 

So.... I have 2D image related tasks in 2 different editor, each with different usecase modes, and.. the UX is just not handy. 

I would combine to one editor if possible, but I know that would break a lot of code and be hard. 

So... minimize the modes operators (don't show disactivated) and maybe expose the editor mode switching to make the UX atleast easier(like the animation editor toggles on a single mouse over and click), and try make the UV and Image editor the same editor  and understood it's just a mode for 2D images - like it used to be in 2.79 days..... Why re-invent the wheel? 

![image](https://user-images.githubusercontent.com/35357409/106403090-ce5b5d00-63fa-11eb-991b-864dbcbceeab.png)

**Comment by ReinerBforartists** [comment]
The modes dropdown box could be an extra task. I am more for keeping it for consistency sake. It shows that this is a mode element. Yes, it adds a few miliseconds to the workflow. But you don't switch this kind of mode every two seconds.

**Comment by iyadahmed** [comment]
> Okay, so you pretty much share my ideas here. Hide away the not needed elements :)
> 
> The modes dropdown box could be an extra task. But i am more for keeping it for consistency sake. It shows that this is a mode element. Yes, it adds a few miliseconds to the workflow. But you don't switch this kind of mode every two seconds.

I see now, many thanks for clearing this up @Draise14
