### ISSUE TITLE
Improve description

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2202]
The webpage is currently not this clear why one should use Bforartists and not Blender. We should go a bit more agressive here. 

Like stating that you loose nothing when you try out Bforartists since it is 100% compatible to Blender. So try it out ...

Especially the features page should get a bit more polishing.

**Comment by ReinerBforartists** [comment]
I think the best is to make a dedicated page for the features from us.

Suggestions, ideas?

**Comment by ReinerBforartists** [comment]
First changes in the first two text boxes at the top of the front page.

**Comment by Draise14** [comment]
> I think the best is to make a dedicated page for the features from us.
> 
> Suggestions, ideas?

I think a dedicated feature page would be great. Show a VS. Comparison with hero sections. Maybe even animated gifs.

**Comment by ReinerBforartists** [comment]
Okay. Then let's make a own page just for this :)

**Comment by ReinerBforartists** [comment]
We have a new page to show the differences between Blender and Bforartists by some examples. https://www.bforartists.de/the-differences-to-blender/

Reviews, suggestions and ideas is highly welcome :)

**Comment by ReinerBforartists** [comment]
Not sure what to do with the features page.

**Comment by Draise14** [comment]
I like the first proposal so far. I think I have envisioned more of a design left then right comparison, then feature benefit method, and a bit of colour coding (blue for BFA, orange for Blender, red for bad, green for good)- but the conversational method of improvements through chapters are alright. The comparative images are also great examples. I think it may need just better sectorization in how it's presented, or a column based system with section cards, with emphasis or added quick list of pro's and con's. Left image + description, then next section, right image + Blender comparison, etc, and then section of pro's and con's of the changes, etc. 

Here is a design wireframe I had in mind, more or less... 
![image](https://user-images.githubusercontent.com/35357409/106402426-6c4d2880-63f7-11eb-9113-be447935dbf7.png)

I know that webdesign isn't that easy, so I actually wouldn't worry about it too much. I will check for grammar tomorrow and take notes of what would be easy fixes. 

**Observations:** 
- I'll check grammar and let you know here, there were some minor things. 
- At the last point about searching for information at the end, maybe show the Bforartists search capabilities inside the PDF to compare, since it just ends with Blender results and no visual comparison.
- Add a quick summery section to the end to do a quick recap of all the content, so you can skim and still not miss a thing.

**Comment by Draise14** [comment]
> 
> 
> Not sure what to do with the features page.

Oh, and to mention, the official features page on it's own is alright, maybe add another row of cards with the GUI highlights: like customizable toolbar, colored iconography, descriptive tooltips, UI discoverability.

**Comment by ReinerBforartists** [comment]
That's actually a good idea. Thanks :)

**Comment by ReinerBforartists** [comment]
I have now added some UI highlights to the features page too. And call this task done.
