### ISSUE TITLE
Node Editor - Button to refresh cache on node trees

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2280]
# Issue
Right now the only method to force refresh a node tree is by connecting and disconnecting any noodle. The idea that trees are cached is not even shown in the UI an there is no actual operator of button to force update a node tree. But trees do get cached. There are cases where some changes are applied, but you won't see an update till the tree structure force updates the cache. 

# Request
Create a button the connect/disconnect something temporary to force update cache. 
1. Make two redirects randomly
2. Connect between two reconnects
3. Delete reconnects
4. Do the script with a button
5. Add the button to the header of the node editor or to a panel.

**Comment by Draise14** [comment]
This is relatively low priority, just a minor UX thing.

**Comment by Draise14** [comment]
Also, the approach is not great...

**Comment by ReinerBforartists** [comment]
Hm. Sounds like a bug. You should report this to blender.

**Comment by Draise14** [comment]
Hmm.. good idea. 
@seanr can you upload a node tree where you found this bug so I can.. then report to Blender? (without FX Nodes)
I can't replicate it yet, but we would need something to showcase it.

**Comment by Draise14** [comment]
Yeah, can't find anything in Blender about it, so should be a task.

**Comment by iyadahmed** [comment]
Indeed the bug is not reproducible that often
it is clear that there's some sort caching
here's a demo of caching, when first time connecting the socket, it takes a sec to compile, after that it becomes instant
sometimes cache doesn't update well, then the bug happens


https://user-images.githubusercontent.com/25552173/110428049-619a4900-80b1-11eb-893d-d878357d02e9.mp4



![image](https://user-images.githubusercontent.com/25552173/110427155-fe5be700-80af-11eb-9192-c213324d99c0.png)
https://wiki.blender.org/wiki/Source/Nodes/Caching

**Comment by ReinerBforartists** [comment]
Thanks for the use case and the report. 

As usual, such issues are best reported to Blender. Of course just in case it is reproduceable with Blender. Which i expect to be possible in this case since we change the UI, not such deep features. We miss the manpower and the knowledge to fix such issues.

**Comment by iyadahmed** [comment]
Indeed, the issue is for adding a "flush cache" button, when we find a way

**Comment by ReinerBforartists** [comment]
Yeah, but that's not our job. It's the job of the Blender developers in the first place :)

**Comment by Draise14** [comment]
I'm trying to find a way to reproduce the issue, but it is not easy - so I can report this to the blender tracker.

**Comment by ReinerBforartists** [comment]
Was this ever reported? ^^

**Comment by Draise14** [comment]
I couldn't find a formula to reproduce the issue. So I could not report it. I think we should just close for now.
