### ISSUE TITLE
Error when trying to enable denoising,

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2282]
Error when trying to enable denoising,
unfortunately this is in website release
![image](https://user-images.githubusercontent.com/25552173/110494608-6f28f080-80fc-11eb-9290-bc098e10f0bf.png)

**Comment by ReinerBforartists** [comment]
Thanks for the report.

I am currently into music, i fear that i won't find the time for a new release before sunday.

**Comment by ReinerBforartists** [comment]
Ah, this one was already fixed while going through the commit messages and updating the manual. 

Lesson learned. I guess next time i really have to update the manual first, and fix the issues that comes up while that before pushing a new release. You never really stop learning.

The prop that is missing is a new option called Input Passes. You can find it already in the developer build. But that's a new feature that will come with Blender 2.93. You can still use denoising. So no complete showstopper bug. Just a UI slowdowner because of the error messages.

Bug is as told already fixed. What remains is to make a point release. Best done after the next merge. Expect it to arrive next week after updating the manual and fixing its issues.

![inputpasses](https://user-images.githubusercontent.com/13919702/110508772-a77efd80-8101-11eb-98c8-50a09161387d.jpg)

**Comment by ReinerBforartists** [comment]
Hmhmhm. I would even say we wait the two or three more weeks until Blender 2.92.1 comes out. Makes no sense to release a new version every two weeks. And this bug is just a bit nasty, and no showstopper. The developer versions brings the fix already.

**Comment by Draise14** [comment]
I'm ok waiting a few weeks for releases. Indeed lately a quick release has come with a couple of issues here and there. And the extra time is good to do hype publicity on socials. Better a polished release than to recommend a dev build after official.

**Comment by Draise14** [comment]
also it allows to test a bit. i do work with the devbuild with work, but i dont typically test everything.
