### ISSUE TITLE
Bug - Can't use focal distance dropper

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2298]
# Issue
![image](https://user-images.githubusercontent.com/35357409/111859020-b046af00-890b-11eb-8e3d-1d1e5c337b1f.png)
When trying to use the eye dropper to select 3D distance, you can't, because as soon as you mouse off the slider, it greys out. 

# Task
Eh.. figure out if this is desired UX
Fix if broken, or report to Blender

**Comment by ReinerBforartists** [comment]
This is by Bforartists design. To add the tooltip to the slider did not work as expected when i remember right. I needed to add a button to have a place to display the tooltip. So that the user knows this functionality exists at all. In Blender this is a undocumented hotkey only tool :)

When you have a better idea, i am open to anything :)

![focusdistance](https://user-images.githubusercontent.com/13919702/111864160-b49cb780-895f-11eb-9557-0cd11e14e014.jpg)

**Comment by Draise14** [comment]
Ah. Hmm... Maybe with another icon? Screen + dropper? To show it is for the view? I automatically thought it was like all the other drippers.

**Comment by Draise14** [comment]
Or keep it greyed out. So we are forced to read the tooltip to know why it is greyed out.

**Comment by ReinerBforartists** [comment]
When it's greyed out then you don't think it's an available tool. It remains difficult ^^

**Comment by Draise14** [comment]
Yeah... A different icon might show how is different then adropper. Instead of greyed out. You do have a point.

**Comment by ReinerBforartists** [comment]
Well it IS a picker in the end. But a hotkey only :)
