### ISSUE TITLE
The program fails to start because of missing "api-ms-win-core-path-l1-1-0.dll"

### ISSUE THREAD

**Issue by 0rkaM** [Bforartists/Bforartists#2349]
As state by the title, the program Bforartists2 v 2.8.0 complains about not finding the above DLL with the error:

> **bfroartists.exe - System Error**
> _The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem._
> 

and even when that DLL is added to the install directory, or in %windir%\System32, or %windir%\SysWOW64 the program fails again with the error:

> **bforartists.exe - Application Error**
> _The application was unable to start correctly (0xC000007b). Click OK to close the application._

This is very unfortunate since at the same time the actual Blender v2.92.0 program starts and works fine.

**Comment by ReinerBforartists** [comment]
Thanks for the report OrkaM.

You run Windows 7, right? The actual Blender version 2.92 still works on Windows 7. But Windows 7 is not longer supported in the upcoming Blender 2.93. And so also not by Bforartists, since we depend of it. We always pull from the master. And our current stable version is already Blender version 2.93 under the hood. The background of this failure is an update in the internal Python module. The newest Python version doesn't support this dll anymore.

There is no solution, unfortunately. Windows 7 is simply not longer supported. I fear you have to upgrade to Windows 10. Or use an older version of Bforartists. I think 2.6.0 was the last Bforartists version that was based at Blender 2.92.

Kind regards
Reiner
