### ISSUE TITLE
New Transfer Sculpt Mode operator

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#2365]
Create Icon, keymap, and manual
![image](https://user-images.githubusercontent.com/25552173/115161158-4fda9700-a09c-11eb-851e-412c98448e70.png)

**Comment by iyadahmed** [comment]
and keymap too
![image](https://user-images.githubusercontent.com/25552173/115161780-d93f9880-a09f-11eb-8496-a5dc79297cd0.png)

**Comment by ReinerBforartists** [comment]
We are not Blender, we don't hotkey every available tool just because you can. I don't expect that this tool will be used every five seconds. So i'll leave it up to the user to add an hotkey here if needed.

**Comment by ReinerBforartists** [comment]
Fixed in master

Needs documentation

**Comment by iyadahmed** [comment]
So this only needs manual right?, gone through changes not many UI changes

**Comment by ReinerBforartists** [comment]
That's the missing part now, yes  :)

The workflow is, first i go through the commit messages. One by one. And check for UI changes. These changes are then changed in the manual. At my way i also document new issues. Like this one here, which needs a new icon. Then i resolve the new issues, like this one here. And add them to the manual too. And at the end of the week i commit the changes to the manual. And everything starts from the beginning.

I could work this way, to just commit once a week, since i was the only one working at the manual so far. Our  current situation is different. Now you are involved here too. And so you need to commit possible changes at the manual first before i can continue to add content. Like document the new operator here.

Just curious, was there even a change this time? The only bigger change that i have noticed besides this issue here was the revert of the lock camera view button. But it made no sense to modifiy this part of the manual while knowing that we add it back anyways.

**Comment by iyadahmed** [comment]
there was changes, but like you said there was not many, here's a list
![image](https://user-images.githubusercontent.com/25552173/115361040-7c87cf00-a1c0-11eb-8d3b-9de96d1ba951.png)
![image](https://user-images.githubusercontent.com/25552173/115361116-8e697200-a1c0-11eb-8398-0bde78aa3a51.png)

I have to fix these:
the gltf import export lost the icon, this is a mistake I think -_-
![image](https://user-images.githubusercontent.com/25552173/115362310-b0172900-a1c1-11eb-96f7-7a16fa51c633.png)

![image](https://user-images.githubusercontent.com/25552173/115362435-d1781500-a1c1-11eb-8dfb-4da245bbedab.png)

**Comment by ReinerBforartists** [comment]
Mh, forgot to mention, to document new operators is part of the merge. So writing the documentation part for the new transfer sculpt mode operator is part of the merge. This task here was to add a new icon then. Which is another update to the manual then.

And ah, you killed the gltf im and export icon in the addons. Gratulations :)

As told, you need to check every addon one by one and line by line, unfortunatel. After a while you know your trouble makers ...

Will make a task here now to readd the gltf icon.

**Comment by iyadahmed** [comment]
yep sorry about that, I'm working on it now

**Comment by ReinerBforartists** [comment]
No problem. Happens even to me sometimes. It's always a good reminder to be more careful when it happens :)

Please make a tracker issue first!

**Comment by ReinerBforartists** [comment]
I made the tracker issue now.

**Comment by ReinerBforartists** [comment]
This is one of those wtf operators. You can switch another object to sculpt mode with this tool without leaving the sculpt mode. Saves you pressiong one hotkey, back to object mode. Which is in the scope of a minute in a year. And adds mode confusion. Blender UX design ...

Anyways. I was wrong. This tool needs an hotkey since it is tied to the mouse position.

![transfer](https://user-images.githubusercontent.com/13919702/115829511-60c63800-a40f-11eb-9f03-70c020181859.jpg)

**Comment by ReinerBforartists** [comment]
Nice. Blender bug too. The tooltip does not show the hotkey.

**Comment by ReinerBforartists** [comment]
Hm. No bug. The tool from the menu works with an eye dropper. The tool called with the hotkey works without eyedropper, directly. So we need to update the tooltip here too, and add some information about the hotkey. Geez, some changes makes really trouble ...

**Comment by ReinerBforartists** [comment]
Oh, and we need to replace this crazy nerd tooltip by something understandable ...

**Comment by ReinerBforartists** [comment]
Phew, that's better ...

Fixed in master

![fixed](https://user-images.githubusercontent.com/13919702/115836039-4abc7580-a417-11eb-879c-2aab29e42cd7.jpg)

**Comment by ReinerBforartists** [comment]
Fixed in master
