### ISSUE TITLE
Make the "New Collection" button context sensitive to outliner view

### ISSUE THREAD

**Issue by slippystance** [Bforartists/Bforartists#2419]
At the moment, the "New Collection" button executes the same function irrespective of the Outliner Display Mode being "View Layer" or "Scene".

Proposal:
Allow the "New Collection" button function to create a "New Scene" when the Display Mode is set to Scene (please see example below).

![image](https://user-images.githubusercontent.com/57046940/118307626-cbfbab00-b49f-11eb-86c7-87f49e916d8f.png)

The above example allows the user to quickly create either a Collection or Scene depending on the Display Mode chosen.

Currently, the user has to access the "Scene Properties" tab to create a new scene.  The solution I'm proposing can expedite that task.

**Comment by ReinerBforartists** [comment]
Hi Slippystance.

Thanks for the idea, but the current way makes sense, since you need to create the collection in the right scene. If even then we should add a add scene button here. But i am not sure and not convinved if this is a good idea. Since we cannot implenent the whole scene property. It would eat too much header space.

![addscene](https://user-images.githubusercontent.com/13919702/118311677-7ef3f500-b4f0-11eb-896d-6ac1945131c8.png)

**Comment by Draise14** [comment]
I think this request is that when in Scene view, that context menu is exposed to a top level so you can create, copy, link copy and delete scenes from the outliner without using the context menu. 

I think here, instead of "make a new collection", the button would "make a new scene" instead (since it's more a scene manager, not a view collection manager)

**Comment by ReinerBforartists** [comment]
Yes, that's how i have understood the request. But as told, we would need to implement the whole scene property since it is not done with adding the scene. You need to see which scene is the active one. And you need a way to switch the active scene too when you create one.

I am still at thinking if there is a way. But we are super short of space in the outliner header. I don't see a way really.

We have the scene property in the Misc toolbar. That way your mouse doesn't need to travel this far when you work with scenes.

![sceneintoolbar](https://user-images.githubusercontent.com/13919702/118314412-65ed4300-b4f4-11eb-9996-6e284d18f4c5.jpg)

**Comment by Draise14** [comment]
Maybe just add a new button with "Add new scene", which just creates a new one, not based off active, just.. a new scene container default.

**Comment by ReinerBforartists** [comment]
As told, it adds confusion just to add an Add new Scene button: That's the Blender UI design. Add the same button everyhwere where it could be useful. I don't want to repeat this mistake :)

**Comment by Draise14** [comment]
Ah ok.. hmm...... what would be the guideline? We have the scene manager system in the Property Editor. We have scene management in the Outliner under scene view, but only in a right click context menu, and in the Misc toolbar group. 

Maybe we need a drop down entry in the header for the right click operators just like we did with the view and collection drop down in the outliner header. Atleast for discoverability sake and easier handling of a quick menu or hotkeys - would that be consistent?

**Comment by slippystance** [comment]
Is there a possibility this can be added via the Right Mouse Button Menu?

In the "View Layer" mode, the options available are as follows:
![image](https://user-images.githubusercontent.com/57046940/118320645-62849800-b4b1-11eb-8d90-4ad2e6a4336b.png)

As you can see above, a "New Collection" option is available

In the "Scene" view, the Right Mouse Button menu only allows deletion
![image](https://user-images.githubusercontent.com/57046940/118320901-b68f7c80-b4b1-11eb-858c-5609beaf7cbd.png)

Would it be possible to add the "New Scene" function within that menu?

**Comment by ReinerBforartists** [comment]
Everything is possible. And when it's just about the place to insert the Add button, then this would be a nice place. It would go around the short of space problem in the header.

But as told numerous times now, the place where you add a new scene needs to be the place where you can manage the scenes too. And this is not possible without the whole property including dropdown list. When you add a scene then you need to open the scene properties anyways. To see which one is active, and to set the active scene.

The culprit is that the outliner is not the place to add content. It is the place to manage content. Collections is an exception here. It allows to manage the content. But everything else is created outside of the outliner.

I will close this issue now. Please be not angry about it. It was a nice idea, but does simply not fit into the big picture.

**Comment by Draise14** [comment]
> But as told numerous times now, the place where you add a new scene needs to be the place where you can manage the scenes too. And this is not possible without the whole property, including the dropdown list. When you add a scene then you need to open the scene properties anyways. To see which one is active, and to set the active scene.

Ah ok... oh well. We are a number of users from discord looking for this - it would be consistent with collection workflows done mostly in outliner. 

The ironic thing is.. the scene view of the outliner IS where you manage scenes, specially when toggling view layer rendering of multiple scenes for rendering and quickly switching scene without using the dropdown list, for animation in multiscene, or for video editing with containers, or when working with scene libraries linking collections between scenes and more, etc - you then would be using the property editor to define the scene render settings, object settings, rig settings, or anything else but the scene management mostly. The outliner scene view shows what's active by highlight, and it has a half baked scene management to remove scene from the right click, not add. Without direct scene management at a top level (other than the Misc group which is hidden by default), the scene management UX requires lot's of UI switching. 

But yeah, no maddness here - it does seem to be a Blender feature they really should fix - and I had a look at the code to verify:

Here is the context menu, it only has "delete" in there and the method they use for this is beyond me. 
![Code_0LFQX3dXmE](https://user-images.githubusercontent.com/35357409/118373604-74337180-b57d-11eb-80bc-fdf73c42ffed.png)

![firefox_jvX9v98ej7](https://user-images.githubusercontent.com/35357409/118373615-7eee0680-b57d-11eb-9a86-8b190fdb5b5e.png)

Though the scene management could be defined by python to a degree, as whatever scene you are in is the context the python calls from the active scene in active window editor - whatever you have on. But making it duplicate, or link copy or copy settings would only be contextual to active, as you say - but it's a toplevel action, as it does this only from active, not from outliner. Unless it "new".. New is agnostic to the active scene - it just makes a new empty new scene and switches to it. 
 
![image](https://user-images.githubusercontent.com/35357409/118373870-9d083680-b57e-11eb-9c1f-7d138261069a.png)
 
That whole panel is a template_ID system so not sure how to break it up into pieces. 

Maybe I'll bookmark this idea for an addon since making new scenes is a python op, and those operators could be added somewhere to make life a bit easier, because yeah.. I have my misc scene group toolbar open all the time, but it would be nice to not need to use 2+ editors to do 1 thing, manage scene data and scene containers.  

So.. thanks for taking a look at it. I will experiment the code later.

**Comment by ReinerBforartists** [comment]
Have a look at the tooltip. Here you can find the single python commands.

![python](https://user-images.githubusercontent.com/13919702/118386597-d8574380-b618-11eb-92f3-23fb0b94f017.jpg)
