### ISSUE TITLE
3D View - Header - Show/Hide entries from Header when tabs activated

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2464]
# Request
![image](https://user-images.githubusercontent.com/35357409/120044178-ef137800-bfd2-11eb-9e3c-bf6bbdf0e68b.png)
We have a toggle for the toolshelf which adds tabs and panels - but when we do this, it create a tonne of double entries and bloats the GUI a bit. 

In Bforartists 1, we had them only in the toolshelf, and these header menus were thus minimal. This made the header menus easier to use, and it also was easier learning the UI with the other tools quicker, instead of using both in an undecided way. It also made the header menus more legible and quicker to scan. 

Would it be possible to show/hide or swap out these menus with the prop that shows the tabs also? 

## Notes
I have seen some addons replace the header entries entirely with their own orders and use before, so in code it must be possible, though it might be a destructive hard code to maintain since there are two variables of the 3D View and it's distribution of tools. Though, it would be great. People in Discord have asked about this.

**Comment by ReinerBforartists** [comment]
In Bforartists we had no toggle to turn the tabs off. I thought of hiding away the content from the text menus when you use the toggle. But this is complicated since we don't have all content in the tool shelf. And so i am not really keen to implement it.

**Comment by Draise14** [comment]
Yeah, I recall no toggle - but I liked the end result with no bloat. Being able to toggle to be like the end result of BFA 1 will be such a godsend. 

And yeah, best finish one thing, then tackle the next! But looking forward to it!

**Comment by ReinerBforartists** [comment]
I have thought now intensively about this issue. It would of course be nice to hide the entries in the text menus when we show the content in the tool shelf. But there are a few big drawbacks then. 

It would heavily complicate the code. And users are not longer able to easily follow Blender tutorials. Which already now scares users away as i just found out by discussing with some. Most of them fear that they cannot follow Blender tutorials anymore when they switch to Bforartists. And so they stay with Blender, even when it is more cumbersome to use.

And so i am in this regards in the dilemma that i would on the one hand love to make Bforartists even more unique. But on the other hand there is the need to stay close enough to Blender so that migrators doesn't completely run against a wall. And so i decided to live with this double menu entries.

Either way, thanks for the idea, but this idea didn't make it, unfortunately. Closing.

**Comment by Draise14** [comment]
Yeah, makes sense. Don't "remove" features where possible. Ah ok. 

Would it still be thinkable even if it were an optional toggle to hide/minimize headers exclusively (not connected to toolshelf)? Like.. minimize header optionally and toggles not connected with the toolshelf?

**Comment by ReinerBforartists** [comment]
This is no option. Not everything is in the toolbar.

**Comment by Draise14** [comment]
Well that's ok then! Onwards to other things.

**Comment by ReinerBforartists** [comment]
That's the spirit! :D
