### ISSUE TITLE
Copy the addons from Blender

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#2528]
**Is your feature request related to a problem? Please describe.**
I have installed a lot of addons in Blender. I would have to repeat the whole process for B4A. This is tedious, simply because I consider that as a duplication of work.

**Describe the solution you'd like**
It would be great if B4A can simply copy the addon data from Blender with a click of a button.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ReinerBforartists** [comment]
Hi raindropsfromsky,

Thanks for the report. This should work like in Blender by a click at the Copy Settings button once you install a new version.

![prefsfolder](https://user-images.githubusercontent.com/13919702/124344448-7ce61280-dbd2-11eb-835d-a3bae76d75fc.jpg)

**Comment by raindropsfromsky** [comment]
I have already selected that. BTW I am using the 3.0 alpha version; not the 2.92 version.
I have created a folder C:\Program Files\Util\BforArtists.
To install a new version of b4a, I select all files/folders of the previous version and delete first.
Then I unzip the new zip file into this folder.

When I started the latest b4a for the first time, it gave a choice between Blender 2.92 and 3.0 (IIRC).
Well, I have only Blender 3.0 alpha (which also I install using its zip file; not with installer).

But now the splash screen does not offer that setting any more.
**It should allow the user to change the settings any time!**

Secondly, I used the **Edit > Open preferences folder** menu option.
It opens a folder that has three subfolders: 2.93, 3.0 and matlib.
But what do I do with these folders?? There are no instructions!
I deleted the 2.93 subfolder experimentally, and restarted b4a.
But it made no difference: The splash screen of B4a did not re-introduce the option to copy my preferences from Blender.

**Comment by ReinerBforartists** [comment]
The option vanishes once you create the 3.0 folder in the appdata directory. Which is done by clicking at "Next". And don't mix Blender with Bforartists. Bforartists uses its own directory. Changing something at the Blender directory does not change anything in the Bforartist directory.

I remember that you are at Windows. So go to 

C:\Users\YOURUSERNAME\AppData\Roaming\Bforartists\Bforartists

Here you might see a folder called 2.93, which is from Bforartists 2.8.0. And a folder called 3.0, which is from Bforartists 2.9.0 and higher.

You could now remove the 3.0 folder. Then you get your option back in the splash screen. And you can load your previous settings once you start Bforartists.

![previoussettings](https://user-images.githubusercontent.com/13919702/124348897-e96e0b00-dbec-11eb-9230-d6f0bd75aca8.jpg)

When you want to copy over addons from Blender, then that's a completely different story. 
You really have to copy them manually over from the Blender Foundation folder to the Bforartists folder in the appdata directory. And activate them manually. Since i do not recommend to copy over the userpref.blend. We are not Blender, and have some different settings. This might work, but there is no guarantee.

Copying over the addons saves you at least the step to reinstall them one by one.

![copyover](https://user-images.githubusercontent.com/13919702/124349065-99437880-dbed-11eb-82ae-6e531eef0c2e.jpg)

Hope this helps :)

**Comment by raindropsfromsky** [comment]
I firsdt closed b4a and then deleted the entire **Bforartists** folder. Then I restarted b4a. But I did not get the **Load 2.93 settings** button in the flash screen.

**Comment by raindropsfromsky** [comment]
I copied the contents of Blender's 3.0 subfolder into Bforartists 3.0 subfolder, and started b4a.
And my Blender addons appeared in b4a.
So far so good. I will now check whether each Addon actually works.

BTW this folder-copying can be done when we press a "Copy Addons from Blender" button, right?

**Comment by ReinerBforartists** [comment]
Fingers crossed :)

> I first closed b4a and then deleted the entire **Bforartists** folder. Then I restarted b4a. But I did not get the **Load 2.93 settings** button in the flash screen.

Yes, because then there is no content from 2.93 in the directory anymore. You need to have the old settings to be able to migrate them to the new installation :)

> BTW this folder-copying can be done when we press a "Copy Addons from Blender" button, right?

We don't have such a button. So i am not this sure which button you mean here.

**Comment by raindropsfromsky** [comment]
Why, a new button by that name! That's what I meant!

**Comment by ReinerBforartists** [comment]
Sorry? ^^

**Comment by raindropsfromsky** [comment]
I meant that we should have a new button that copies the Blender's
addon-related subfolders into corresponding b4a subfolders.

That way, the user does not have to mess around with the folders himself.

**Comment by ReinerBforartists** [comment]
Ah, now i see. A feature request. This is no trivial task. And i am not sure if we should even start to think about it. We could introduce more trouble here than we are able to tackle.

**Comment by ReinerBforartists** [comment]
I assume that this question is resolved. So closing.
