### ISSUE TITLE
differents views on different windows-pcs

### ISSUE THREAD

**Issue by ReaderfRik** [Bforartists/Bforartists#255]
Couldn't find this issue in the existing items, so Ipost this:

The same project, scene, and presets:
left on my laptop with Windows 10, right on my desktop with windows 7.
The desktop has an more advanced (but older) videocard, can that make this difference??

![bfa different views on different pcs](https://user-images.githubusercontent.com/29224963/43995678-eb4c5b46-9db2-11e8-9b82-6159e7fe71de.jpg)

**Comment by ReinerBforartists** [comment]
You mean the pink color? That's no bug, but unfortunately expected behaviour.

The pink color indicates that the textures are missing. Most probably you had absolute texture paths in the blend file. And then moved the file to another location. And then Bforartists doesn't find the textures anymore.

Two ways to fix this. Either you go to the materials, and reload the textures one by one. Or you go to File / External, and use the Find Missing Files button. Here navigate to the folder with your textures.

After you did this it's a good idea to click at the Make all Paths relative button in the same menu, and save the file.

Hope this helps :)

Reiner

**Comment by ReaderfRik** [comment]
I'll study again!
Thanks very much for your helpful and quick reply:))
Regards, Marcel

ReinerBforartists <notifications@github.com> schrieb am So., 12. Aug. 2018
08:00:
