### ISSUE TITLE
Numpad hotkey problem at laptops - alternative hotkeys?

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2561]
A user has reported about not being able to press the numpad comma key since he is on a laptop . And so he cannot center the view to an object for example.

We should go through the numpad hotkeys and have a look if we can find alternative hotkeys at the regular keyboard block. And/or add some of this functionality to our align view addon up right.

**Comment by ReinerBforartists** [comment]
Hm, you can emulate numpad number keys. But not the other numpad keys. And this conflics then with our hotkeys to set the mode. And with the Blender hotkeys to set the collection. Okay, nonsense feature anyways. But there should be a better solution.

**Comment by Draise14** [comment]
I have since stopped using the hotkeys from the numpad, other than Isolate Selection with *. 

I moved "Focus Selected" to the industry standard **F**, and moved brush radius to XCV with V for Radius, C for Strength and X for Tilt respectively, similar to how vertex, edge, face selection work on XCV. It makes everything exposed, no need for double hotkeys when painting, and focusing is super understood as most 3D software use F to focus. I press this key the most in typical workflows. 

Isolate Selection is used in a limited sense, and going to camera is shown in the interface in the widget and also in an optional top right entry. Same with setting camera and isolating selection, so technically, we don't really need to rely on the numpad.

## Solution for View Selection on Numpad:
Remove usability from Numpad by making "Focus Selected" as **F** in all editors. Make it industry standard (F). 
Change conflicts:
1. Edit Mode>Fill with F would be ALT+F
2. Radius with F would be V (free), adding in C for Strength and X for Tilt/Rotation (remove SHIFT and CTRL from brush controls to keep to ONE hotkey)

Expose Isolate Selection in the header as a default exposed button. 

#### Reason to change View Selected to F
We already have a view widget to orientate, and the view angles are also in the header as a default. We have the camera toggle there also. "View Selected" is industry standard F (most software), and it's not hard to implement. We don't techically need the numpad for it's features because of the GUI, so we can put emphasis to GUI and left handed workflow.

**Comment by ReinerBforartists** [comment]
The radius thingie is dangerous. It is also often used. I wish we had more free default hotkey left at the left hand side ...

**Comment by Draise14** [comment]
I have set raidus to V in all editors and modes without any conflicts, same with the others as XC, used it for now more than a year without issue.

**Comment by ReinerBforartists** [comment]
Okay, worth some experiments then i guess. V is face mode in edit mode. But should not conflict with paint modes then.

**Comment by ReinerBforartists** [comment]
Doing changes at the keymap is always a bit fuzzy. There is always the danger to introduce new conflicts. I think we had the focus problem at the table before ...

**Comment by ReinerBforartists** [comment]
Reminder to myself. Don't forget the stencil brushes. And don't forget the tooltips. We have added the hotkey as hardcoded text to quite a few of them to tell the user that this hotkeys even exists.
As told, no easy operation to move the F key to somewhere else ...

**Comment by iyadahmed** [comment]
Hmm why not they enable numpad emulation

**Comment by ReinerBforartists** [comment]
True story :)

I would nevertheless be happy to have a substitute for the numpad zero key. It's unhandy.

**Comment by Draise14** [comment]
I have been using XCV for brushes for a while now. CTRL+V and CTRL+C don't conflict from the modal. I haven't found other obvious conflicts. The **Is Key Free** addon may have to come in handy here...

Keyboard layouts I use is US Standard, ES from Mexico, Colombia and Spain. Colombia ES is the most common layout I use.

**Comment by ReinerBforartists** [comment]
Thanks Draise. Then let's give it a second go.

**Comment by ReinerBforartists** [comment]
Current changes see this pdf. It may be incomplete, i need to check it again.

[experimental_changes.pdf](https://github.com/Bforartists/Bforartists/files/7353069/experimental_changes.pdf)

**Comment by ReinerBforartists** [comment]
Has somebody found the time to test the experimental keymap for conflicts yet?

**Comment by ReinerBforartists** [comment]
I see. It's me again to test this.

I would say we deliver the experimental keymap to the user with version 3. And tell them to try it out, with the hint that this becomes the default with the next point upgrade.

**Comment by ReinerBforartists** [comment]
Ah, no mac version of the experimental keymap yet ...

**Comment by Draise14** [comment]
> Has somebody found the time to test the experimental keymap for conflicts yet?

I have been testing the experimental today. 

Issues
- The outliner is still on` Numpad .` instead of `F`
- I find radius size is the most common brush operator, should probably be best under the index finger (`V`), been using it this way for a year now. Pretty intuitive. But having it under the ring finger is a bit off.

**Comment by ReinerBforartists** [comment]
Outliner has brushes? O_O

**Comment by ReinerBforartists** [comment]
Have changed the outliner key now. And found a frame selected in the asset browser that didn't have a hotkey yet. So added our F here. Consistency ...

Mh, i have left the order for the brushes intact. The reason is the order like in the brushes panel. And here the radius comes directly after strength. I press all three hotkeys with the index finger anyways ...

**Comment by ReinerBforartists** [comment]
Note to myself. Don't forget to change the tooltips when this goes into the main keymap.

**Comment by ReinerBforartists** [comment]
Migration complete.  The new keymap is in place. The old keymap is still available in case something went wrong, now called old. It will remain until after the next release. You never know ...

**Comment by ReinerBforartists** [comment]
Next release is out. So far no problems reported. What is left is to remove the old keymap. We don't need it anymore.
