### ISSUE TITLE
Blender Youtube tutorial did not work in Bforartist 

### ISSUE THREAD

**Issue by jinujohnm** [Bforartists/Bforartists#2570]
**Describe the bug**
The following tutorial in youtube did not work in Bforartist even after trying it for more than 3 times, but it was a success when I tried it in blender. Bifrost did not give the desired result when applying the texture part of the tutorial, which roughly starts at 4:00 minutes of the video https://www.youtube.com/watch?v=Yrif5lXX7WY&t=186s

**Desktop (please complete the following information):**
The Operating system. Windows 7, 8, 10, Linux, Mac ? What graphics card? 

**Screenshots, Example Files**
If applicable, please add Example material. A screenshot, a blend file, Or even a short video.

**Comment by ReinerBforartists** [comment]
Hey jiunjon. 

Thanks for the report. But could you please next time fill the body with the bug description, and the title with a SHORT description of the bug? ^^

**Comment by ReinerBforartists** [comment]
Hm, the tutorial covers virtually everything. And this means i cannot help you with your problem here. You first have to tell me  what exact step fails.

And you mention Bifrost. But Bifrost is a Autodesk Maya addon.

**Comment by jinujohnm** [comment]
I think I mixed up the title and the body together. My bad.
In the tutorial the step which did not work in Bforartist, was the applying of the texture to the pile of cubes. That step starts at about 4th minute of the video. Thank you for the reply.

**Comment by ReinerBforartists** [comment]
Thanks for clarification :)

No bug. Your problem is most probably that the other cubes does not have a material yet. In the Blender tutorial you most probably started with the default Blender cube. And this object has already a material applied. And when you duplicate this cube then it still uses the same material.

You simply need to make sure that all your cubes have the same material. There is luckily a way to give every cube the same material afterwards. So no reason to redo the whole scene.

- Select the cube with your material. This cube is now the active cube.
-  Select all
- Go to Object , Link/Transfer Data and click at Link Materials.

The other cubes should have the material from the first cube now :)

![linkmaterials](https://user-images.githubusercontent.com/13919702/127733013-f6bfaf93-c6cf-4daf-b97b-c9eb21f40217.jpg)

I hope this helps :)

"Bug" resolved. Closing :)

**Comment by jinujohnm** [comment]
Thank you for the reply.

**Comment by ReinerBforartists** [comment]
You're welcome :)
