### ISSUE TITLE
Property Shelf Icons - Increase Size for more visual realestate

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2589]
# Request
![unknown (2)](https://user-images.githubusercontent.com/35357409/128383605-3d277201-f679-42ec-821b-ae9570a77598.png)

A user in Discord pointed out that many of our icons are a lot smaller compared to Blenders native ones, though we have more details, the size looses the legibility - they have less pixel real estate than those in Blender. I recall that we added padding to the icons, but in this group of icons the padding may not be necessary.  

Goal here is not only legibility (which we have with color and lineart and form), but clickable realestate psychologically. A couple of pixels larger here and there.

**Comment by ReinerBforartists** [comment]
Fixed in master. 

Improved are three icons. Which is for me more a change for the sake of change than a real improvement. But be it this way. The rest makes no sense. We don't need to fit to Blender icons, but to our own iconset.

![fixed](https://user-images.githubusercontent.com/13919702/134386449-8fd5b4f0-0466-4086-ba36-a97b16d75f48.jpg)

**Comment by Draise14** [comment]
Thanks for doing this. This is for the artists who reported this so it will make them happy. The three changes are really nice. Thanks again.
