### ISSUE TITLE
Blender 2.8 -Rotating the scene switches to Perspectivic mode

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#259]
When you are in orthographic view mode, and in an ortho view like top view, and rotate the viewport with MMB (we have it with RMB), then the mode jumps to perspectivic view mode. 

Shouldn't happen. The key to switch between ortho and perspectivic is numpad 5. And there is no other hotkey assigned to this functionality - Turns out that this is a Blender bug. Should be reported when the Blender 2.8 tracker goes live.

![mmbrotate](https://user-images.githubusercontent.com/13919702/44259335-7e2fb680-a211-11e8-85e9-e5d1c5e8413a.png)

**Comment by Draise14** [comment]
I personally like this feature - as I have that turned on as default in BFA, as... seeing things in Ortho when rotated in "3D" is.. really unnatural and Ortho with "perspective" based rotation angles is prone to clipping bugs on the grid on top of it all. 

Ortho is essentially removing the third dimension and when rotating in Ortho converts your "3D" to only 2 dimensions - things go weird. Rotating angles in 2D is.. secondary and really not 3D friendly. This is probably intentional design. I can see why. 

But yes, the toggle should not be widget based on automatic. Max, Maya, Softimage, trueSpace - are the ones I've used and are consistent to that design. Blender is now the oddball by changing Ortho/3D with the View Widget rotation automatically. It should have Ortho disabled on default, and only toggled on demand.

In fact, usually in Softimage, the angles selected on the widget are based around the selection, like a focus + change view angle.

**Comment by ReinerBforartists** [comment]
Blender devs have meanwhile fixed this issue.

Closing.
