### ISSUE TITLE
Icons - Select and View icons - "Squarify" for more realestate

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2590]
# Request
![comparison](https://user-images.githubusercontent.com/35357409/128385329-e59d5d46-b561-4bac-a8a3-2902d0d412eb.png)

The select and View icon are detailed, but they are either thin or flat, meaning the square clickable area of the icons are rectangle in logic. When comparing to blenders "square" realestate icons, they have quicker selection and silhuette. 

A user in discord pointed this out, and it does make sense. 

Maybe we can "squarify" the volume of the eye and the mouse icon a pixel or two. 

We can also make the coloured lineart a similar colour, or similar contrast.

**Comment by ReinerBforartists** [comment]
The issue here is when i make everything bigger then we have more visual noise in the outliner.

**Comment by Draise14** [comment]
I had a quick look in the SVG, we could push the eye corners in, 1-2px each side , and scale upwards 2px. Keep blue circle round. 

The mouse select could have a larger triangle, shorter stem. Then it would be "wider". 

Overall is to still keep padding, but just make the general shape consistent. Padding being 2-3px from icon edge. 

And here would be the tip to reduce noise:
1. Make line colour of select and lineart the same (currently dark grey and black which isn't consistent and noisy)
2. Also make the lineart of the blue circle on the eye just one colour, or remove the dark blue ring on it, just keep the specular shading, not refraction. 


_I do have to admit though, when I opened the SVG file, I see a lot of the icons are raster art converted to vector, and line width and colour is not set in the vector data, but the lineart is really set by fill data of another vector object, with vectors defined both sides of the lineart! Which.. slows down the drawing of so many icons a lot, and makes editing really slow and painful, ei, lines are drawn as a new object with many vertices instead of one object with one line in the fill property.  I can understand the pain it would be to do updates to icons - the workflow is do the individual outside then convert in a single SVG, then copy and paste it's position with correct labeling? _

**Comment by ReinerBforartists** [comment]
> I do have to admit though, when I opened the SVG file, I see a lot of the icons are raster art converted to vector, 

It's all of them. My pipeline is to create a raster icon first :)

**Comment by ReinerBforartists** [comment]
I stare at this since weeks. And since weeks nothing has changed my mind that the current icons are perfect as they are. The clickable area is the same, no matter how big the icon in the middle really is. Making the icons bigger makes them more noisy. Removing the black outline makes them stick out fewer when they are selected. Means no matter what i try, the result is not as useful as the current one. If even then i would make the viewport icon smaller. It is currently slapping into your face. But even this icon is fine. Especially since we don't have it activated by default.

This would a change for nothing, with the outcome to make it possibly worse. And this means that i will not fix it. Sorry.

Closing.
