### ISSUE TITLE
Loop select with double click like in Maya

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2642]
Draise brought up the idea to select loops like in Maya. It's more intuitive. And you don't need to hold down a key then. Means faster.

Question is if this solution is reliable. This one would be a vital change, and needs heavy testing!

**Comment by Draise14** [comment]
I'll change it to test. I used it a while like this with Context Select Hybrid addon that a user in the Discord made. But is also improved how CTRL+LMB would walk across meshes.

**Comment by ReinerBforartists** [comment]
Any progress? Or still in the crunch? :)

**Comment by Draise14** [comment]
I have used double click as select linked. The edge looks I haven't got used to it. Here is the reason:

So double click while modeling is fine. 

My testing argument is there is no pre-highlight on loop selection to then double click. We also have two modes, loop horizontal and vertical. So when using it it is hard to predict where it will happen. Unless you have the edge selected already. In this case I think something more broad and less precise would be best for a double click.

I've been using double click to select linked a lot more than the loop tool since not all models contain loops also, and it is a common mouse action to use so best to use something more common. 

I think in general blender sorely misses pre-highlight of geo like almost all other software. This makes it harder for quick mouse movements in everyway. You have to manually preselect your active edge then loop. Best one click here than two. (The old way with hotkey and mouse)

**Comment by ReinerBforartists** [comment]
Thanks @Draise14 . So shall we close the task?

**Comment by Draise14** [comment]
Sure.
