### ISSUE TITLE
bundle-identifier of 'bforartists' and version number of 'bforartists-player ' broken on macOS

### ISSUE THREAD

**Issue by core-code** [Bforartists/Bforartists#266]
bforartists:
the bundle-identifier (CFBundleIdentifier in the Info.plist file) of Version 1.0 of bforartists is "org.blenderfoundation.blender", which is a very bad idea. you are a different app, you need a different bundle id. else you are going to mess up preferences and caches between both apps.

bforartists-player version number:
i've downloaded Version '1.0.0' of 'bforartists-player' but when selecting it in the Finder and using 'Get Info' it shows Version '2.79'

**Comment by ReinerBforartists** [comment]
Hi core-code, and thanks for the report. 

Yes, that's bad. The first one is clearly a bug. And needs a fix.

The second issue, well, the player is from Blender. We don't have our own player. And it is made for Blender 2.79. So this version number is correct, since Bforartists 1 is based at Blender 2.79. We might or might not be able to fix this issue. It's a bit more complicated with this internal version number.

However. We won't investigate this issues in Bforartists 1 anymore. This development cycle is closed. But the issue stays open for the upcoming merge of Blender 2.8 into Bforartists.

Postponing.

**Comment by core-code** [comment]
thanks! glad to see you'll fix the bundle identifier for the next version

**Comment by ReinerBforartists** [comment]
We have unfortunately no Mac maintainer anymore. As stated above, the issue won't be fixed for BFA1 anymore. And BFA2 does not have a Blender Player anymore. 

So closing this issue as won't fix. Sorry.
