### ISSUE TITLE
Lock on Constraint transform space 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#273]
# **Request**
Lock on constraint transform space so you change one target and both targets would change (target and source) -

![pureref_2018-09-03_15-51-16](https://user-images.githubusercontent.com/35357409/45001293-8ae23780-af91-11e8-96e2-24ca7b0c291e.png)

## **Describe the solution you'd like**
It is rare I use two spaces on the same constraint and often looks and feels like it's broken as soon as you swap one of the spaces and not the other - best to make it look like it's working by having them locked/mirrored on default. 
By adding a little lock icon between them, you can toggle one space and the other will toggle also to the same target space.

**Comment by ReinerBforartists** [comment]
Hm, this is a feature, not UI. So best is to report this to the Blender devs too.

**Comment by Draise14** [comment]
It's a feature? I posted this one to the Rclick community. 
https://blender.community/c/rightclickselect/fbcbbc/lock-on-constraint-transform-space

_Does Blender tracker even give as much heed as this one here?_

**Comment by ReinerBforartists** [comment]
Well, it's a gamble. Feature requests may or may not be fulfilled. Most of them gets ignored, and sinks over the years. But some makes it through.

Here we could do such changes. But it is more theoretically since i want to keep the C code part as unmodified as possible to make our life with synchronizing with Blender as easy as possible. And i miss the needed knowledge for this operation anyways.

**Comment by ReinerBforartists** [comment]
Makes no sense to keep it open when nobody develops it. This is a task for Blender devs. Closing.
