### ISSUE TITLE
Add asset browser workspace

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2750]
I had once planned to add the asset browser under the hood of the properties editor. However, it comes with functionality in the tool shelf area and the sidebar. And does simply not fit. Even the header is too wide. It does not even show all content when i collapse the menus.

So where shall we add the asset browser? Make a new layout and split the 3d view into two halves? Or shall we find a way to fit the asset browser into the space of the properties editor? I don't want the user to pull the window around all the time because the space doesn't fit.

![assetbrowser](https://user-images.githubusercontent.com/13919702/139645425-e680ef22-0dac-4cae-a98d-ea76ab02115a.jpg)

![wastedspace](https://user-images.githubusercontent.com/13919702/139646061-8451f4b8-f3cf-4afc-9629-cdc854289ee5.jpg)

**Comment by Draise14** [comment]
I have a new workspace "Layout" that has the dopesheet/timeline editor replaced with the Asset Browser. 

Another user in Discord made a button that exists in the corner of some editors that opens a floating panel of the asset browser. Like a pop-out.

**Comment by ReinerBforartists** [comment]
Thanks Draise :)
I love the idea with the popup. But am unsure how to do this. And the asset browser would need a big button, which is at the contrary big and visual noise in the time you don't need it. So i guess new workspace makes more sense then. 

Mh, Blender has also no solution for it yet. Shall we wait a bit longer then?

**Comment by ReinerBforartists** [comment]
Hm, you say you have placed the asset browser at the ground? This would be a mockup for a workspace with split view.

I find it plain crazy how few space is left for the actual assets. You need at the left your categories, and at the right your settings for the selected asset. So much visual noise, and so many wasted space ...

![spacefortheassets](https://user-images.githubusercontent.com/13919702/140021361-1be17d51-d0d8-4afe-beea-423089f6ca91.jpg)

**Comment by Draise14** [comment]
Yeah I keep it on the ground for this reason. More columns for items. Also it's standard in most software like Unity, Unreal, Substance, Quixel Mixer, Marmoset, Mudbox, Armourpaint, etc. Most libraries are placed bottom with view top. 
The 3D view also is widescreen for easier layout. Instead of vertical. You place more horizontally than vertically to compose layout as widescreen is more a standard than portrait video and art.

**Comment by Draise14** [comment]
Also... have they removed the list view? you can change thumbnailn sizes and to list i think. obviously probably needs to be exposed to header in a other task.

**Comment by ReinerBforartists** [comment]
Yes, is removed it seems.
I would love to have a asset lib like in trueSpace. This one was amazingly compact and really nice to use.

**Comment by Draise14** [comment]
You have to customize your catalog as if tags.. then assign the assets to them. So like.. for materials, world, etc. Before they were separate by data blocks, now it's user set by tags "Catalogs". 

So.. first make a tag, then go to Unassigned, and tag your asset.

**Comment by ReinerBforartists** [comment]
Ah. Oh my. So unintuitive again :/

Many thanks Draise. Updating the manual ...

**Comment by ReinerBforartists** [comment]
Implemented in the typical Blender manner ... -.-
![fubar](https://user-images.githubusercontent.com/13919702/140164262-a2c0a728-54cb-4d3c-804e-9454560ae789.jpg)

**Comment by ReinerBforartists** [comment]
Draise i fear i need your further assistance here. I have added a tag and created a catalog. But the asset is still in the All category. How can i add it to my material catalog?

![how](https://user-images.githubusercontent.com/13919702/140164783-7440ea58-460c-4ea4-908f-bee5f907bd8b.jpg)

**Comment by ReinerBforartists** [comment]
Ah, have it. Save the file. Then drag the asset into the catalog. Sheesh ...

**Comment by ReinerBforartists** [comment]
I have made it a task now. We will have a workspace for it. I am just still unsure if vertical or horizontal. The horizontal one has more space. The vertical one doesn't require you to pull the window around to edit the tags though ...

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/140182744-a068a543-9381-40c9-b743-e5ac36c6c631.png)
Ah, it's simpler. Just drag and drop. Tags are something else different from Catalog, sorry for the confusion. 

I vote for horizontal, similar to the node, shader or compositor modes and consistent with most other libraries in most software.. 

Truespace was great because you had a panel for each category or file type, and the thumbnails and grid had no titles and fit nicely in a column with the panels.. but here we have no panels. So this system can't be possible without a multieditor column (not flexible, hard to collapse "panels"). 

In the future, we could develop a panel per category in a tab in the property shelf, then it would be very similar. For quick drag and drop, or adding? But that will depend on the API. How you draw and populate new panels per category must be.. a spaggetti monster.

**Comment by ReinerBforartists** [comment]
Thanks Draise, i found it out already :)

You could make a mockup if you want.

**Comment by ReinerBforartists** [comment]
What about this ?

We need one 3d view and one material view. That's imho the two most used library types.


![mockup](https://user-images.githubusercontent.com/13919702/140281745-837cd5ae-36bb-416f-8067-a0fe729ef063.jpg)

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/140330270-9deb34ec-28e5-47c0-a3ef-c4204232e073.png)

Here is my layout proposal:
1. The outliner is full hight at Blender File view (to mark assets first from a single place)
2. The browser is bottom (for consistency with most editor UX and other libraries in other software, and for more columns)
3. The 3D view is top center with a 16:9 ratio almost (for layout composition and use of the browser)

## Reasoning

There is a huge UX flaw with the Asset Browser. You can't use the browser till something is marked. You can't mark evidentially because everywhere it's different and hidden. Only consistent place is in the outliner, but the default View Layer method doesn't show all assets in a Blender File. 

Here is the reasoning to the layout proposal:

1. Creation of Assets UX
- You can't use the Asset Browser till something is marked. 
- To mark something, you have to go to many different panels, drop downs, icons, and hidden menus in many areas, or use the outliner exclusively. 
- The best way to see all the assets, materials, and library data blocks of a blender file.. is in the Blender File view of the outliner with it's filters. 
- After marking assets, this is when you can use the editor, so eitherway, you have to mark assets in an outliner first and foremost (or elsewhere). 
- So after marking assets, you can now use the browser, so eitherway, you have to start outside the browser, so an Outliner in Blender File View would make sense to start there: left to right - mark asset, use browser, place in viewport.  
- So.. do you hide the method to even start using the browser in all the editors? Or do you put priority to a one place find all solution in a single editor? It is best one obvious place for a single solution for all asset marking. 

2. Layout Placement and usecase
- The browser is good for scene layout, but you need a close to ratio view for layout placement, so a 16:9 ratio viewport or camera ratio would be best for the composition and placement of assets.
- The browser to bottom is also familiar. 
- The right side is just generally exposed for consistency. 
- You use collection and objects to place and decorate scenes, done in 3D view. 
- You use world and scene data to place into the 3D view
- You use materials into 3D view to assign - practically the duo of 3D view and Asset Browser should be equal as they work together and for each other. 
- The only exception for the assets is node groups, but that would be second priority. 

# Feedback of first proposal:
- I like that the node editor is exposed for node groups and such, but you can't assign materials objects in the node editor. It would only be useful for node groups. The shader editor would be useless for world, collection, object, poses, even materials  nearly 90% of the asset browser data block use case would not be relevant for a large chunk of the view space. 
- We also have 3 node editors that would be exclusively relevant to node groups, the GN, the Shader and Compositor - which has priority and for which node group? Further watering down the priority of having that Node editor exposed. This may leed to furstration for beginners when making a GN node group that can't work in Shader Nodes on top of that - hiding also the other 90% of the relevant content for the 3D view. 
- We still have the starting UX issue.. we can't use the Asset Browser till we have marked.. SOMETHING.. and it's not evident nor consistent where you can (multi editor, multi method). 
- Though, for node groups, it is nice to use the asset browser in with nodes immediately, drag and drop - which adds a lot of functionality to the editor without clogging it with pre-built saved nodegroups. But like in the 3D view, the Pose Asset Browser tabs should also have a Node Group Asset panel and tab for the relevant node groups for that relevant editor and mode - but that's up to Blender I think.  

So.. I wouldn't consider the Node Editor necessary in the browser use case, but more the outliner in Blender File mode, and put equal relation between 3D View and Browser.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/140334719-1dee49a0-0771-4752-b06f-35e0686da7cc.png)

Though, with the thought of node groups, I would change the file browser to Asset Browser without a doubt.

**Comment by ReinerBforartists** [comment]
I cannot put the outliner to the left. This is in contrary to the left tools right settings philosophy.

> but you can't assign materials objects in the node editor.

Yes you can. But you can't drag a material asset directly into the shader editor again. You need to drag it onto a selected object. Hmmm. I still think we should wait a bit longer until the asset browser is a bit more evolved. 

![markasset](https://user-images.githubusercontent.com/13919702/140642180-ff6b71c8-ccbb-46ee-8f3e-c865ba13188e.jpg)

**Comment by ReinerBforartists** [comment]
Let's add the asset workspace, and then adjust it when there is a need for.

**Comment by ReinerBforartists** [comment]
Fixed in master

![assetsworkspace](https://user-images.githubusercontent.com/13919702/140643530-ba246181-d464-444f-9bcf-89ee501ecf51.jpg)
