### ISSUE TITLE
Outliner - Scene View - Add Scene creation operator to header, and scene duplication operator to context menu

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2792]
# Feature Request

In a full screen mode of the Outliner under Scene view, you can delete scenes, but you cannot create, make a linked copy, or make a new scene from the Scene view of the Outliner. 

**Current Scene context menu:**
![image](https://user-images.githubusercontent.com/35357409/142910664-b62d1b58-7219-4226-bc7a-089d2c82cfe7.png)

**Added operators to the Scene Context menu that would be useful**
![image](https://user-images.githubusercontent.com/35357409/142910659-d4c07c40-8151-48c9-a6c4-6ce460521979.png)

Could we add these contextual operators to the right click menu on scenes in the Scene view to make the Outliner Scene View much more usable? (not just to delete, but also create and duplicate linked, new scenes, etc)

## Reason
![image](https://user-images.githubusercontent.com/35357409/142911140-59b1db88-9af0-4828-878d-072ddd20074b.png)

When using a full screen outliner in a second monitor, or using the scene view of the outliner for scene management to render multi-pass systems, you have to dig to add or create duplicate scenes. You're in the outliner, then you have to either go to the top right corner on the other screen to a Misc toolbar group to manage scenes OR you have to go to the Scene tab in the property editor to manage your scenes. Both in editors that are disconnected from the outliner scene management view.  

We already have the operator "Delete Scene" located in the scene management dropdown system and in the outliner, but the other operators are missing from the UX. To have the ability to not only remove scenes, but also create and manage scenes in the Scene View of the Outliner would... save a tonne of time zig zagging through different editors to manage one thing.. scenes (or Render Passes).

**Comment by ReinerBforartists** [comment]
Mh, the outliner is imho not the place to create objects. It's the place to manage objects. It will add lots of confusion when we make it a place to create content too.

**Comment by Draise14** [comment]
I think the current method is more confusing at the moment. I hit walls with new users and this feature often, and in production this slows things down a lot. 

We already can make collections from outliner. So it's a consistent method to make scene containers also.

**Comment by iyadahmed** [comment]
Right, collections there is that button up the outliner

Maybe a button like this for new scenes, and duplicate options in context menu?

**Comment by ReinerBforartists** [comment]
Mh, as told, the outliner is not the place to create content. It's a place to organize it. Collections is a element to do this organization. So this fits into the concept. Scenes not so well. This is already content.

To speak for me, i was never confused. A normal user will not touch the scenes features at all. He will create a completely new scene from the file menu.

**Comment by Draise14** [comment]
You cannot create scenes from the file menu... or are you refering to making new blend files?

Scenes are also containers to organize elements. They are containers to organize render settings, organize view layers and to organize collections. They are not objects nor content, but containers for content, just like collections. 

_I am requesting this for any user that does rendering for VFX or animation, as you don't render only from view layers but scenes. It may sound like a power user experience, but you don't create new blend files per render pass, you use scene management. There are quite a few reasons - and to label them "objects/contents" is a mislabel. They were "collections" before collections came out in Blender 2.8. Also.. seriously, I burn so much UI time zigzagging around the interface just to manage new scenes, even delving into scripting to do this because the old system is not great nor intuitive. Regardless of unhiding the drop down it in the Misc group. It's not an inconsistent UX, just something more refined. _

**Comment by Draise14** [comment]
Just to say, every animated project from the studio and co-workers requires scenes, I have no exception where scenes are not used.

**Comment by iyadahmed** [comment]
Outliner might not be a place but it has this functionality for collections, having scene too is useful, and it is not much clutter

**Comment by iyadahmed** [comment]
![image](https://user-images.githubusercontent.com/25552173/142923022-e3081a5c-e1bf-40a0-8285-41a979c68231.png)

**Comment by ReinerBforartists** [comment]
Yes i mean new blend files. And then append or link from then, Most users are not used or even aware of  the concept to have different scenes within a blendfile. This is highly advanced stuff.

**Comment by iyadahmed** [comment]
> Yes i mean new blend files. And then append or link from then, Most users are not used to or even aware of  the concept to have different scenes within a blendfile. This is highly advanced stuff.

Ah ok, so scene options should be added for sake of consistency with collections, and also convenience imo

**Comment by ReinerBforartists** [comment]
You really give me a tough time to keep Bforartists consistent ^^

**Comment by ReinerBforartists** [comment]
I'm not fully convinced yet. Give me some days please :)

**Comment by iyadahmed** [comment]
So what should be done 😄, if the task is ok I can try to tackle it

**Comment by iyadahmed** [comment]
> I'm not fully convinced yet. Give me some days please :)

Ok

**Comment by ReinerBforartists** [comment]
No rush. I first have to think through all conseqences before i can give green light here. Or tell my reasons why to decline the task. As told, at the moment it collides with the concept of having the outliner to organize the content. Not to add new content :)

**Comment by iyadahmed** [comment]
Ok :)

**Comment by ReinerBforartists** [comment]
On with struggling with this idea.

We have deactivated the general right click menu in the outliner since we have all its content top level UI already.

To add the new scene functionality to the right click menu when clicking at one of the objects in the hierarchy doesn't make sense. Since you don't want to create a new scene from a mesh cube. So the only place that makes sense to me is the header, besides the create collection button. And not in one of the rmb menus. That way the create new scene functionality is also easy to discover.

Thoughts?

![thinking](https://user-images.githubusercontent.com/13919702/143011952-6ffe3a18-394d-4ef8-9864-64dfd0b361a0.jpg)

**Comment by iyadahmed** [comment]
When right click a collection in outliner it shows this menu![image](https://user-images.githubusercontent.com/25552173/143012558-20829277-7615-4926-bfce-42c71deb3101.png)

**Comment by ReinerBforartists** [comment]
Yeah, but a collection is already part of a scene :)

**Comment by iyadahmed** [comment]
> Yeah, but a collection is already part of a scene :)

Ah yes, but scene has same operations and they are not exposed

**Comment by ReinerBforartists** [comment]
I disagree. A scene is the container that contains the collections. It's the most upper hierarchy.

**Comment by iyadahmed** [comment]
> I disagree. A scene is the container that contains the collections. It's the most upper hierarchy.

Yes I realize but it has those this operations already, just like collection, they are exposed in the scene selection, but not in outliner, which makes working somewhat not convenient

**Comment by ReinerBforartists** [comment]
I think we talk about two different things here. Where is a create scene in a collections menu to find?

**Comment by iyadahmed** [comment]
my bad, scene has it special place in outliner
![image](https://user-images.githubusercontent.com/25552173/143018756-a1c0f5af-652e-4f58-bbb5-62b14cd4d6d4.png)

but only delete options is available there
![image](https://user-images.githubusercontent.com/25552173/143018805-3a529e2b-1a50-488b-9d89-c3f562168c98.png)

although scenes support other operations like new/ duplicate and such, which belong to outliner too, just like the collections in outliner have a new/duplicate options

![image](https://user-images.githubusercontent.com/25552173/143018958-560dc418-ce9e-4505-a142-5928dfde3356.png)

**Comment by ReinerBforartists** [comment]
Yes scenes has its own mode in the outliner :)

And yes, like with any other content, you can delete it, but not add new content. That's the part why i still struggle to add the add scene to the outliner at all. Consistency. When we start to allow to add content from the outliner, then we run in big trouble.

The collection is as told a very special element here. It is no content in the classical sense, like a mesh object. But allows you to organize your content. And this fits into the outliner philosophy.  One could argue that a scene is an equal container to manage content like a collection. And that's why the task is still open. I tend more and more to agree ...

Back to the problem where to add the add scene button. I already told my arguments. You don't create a cube from a mesh. You create a cube, and this cube has already a mesh . Same goes for scenes. You don't create a scene from a cube or a collection. You create a scene, and then add a cube or a collection to it. Hierarchy. And so it is no good idea to add the create scene menu to a sub menu that comes up when you click at a collection for example. This does not belong together.

And this is why i think that the only logical place for the add scene menu is the header of the outliner, in scenes view mode. This is the mode where you deal with scenes.

Trust your designer ;)

**Comment by iyadahmed** [comment]
I agree, and your points are absolutely right, but I think there's something more I should show, the right click menu that should have the scene new/copy options, is the right click menu that appears when you right click **a scene** in the outliner

so it doesn't go against the points mentioned, it agrees with most of them

**Comment by ReinerBforartists** [comment]
This is imho again a hierarchy problem. You cannot create a scene within a scene.

**Comment by iyadahmed** [comment]
> This is imho again a hierarchy problem. You cannot create a scene within a scene. This works with a collection. But not with a scene.

yes it doesn't create a scene, inside (not nested)
see collections for example has New and New nested

scenes should have New only
![image](https://user-images.githubusercontent.com/25552173/143021078-2593eb96-b4a6-4703-9dbc-ccb6180b42f8.png)

**Comment by ReinerBforartists** [comment]
Yes, but Copy and copy linked also creates a new scene. It does imho simply not belong into the rmb menu

You see how difficult the matter is? And why i was against a quickshot here ? :D

**Comment by iyadahmed** [comment]
yes I agree it is not an easy matter to decide, but it will improve UX and prevent switching editors, and Scenes have a special place in outliner so we are not hacking or introducing something new,

new operation will create a new scene, as user already expects the operation already exists
copy will create a new scene that's a copy

there's nothing much against user experience, in fact there's gain

**Comment by ReinerBforartists** [comment]
So can we finally agree to put the new add scene functionality into the header, besides the add collection button in Scenes mode? As initially suggested? Then we can make it a task. As told, this makes most sense to me :)


![scenes](https://user-images.githubusercontent.com/13919702/143024807-c44212ef-b8f6-4507-b887-4ab1241fcf48.jpg)

**Comment by iyadahmed** [comment]
Haha right, ok agree that's a great start

**Comment by Draise14** [comment]
Yes. Makes sense. 

I am not sure if these operators only work from active scene or from selected scene in the outliner. If they would work from selected (the one you right click on contextually) scene (like the delete operator) then it would make sense having some in the context. But if they are context agnostic and based on the "active" scene selected in the outliner then best from header.

**Comment by ReinerBforartists** [comment]
This menu should be context agnostic. It works at the highest possible hiearchy.

The mean part is, the add menu in the prop is a C menu. So we might want to recreate it in python ...

![newscenemenu](https://user-images.githubusercontent.com/13919702/143025675-f06e0bae-286c-4d8c-b014-3fcfbae4306f.jpg)

**Comment by ReinerBforartists** [comment]
Task has green light :)

**Comment by Draise14** [comment]
Request withdrawn. Better alternative that is context sensitive mentioned in #2794.

Add new to header + add copy to context sensitive menu (code ready and works, right click any scene to copy it)

**Comment by ReinerBforartists** [comment]
No it is not. 

Draise, could you please stop running amok here? Thanks.

**Comment by Draise14** [comment]
Hey there, thought maybe a little walkthrough on the UX, proposed solutions and context for the scene management feature requests in a video to explain a little of where we are coming from and why. Didn't meant to make things crazy, just trying to find UX solutions to issues that slow work and art down. 

[https://www.youtube.com/watch?v=xDzzFHl5CLM](https://www.youtube.com/watch?v=xDzzFHl5CLM)

**Comment by ReinerBforartists** [comment]
Draise i have long understood your request and the concept behind it. But you don't seem to understand the reasoning why i simply cannot accept this proposal.

First, the long mouse movement between outliner and scene prop in your video is homemade by your custom layout. In Bforartists the Scene prop is directly besides the outliner. Shortest possible mouse movement. 

![mousemovement](https://user-images.githubusercontent.com/13919702/143613405-0a221cfe-8296-4976-966b-f47097bc2399.jpg)

It isn't this much shorter with having the add button in the header. But in the header a normal user would be able discover it in the scene view. The scene prop in our toolbar is hidden by default. Which is the next poin already. Discoverability. The self explaining UI. Right click menus are hard to discover. I avoid it where ever i can. To stumble by coincidence across it is for me inacceptable.

You can add a hotkey to the menu if you want. Scenes is a power user feature anyways.

But the third and most important point is that the right click menu content when you click at a scene in the outliner belongs to the current active scene that you click at. And you simply cannot nest a scene into a scene. And this is the main reason why i cannot accept the proposal. Scene creation needs to happen at another place. This is a logical problem. And the best place for that is imho the header. 

I thought to reactivate the right click menu just for this functionality. You know that i have deactivated it since we have all its content in the regular menus already. But then we are at point two again. Self explaining UI. A right click menu is not easy to discover. An entry in the header is. 

You see, it's not that i haven't understood your reasoning, and ignore it just because i can and am in a bad mood or so. I need to decline the request since it breaks the UI concept. I have my very valid reasons to do so. I have to think about the average Bforartists user.

And  while at it, may i remind you to make always a tracker entry first before starting to develop anything? Even i do this. It is a very important rule to prevent exactly this kind of problems that we have here. Where you have already developed the feature and eagerly want to have it in the master now. And i simply have to decline it since it does not fit into the UI concept of Bforartists.

Tracker entries are important! They give us the place to discuss about features :)

**Comment by ReinerBforartists** [comment]
I knew there is a way to improve it. Make it a dropdown panel. A panel stays open as long as you are with the mouse over it. A menu closes after each click ...

**Comment by iyadahmed** [comment]
> I knew there is a way to improve it. Make it a dropdown panel. A panel stays open as long as you are with the mouse over it. A menu closes after each click ...

A context menu is better then?

**Comment by ReinerBforartists** [comment]
This has nothing to do with it. A context menu would be a menu again. Which closes immediately after one click.

And where would you want to call it? As told numerous times now, it is no good idea to call it with a right click at an existing scene. It does simply not belong there.

**Comment by iyadahmed** [comment]
Hmm ok

**Comment by iyadahmed** [comment]
But what about scene duplication, it belongs to it imo

**Comment by ReinerBforartists** [comment]
Well. So again going in circles. 

You would separate the create scene methods apart. And the duplicate methods are then not so easy to discover anymore. Scene creation does imo not belong into the context menus.

**Comment by ReinerBforartists** [comment]
EDIT, but this would indeed be the point where we could meet us in the middle. The double menu entry for the duplication methods.

**Comment by iyadahmed** [comment]
> EDIT, but this would indeed be the point where we could meet us in the middle. The double menu entry for the duplication methods. When we keep out the Create new Scene item of the rmb menu.

Agree 100%

**Comment by ReinerBforartists** [comment]
Then let's do it :)

**Comment by iyadahmed** [comment]
![image](https://user-images.githubusercontent.com/25552173/143769631-d3e4e79d-6d0e-4400-843f-85a9ca44a4f6.png)

**Comment by ReinerBforartists** [comment]
This task is done. Closing :)

**Comment by ReinerBforartists** [comment]
Not sure why this task is still open. It is long fixed. Closing.
