### ISSUE TITLE
64-bit Windows version installs to Program Files (x86)

### ISSUE THREAD

**Issue by jimbo1qaz** [Bforartists/Bforartists#28]
64-bit programs on 64-bit Windows OSes should install to Program Files.

The 64-bit download installs to Program Files (x86).

**Comment by ReinerBforartists** [comment]
Hi jimbo1qaz,

Thanks for your report. 
This is a known issue, and can already be found in our tracker. https://www.bforartists.de/content/x64bit-bfa-installs-programs-files-x86

The next Bforartists version will install into the correct folder then.

Kind regards

Reiner

**Comment by jimbo1qaz** [comment]
Anyway I think I got a crash while undoing/redoing object/edit mode. Any way to get crash logs? I can't find anything in my windows user temp folder. Maybe I didn't crash?

I'll probably stick to stock Blender for now, it isn't *quite* as unnavigable as I originally thought (Google all my issues), and the prebound shortcuts are quite quick (I could bind my own in bforartists?). I like shortcuts.

**Comment by ReinerBforartists** [comment]
Hi jimbo1qaz.

You need to start Bforartists from the console. Then you get the latest warning there. But i doubt that you will see more than an access violation there when it is really a crash. Cold crashes requires to run in debug mode. And this means you need to compile Blender/Bforartists.

To use Blender instead of Bforartists is of course your decision. But you will not escape crashes that way. It is very likely that Blender crashes in the same situations. Bforartists mainly modifies the UI. Not the core code or tools.

In case you can repeat the crash in Blender please be so kind to report it to the Blender developers. They are very likely interested to fix this.

Kind regards

Reiner

**Comment by ReinerBforartists** [comment]
Finally fixed. Thanks for the report.

Closing.
