### ISSUE TITLE
Create material error Linux Ubuntu

### ISSUE THREAD

**Issue by Svips21** [Bforartists/Bforartists#2803]
**Describe the bug**
I am trying to create new material like in your video but get error:

Python: Traceback (most recent call last):
  File "/opt/bforartists/3.0/scripts/addons/materials_library_vx/__init__.py", line 962, in invoke
    return self.execute(context)
  File "/opt/bforartists/3.0/scripts/addons/materials_library_vx/__init__.py", line 1028, in execute
    success = matlib.apply(context, True)
  File "/opt/bforartists/3.0/scripts/addons/materials_library_vx/__init__.py", line 576, in apply
    self.get_material(name, linked)
  File "/opt/bforartists/3.0/scripts/addons/materials_library_vx/__init__.py", line 502, in get_material
    with bpy.data.libraries.load(self.current_library.path, link, False) as (data_from, data_to):
TypeError: load() takes exactly 1 positional argument (3 given)

location: <unknown location>:-1

**Desktop (please complete the following information):**
 Linux, Ubuntu 16.04 Card:  GF GT 710

**Screenshots, Example Files**

**Comment by ReinerBforartists** [comment]
Hi Svips21,

Thanks for the report. Hm. Seems that this was broken in the release version since day one. And we forgot to update the release versions when we fixed the bugs in the addon. Unfunny. And sorry bout that.

We have this bug long fixed in the actual Bforartists developer version. And tomorrow comes a new Bforartists version too. So it makes no big sense to recreate a fixed version.

You can use the actual linux developer version, which can be downloaded from our download page. Just scroll down to the devbuild section: 

https://www.bforartists.de/download/

Or you wait two or three more days. We are currently at preparing the release of Bforartists version 3. And our linux maintainer promised to build the new version at sunday.

Kind regards
Reiner
