### ISSUE TITLE
Primitives:  Middle-mouse button calls function and Adjust Last Operation

### ISSUE THREAD

**Issue by slippystance** [Bforartists/Bforartists#2904]
Currently, clicking on an create-primitive icon (e.g. box, torus, ico-sphere,...etc) creates the primitve as expected.

It would be nice if that function could allow an enhancement where the primitive is created and then the Adjust Last Operation call is made.

My thinking is this enhanced function could be mapped to the middle mouse button.  So, for example, clicking on the torus icon with the middle mouse button would create the primitive and then call the Adjust Last Operation for that primitive.

This allows the original functionality to remain in place and the enhancement can be executed completely via mouse just like the normal create primitive function works.

**Comment by ReinerBforartists** [comment]
Hey slippystance,

Thanks for the suggestion. We know the problem. There is just no solution possible. When you create the primitive from the toolbar, then the adjust last operator in the 3d view is unfortunately not triggered. We have never found a way around this.

This has to do with Blender code design, where you have to use the tool in the editor for which you want to call the adjust last operator. And the toolbar is another editor. So you need two separate actions for this.

You can call the adjust last operator panel either with the already assigned hotkey F6. Or you can click at the Last Button in the right of the toolbar.

Since we cannot do anything here, closing. Sorry.

![notpossible](https://user-images.githubusercontent.com/13919702/154905362-72ddaa18-84d2-4154-83d2-ac4e74702c75.jpg)
