### ISSUE TITLE
Topbar - Missing TOPBAR_MT_file_recover

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2916]
![image](https://user-images.githubusercontent.com/35357409/156450828-a8e21d66-4456-4313-952a-33a00f71239e.png)

```
C:\3D Stuff\Devbuild\3.2\scripts\startup\bl_ui\space_toolbar.py:314
search for unknown menutype TOPBAR_MT_file_recover
uiItemM: not found TOPBAR_MT_file_recover
```

Devbuild: devbuild-26-02-2022

Mouse over the top bar to see it from the console. Not sure what's missing.

**Comment by ReinerBforartists** [comment]
Nothing missing, but something too much. The content of this menu was the two buttons called Recover last session and Recover last auto save. But we have put this content one upwards already, and removed this menu then. To remove the menu in the toolbar too simply slipped through. Good catch!

Fixed in master
