### ISSUE TITLE
File - Edit Menu - add option/information on how to copy a Blender configuration to Bforartists

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2925]
Blender Users often come try Bforartists - and they are frightened when it comes to learning something new from the same feature set. They often are a little clueless that it is possible to keep the Blender methods they know to work and still use the good stuff from Bforaritsts - when they copy the appdata from Blender to Bforartists. 

A Blender user can copy addons, hotkeys, layout and everything and use it in Bforartists almost immediately so they can start running with the good things here. It just needs to be made evident. 

So I have thought up two solutions, thanks to a user in Discord and his suggestion and feedback:

## Alternative A
We could create a custom operator that can do this:
1. Check if Blender preferences exists in USER appdata path
2. If it exists, then copy the blender USER data to Bforaritists USER after a confirm dialogue

It would use similar code to how I would copy and paste libraries from installation to USER folder. Or similar code to "import preferences" from older versions of Blender/Bforartists. This is more work though, but could also be an addon that comes in with it... not sure, but this would be more long term. It would help a large market share adapt BFA from Blender with a single click. 

**Potential location for the operator:**
![bforartists_UgEun9ejwr](https://user-images.githubusercontent.com/35357409/157974856-7c892bdd-a14d-4579-bbc6-43a144ec0796.png)

## Option B
Add a quick paragraph/text box or quicktip on the download page or website or interface to show users that they can do this if coming in from Blender. Or add a quick little chapter in the documentation to show how to do this also. Maybe also make a video tutorial for this. 

**What to show:**
1. Why you would want to copy preferences from Blender
2. Where are the user preferences stored
3. How to copy Blender preferences over
4. Explain a quick reason why using Bforartists default may be alternatively useful, nonetheless

**Comment by ReinerBforartists** [comment]
Thanks for the idea, but i am having a hard time with it.

My first reaction was: we can't do this. We are Bforartists, not Blender.
My second reaction still is: we can't do this. We are Bforartists, not Blender.
And my third reaction remains: we can't do this. We are Bforartists, not Blender.

We have already an improvement access to the appdata folder. And the best method remains the manual method. See A ...

> **A**
> We could create a custom operator that can do this:
> 
> Check if Blender preferences exists in USER appdata path
> If it exists, then copy the blender USER data to Bforaritists USER after a confirm dialogue

What about addons that already exists in the Bforartists directory? What about versioning, both, Bforartists and Blender? To tinker with paths and versions will lead to pure chaos. And once you start it you can't easily stop it. So this is imho a No No.

> **B**
> Add a quick paragraph/text box or quicktip on the download page or website or interface to show users that they can do this if coming in from Blender. Or add a quick little chapter in the documentation to show how to do this also. Maybe also make a video tutorial for this.

I will definitely not make advertisement for Blender inside Bforartists. We are Bforartists. And we should not mention or link to Blender in the UI if not necessary. We have so far one exception: the API. Since we don't host our own API.

I think i have mentioned the addons in our how to migrate from Blender to Bforartists video already though. So there is nothing really to do imho. But feel free to create an explicit video for it. I'll upload it then. Or add it to the tutorial wishlist.

**Comment by ReinerBforartists** [comment]
I will make a short text tutorial for the webpage.

**Comment by ReinerBforartists** [comment]
Fixed

https://www.bforartists.de/migrate-settings-and-addons-from-blender/
