### ISSUE TITLE
Remove Add Lightgroup from the light group sub panel in object properties - shader

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#2955]
I am biased here what to do. This whole feature is implemented in the Blender fashion to let the user hunt for the required settings. Light groups are managed elsewhere. So when you want to add the current objec to a light group, then you first have to create the light group, i have already forgotten in which tab and panel this is, and then you need to go to the object properties of the object, and add the object to the light group there.

The Blender devs have removed the little add light group button here. We still have it. But the condition is a bit odd. I don't really understand under what circumstances the button gets activated. And the curious part is anyways that the deactivated button allows you to add light groups anyways.

The curious part is that the new code should reveal a add button. But it doesn't.

So what to do here?

![addlightgroup](https://user-images.githubusercontent.com/13919702/162727308-2e44f058-70d2-4e50-8efd-61ccb79853dd.jpg)

**Comment by Draise14** [comment]
Here is the current set UX:

1. You need to create the light group as an AOV or "pass" in the Render Layers tab. There is a panel with a list there. 
2. Then when you have your custom light groups, you assign the selected objects to the correct lightgroup from the list in the Obeject Properties tab. 

Ideally it could also work inversely.
1. Create lightgroup in the Render Layers tab
2. Pick objects that are assigned to the light group with a picker that de-activates when finished directly from the 3D Viewport. 

OR 

3. List the light groups in the outliner view with "lightgroup" collections then drag and drop collections and groups into them... but that is not a feature for a top down "visually linked" UX. 

OR.

4. have the ability to create and manage light groups from the object lightgroup settings? 


Maybe the tag should be "Assign to light Group" instead of only "light group".

**Comment by ReinerBforartists** [comment]
Yeah, this is what the new code should be good for. But the create light group button never shows. Also not in Blender ...

**Comment by ReinerBforartists** [comment]
Hm, no, there is no code for this button anymore. Must have read it in another class.

**Comment by ReinerBforartists** [comment]
Task becomes obsolete by this. Closing.
