### ISSUE TITLE
3D View - Weight Paint Mode - bforartists_brush_panel addon needs better tooltip on single column

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#2982]
![image](https://user-images.githubusercontent.com/35357409/166032074-573f70af-1d39-41a2-9000-12177fb5db5b.png)

The tooltip on single column need a dynamic statement to define a different tooltip when expanded. 

Icon mode has good tooltips already, now it's just the single column mode

Most recent version is 0.0.10. Don't forget to make a branch and bunch the addon version with this commit.

**Comment by Draise14** [comment]
Hey there @iyadahmed I can't recall how to do this. Did we manage to fix this one?

**Comment by iyadahmed** [comment]
I think we didn't fix it, it is a limitation of Blender Python UI code, if you use text in a button it will do this because the operator has the same name or description

Will try to fix it maybe dynamic description will fix it
https://docs.blender.org/api/current/bpy.types.Operator.html#bpy.types.Operator.description

Sadly if the label was the issue then we can't fix

**Comment by Draise14** [comment]
Will work this for next release
