### ISSUE TITLE
Icon Sheet - A lost Icon has no name

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3008]
![inkscape_XBV6myUAoO](https://user-images.githubusercontent.com/35357409/168673026-f0d0f3be-1595-405a-b2a1-6524b08f1bb8.png)

In the icon sheet I found an icon with no name.

Task:
- Review if it's used, and see where it's used
- Rename to correct name if in use
- If not in use, remove from sheet?

**Comment by ReinerBforartists** [comment]
This is for sure in use somewhere. Something always slips through ...

Open up source\blender\editors\include\UI_icons.h, and have a look what the name of the icon is at this position.

The names in the sheet doesn't play a role, codewise. In the Blender sheet all icons are unnamed. I started this just for convenience reasons, since we have now over 1700 icons. And i was tired to count through the sheet.

**Comment by ReinerBforartists** [comment]
Hmmmm ... Smelling more than one here ^^

![g817](https://user-images.githubusercontent.com/13919702/169019246-edf6175a-a2a2-49cb-9275-d689cbdbb3c7.jpg)

**Comment by ReinerBforartists** [comment]
Yep ...
![indeed](https://user-images.githubusercontent.com/13919702/169019807-6e90cbca-3bd9-486d-8493-e6f6bd38e4e1.jpg)

**Comment by ReinerBforartists** [comment]
Okay, i'll simply fix the missing ones. Without to make any further image ...

![missing](https://user-images.githubusercontent.com/13919702/169020071-8a96a82e-573c-4900-80b7-6c40e53d65ab.jpg)

**Comment by Draise14** [comment]
Looks like there is a merge conflict, probably related to #3007

So will assign and fix the merge.

**Comment by Draise14** [comment]
Doing a test build now

**Comment by Draise14** [comment]
Success, now just letting the github action do it's checks, then will merge to master

**Comment by ReinerBforartists** [comment]
The github action will take hours to complete. That's why i usually compile it locally to test ...
