### ISSUE TITLE
Icon Sheet - Add Column numbers to names of icons

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3009]
![image](https://user-images.githubusercontent.com/35357409/168673722-6f16e280-1839-43be-b09f-3c647804c10e.png)

The icon sheet is arranged by rows and columns, and in the files repository we have sub-folders per row, PNG previews and individual files per icon. Great - helps searching in the file explorer. But sometimes cross referencing where the icon is in the SVG sheet is difficult without a column references, and searching still yields multiple results at the same time or you'd need exact name searching (know the icon pre-hand). 

This might make work a little easier in the layers view of Inkscape to list them alphabetically / OR with column numbers in names, which means some time to arrange them manually but saved time in the future. 

**Task:**
- Add numbers to names for columns

**Comment by ReinerBforartists** [comment]
I don't think that this is a good idea. You usually search by row and column number. To take care of the name order in the sheet would eat too much time for no real benefit. The names in the sheet doesn't play any role for the code and functionality.

**Comment by ReinerBforartists** [comment]
Close it? :)

You would make yourself lots of work without any real benefit ...

**Comment by Draise14** [comment]
I spent 1.5 hours looking for icons yesterday, just trying to save time. The search functions both in the object and XML editor of inkscape is not too strong... I have rows to help search for things, and the separate rows reference in the files repository - but I still get stuck on the columns searching.

**Comment by Draise14** [comment]
Maybe a better solution is adding column numbers to the icons names both in the file repository and the icon sheet? Then searching would have cross references instead of only exact name searches.

**Comment by ReinerBforartists** [comment]
Draise, why do you want to make yourself so much extra work? Where is the improvement over the current situation? 

The first and foremost question for a change is always: Where is the benefit? I personally don't see any. I see possible trouble makers ahead though. And this task becomes bigger and bigger. I see already a week of work here, easily. How much time of searching do you want to save the next ten years with this change? How often do you touch the old icons really? I add icons since six years now to the sheet. And have barely ever touched the existing icons again.

As told, you can do a name search in the xml list. You can do the name search in the UI_icons.c file, see in which row and column they are, and you have what you need. And vice versa. This is quick and simple and working. 

To bind an icon to a specific icon sheet position introduces possible sources of wrong labeling though. And gives you extra work with every new icon.

**Comment by ReinerBforartists** [comment]
> I spent 1.5 hours looking for icons yesterday, just trying to save time.

To explain the system again, we have rows and columns. In both, the UI_icons.c file, and the icon sheet. I search usually in the UI_icons.c file first. I type in the name of the icon at the top of the UI_icons.c file, have a look in which row it is, and at which position. The icons are arranged in blocks of ten. And that's it. I have my icon within half a minute usually. 

This file is in source\blender\editors\include\UI_icons.h

**Comment by Draise14** [comment]
Ah ok. Thought process was to save work for less look up time, but yeah, prepping up the way it's organized when they already are in the C file will have to be enough before the double organization becomes redundant and error prone. Sucks I have to jump between file to cross reference - but if it works, it works. 

So will close.

**Comment by ReinerBforartists** [comment]
I am glad that i was able to convince you here. You would really invest too much work for no real benefit then.
