### ISSUE TITLE
can't find getpointpeninfohistory procedure entry point in dynamic link library

### ISSUE THREAD

**Issue by jdevlearning** [Bforartists/Bforartists#3013]
**Describe the bug**
A clear and concise description of what the bug is, and how to reproduce it.

**Desktop (please complete the following information):**
The Operating system. Windows 7,  AMD RADEON R5? 

**Screenshots, Example Files**
If applicable, please add Example material. A scree
![bug](https://user-images.githubusercontent.com/9778566/169224178-78d8441b-cab0-4d71-8c3f-a35169de673f.png)
nshot, a blend file, Or even a short video.

**Comment by ReinerBforartists** [comment]
Hi jdevlearning,

Thanks for the report. But Windows 7 is not longer supported. And this since a pretty long time already. There is nothing we can do, sorry. The recommendations are simply higher nowadays. You need minimum Windows 8 for the actual Blender version, and so also for the actual Bforartists version, from what i remember. 

Blender 2.79 and Bforartists 1 was the last version that supported Windows 7. So either you downgrade to this versions. Or you upgrade your machine to Windows 10. Which should still be possible for free. A Windows 7 key is imho still valid at a Windows 10.

Kind regards
Reiner
