### ISSUE TITLE
Object mode - add shade auto smooth to toolbar and tool shelf

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3020]
New shade auto smooth operator needs entry in toolbar and tool shelf

![objmode](https://user-images.githubusercontent.com/13919702/169751991-7f531363-8a92-489a-80b4-8839f4e6b377.jpg)

**Comment by ReinerBforartists** [comment]
Don't forget to update the manual. Usually just a screenshot of the new tool in the toolbar since the tool shelf is not further documented.

**Comment by Draise14** [comment]
Yep, have that queued for this week.

**Comment by ReinerBforartists** [comment]
Queuing in your personal callendar is not good ^^

Better make a task then :)

**Comment by Draise14** [comment]
It's in the Manual projects Kanban on its GitHub repository. It's public.. Instead of tracking it with another task in the tracker. 

Should I track these project to-dos as tasks in the manual tacker instead? 

Decided to try track to-dos in the Kanban there for single commits of multiple changes - per request.  I can go back to issues maybe? Kanban tasks can convert to commitable tasks easily enough.

**Comment by ReinerBforartists** [comment]
Ah, i see. I never look into these since you cannot assign and fix them. They are no tasks really.

The problem is, i did this job in one or two days, and you spread it across the whole week. So it might be better to make single tasks. But this makes more buerocracy then. Difficult. I would say, as long as you work alone at the manual, do as you want.

**Comment by Draise14** [comment]
Documented.
