### ISSUE TITLE
Panel category warning

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3069]
`Registering panel class: 'ASSETBROWSER_PT_pose_library_usage' misses category, please update the script`
this warning shows in console when in debug mode

find out why this happens with us and not Blender
file `release/scripts/addons/pose_library/gui.py`

**Comment by ReinerBforartists** [comment]
I have no idea what is going on here. The files in question are identical. But since this just happens in a developer build i would say let's close it as a known issue. It does not harm. And investigating here costs time and energy that is better spend elsewhere.

But this is just a suggestion. I'll leave the decision open to you.

**Comment by iyadahmed** [comment]
it didn't disappear since then
something is very wrong

**Comment by iyadahmed** [comment]
I think this is related to us re-enabling tabs in tool area, because in the asset editor, the things are on left
I think this is it, a simple solution is to add a category for this panel in Python
just adding the bl_category="something" line
