### ISSUE TITLE
Texture Paint - Cursor panel greyed out

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3163]
![image](https://user-images.githubusercontent.com/35357409/181867437-396dec4b-ae0a-4b41-abe3-4b104c20df74.png)

These sliders work, but they are greyed out.

**Comment by cl3m3c7** [comment]
is it the same panel as the one in the picture?

![normal](https://user-images.githubusercontent.com/61097104/182221662-7d2a05d9-8aee-4cf2-9dbd-0e6ae2ee6082.gif)

**Comment by ReinerBforartists** [comment]
We have more than one paint mode. @Draise14 , it is always a good idea to provide big screenshots that shows the whole UI. Saves lots of work, and further asking :)

**Comment by Draise14** [comment]
I'll try reproduce again and update.

**Comment by ReinerBforartists** [comment]
Any news with reproducing this?

**Comment by ReinerBforartists** [comment]
Ah wait, now i know what you mean. The sliders and the color can of course still be modified when the cursor is off. But the changes just shows at the active cursor. 

Blender behaves the very same. So closing since this is expected Blender behaviour that you can find across the whole UI with all not active props in general. You can still modify inactive sliders ...
