### ISSUE TITLE
BFA Brush Panel - order brushes from left to right

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3202]
I noticed that the order of tools changes, dependant of how width the panel is. The tools should always have the same order.

![brushesaddon](https://user-images.githubusercontent.com/13919702/185757045-745f38a5-4cd7-417f-b3f8-9db074c3e65f.jpg)

**Comment by ReinerBforartists** [comment]
We have a double icon here too.

**Comment by Draise14** [comment]
Yeah, the draw brush and mix brush is the same brush mode and icon. So despite being two different brushes (that do the same thing) - they are.. still the "same" brush. We could remove one in the default startup. 

Concerning order, they display vertically instead of horizontally - which might be an easy fix? Will have to compare the nodeshelf method in the addon.

**Comment by Draise14** [comment]
@iyadahmed you mind taking a look at this one?

**Comment by iyadahmed** [comment]
Will do asap, currently I'm not sure why it is doing this

**Comment by iyadahmed** [comment]
Ah got it, it actually preserves order but vertically, from top to bottom, this is just how column flow works,
When space is short it will move a button from top of second column to bottom of first column

**Comment by Draise14** [comment]
Hmmm.. so to improve this would mean row flow with column counts? Is it one or the other? Or can both be considered?

**Comment by iyadahmed** [comment]
column_flow is a built in ui function,

There's no row flow, we have to write from scratch or force column flow to do something else somehow

**Comment by iyadahmed** [comment]
I am writing onw

**Comment by Draise14** [comment]
Ok.. So.. it looks alright on icon. Great. I think even better than the old version. 
![image](https://user-images.githubusercontent.com/35357409/187035934-caf8ae3e-0a69-400a-a18a-806fcafabc0a.png)

But now on text version, the list goes to a row instead of a single column. 
![image](https://user-images.githubusercontent.com/35357409/187035931-25a45500-29ba-4d44-acb9-d1fe0f7efe37.png)

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/187036857-e37d1d0f-51c5-4326-b228-d009911e929e.png)

Ok, can confirm the text version goes to 4 column instead of back to 1 column. So will re-open.

**Comment by Draise14** [comment]
![bforartists_PWazkD7O9v](https://user-images.githubusercontent.com/35357409/187040749-391197b4-b904-42cb-9c0d-18464890e584.gif)

Looking good!
