### ISSUE TITLE
Trouble with the Asset Management addon from Pitiwazou

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3208]
I have a user report, or better said, indirect one from the developer, that the Asset Management addon from Pitiwazou makes trouble in Bforartists.

https://blendermarket.com/products/asset-management

Does somebody have this addon, and can confirm the trouble that is described here?

Pitiwazou also mentions a very long loading time compared to Blender, which i can definitely not verify. Blender needs roughly as long as BFA here with a blank restart. Slow loading and slow reaction could point towards the console, getting flooded with errors. But Pitiwazou did not mention anything like that.

![7079_bforartist](https://user-images.githubusercontent.com/13919702/186204125-5f45379c-44f8-4cd0-9d1e-c71f07f90d47.jpg)

**Comment by Draise14** [comment]
Load times will depend heavily on how many addons you have activated on the startup settings. If he's not on vanilla installation, then yes, it might take longer. Mine takes a while cause I load over 50 addons. 

Maybe we need console readout to really know what's up here to support. I don't have access to this addon either... Tell him to load Bforartists from command line. 

A good rule of thumb when troublshoeeting is that many addons take a while to update source to 3.3, and most don't stay up to date with the master builds of Blender (though they should, like we do). If the addon developer is not supporting 3.3 or 3.4, or doesn't do development for Master, and it doesn't work in the Daily builds of Blender, then it may break with the latest version of Bforartists too. Test there first before ruling Bforartists out.. but I'm sure you know this... 

**Random guess:**
The other issue that might slow things down is that PIP may need to be manually updated, but I haven't seen that really hurt performance. That would say in the console. 

**Random guess 2:**
Missing icon flooding the console would slow things down. Some addons use icon indices and/or names of custom icons that might be in blender or not. Occassionally this has happened which is an easy fix and I usually report these.. which is rare. But maybe with the latest there is something different. 

**Another.. shoot in the dark:** 
Another possible issue is maybe the addon is calling for the blender installation path to run from the system environment variables, instead of the SYSTEM or LOCAL path of the renderer of a thumbnail (would only work on installation versions of Blender). This is an issue in the addon code - and if it's calling for the renderer to run in background, it should load it up from the LOCAL or SYSTEM path variables and technically should work with Bforartists too, unless it's specifically calling for the blender.exe for a command line render or something like that.. Most addons I know don't have this issue, but I can see how this might be an issue if path names are not relative or name dependent. 

**Another random guess 3:**
I have found some addons not update context since 2.9 to 3.0 builds has a context api that's necessary to use some things. If the addon hasn't been updated to latest versions of Blender, then this will be an issue. But it is an easy fix - but that will come with the addon maintainer. This bug would be reproducible in Blender dailies.
