### ISSUE TITLE
Compiler warning: code on left of comma has no effect

### ISSUE THREAD

**Issue by iyadahmed** [Bforartists/Bforartists#3232]
```
/home/iyad/projects/bforartists-git/Bforartists/source/blender/editors/screen/area_utils.c: In function ‘ED_region_generic_tools_region_snap_size’:
/home/iyad/projects/bforartists-git/Bforartists/source/blender/editors/screen/area_utils.c:50:70: warning: left-hand operand of comma expression has no effect [-Wunused-value]
   50 |     if (RGN_ALIGN_ENUM_FROM_MASK(region->alignment) != RGN_ALIGN_LEFT, RGN_ALIGN_RIGHT) {
```

CC: @Blenux what was the intended effect here?, because currently this is the same as

`if (RGN_ALIGN_RIGHT)` which is very wrong

**Comment by Blenux** [comment]
Should it be RGN_ALIGN_LEFT + RGN_ALIGN_RIGHT?

Added it because of this,

Without
![without_Rgn_Align_Left](https://user-images.githubusercontent.com/25260650/189815905-2533bf26-0940-4b51-906d-4230adf9390c.png)

With
![with_Rgn_Align_Left](https://user-images.githubusercontent.com/25260650/189815950-5ef7bc5c-bc05-4aa7-874b-8056f61f863e.png)
