### ISSUE TITLE
CMakeList.txt is bugging on Windows - no-longer able to compile master or 3.3.0 branch

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3233]
![powershell_v8C9NInnx1](https://user-images.githubusercontent.com/35357409/190199155-47e94807-03e8-4745-9c50-f597ae767e8f.png)

There is a "bforartists-launcher" issue - but when I dug deeper... the Cmakelist file is very different from previous versions. 

![Code_qC3ly2BKXP](https://user-images.githubusercontent.com/35357409/190199300-ef111fdb-efe9-4b05-9671-33867149130a.png)

At the moment I can't build Bforartists successfully, and @Blenux has also confirmed he can't build also. 

I am assuming many paths and things are broken from the rebasing to fix the other bug. @iyadahmed could you take a look at this one?

**Comment by ReinerBforartists** [comment]
Blender changes gives us really a hard time with the current release :D

**Comment by Draise14** [comment]
![explorer_nXNhEXObZq](https://user-images.githubusercontent.com/35357409/190253042-9c4f68d3-d9af-47b0-bde4-697a7903b1b0.png)

When commenting out "bforartists-launcher"... I get these errors.

**Comment by ReinerBforartists** [comment]
It's not as easy as commenting out the trouble terms. We have replaced the term blender-launcher by bforartists launcher at one point. So when you comment it out then a vital part is missing then.

This kind of big changes that you see here happens usually shortly before or shortly after a Blender release. That's why i am always keen to make a Bforartists release as fast as possible when Blender makes a release ...

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/190482641-d221c931-d31e-4484-a151-04b5bab628fd.png)

Eureka... its was my fevers... 4 days of high fever really was getting to me. I did another pull and viola, it compiles again. Closing.

Got my next antibiotic injection today and we know what it is, I should be able to do SOMETHING next week....

**Comment by ReinerBforartists** [comment]
I wish you the very best!
