### ISSUE TITLE
Bforartists file crashes blender when trying to switch workspace.

### ISSUE THREAD

**Issue by FredRus** [Bforartists/Bforartists#3357]
**Describe the bug**
I was trying to open a file I made in Bforartists. When trying to open with Blender, the file starts, but when trying to switch to the node workspace, it immediately crashes Blender. I am using Bforartists version 3.4.0 and tried to open in blender version 3.4.0. I encounter warnings saying something like "file was written in a newer blender binary, expect crashing a loss of data" when opening file in older version of Bforartists. Worse when trying to open files with some nodes; Blender doesn't even start at all.

**Desktop**
My operating system is Windows10, and I don't use any graphics card

**Screenshots, Example Files**
With a simple mouse model I made, switching the workspace crashed blender. I trimmed some of the start-up to get straight to the point as fast as possible.

https://user-images.githubusercontent.com/120553860/209251384-b0270731-22a0-48cd-9115-ea4733921b8c.mp4

(Sorry for the low res and watermark)

**Comment by Draise14** [comment]
To fix this, load the Blend with Load UI turned off. This can be done from the file browser, or the Save/Load preferences to turn off permanently. 

This is a known issue, and turning off Load UI in Blender fixes this.

**Comment by ReinerBforartists** [comment]
I can just second what Draise already said. Blender is under the hood made in a way that does not allow to add other editors besides the official Blender editors. Blend files can become incompatible in the layouts then. And we have added one more editor type. Our toolbar editor. And this can make trouble then since Blender then has to deal with one more editor that he does not know.

It's not the content that is affected though, it's just the layout. So workaround is to load the file without UI and save it. And you should be fine to go again.

I would in general suggest to turn off Load UI in the Blender preferences. I would go crazy when i would always have ot work with another UI, dependant of which file i use ...
