### ISSUE TITLE
Hotkey - 3D View - Set 3D Cursor can't drag, but in Blender you can

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3423]
![bforartists_jk03bcMPTq](https://user-images.githubusercontent.com/35357409/221384915-345d2cf4-6053-4ff3-ac83-6cb2f1d29f8b.gif)

Right now the `ALT+RMB` places the cursor, but you can't drag it. In Blender the equivalent `SHIFT+RMB` places and when you hold it, it also drags it. Something under the hood must be different though it's the same operator.

**Comment by Draise14** [comment]
Had a closer look at the Blender key map. They have alot of other stuff, new systems. You can't even export the hotkeys without a corrupt file because their hotkeymap is two files.... This means you are effed to replicate their functionality 1 for 1 with the hotkey editor. 

With this particular operator, the functionality has extra tweak conditionals that help it work like the modal operator.. a corrective code IN the key map files... Fubar

**Comment by ReinerBforartists** [comment]
Hm? Here nothing is corrupted. The Blender keymap is just pretty empty when you export it since it uses all the defaults.

**Comment by Draise14** [comment]
Ah right, so every hotkey map is essentially.. an override. So the set 3d cursor hotkey override will break the default functionality?

**Comment by ReinerBforartists** [comment]
I have no idea what the problem is, sorry. We most probably run into the custom keymap issue here.

The concept is that you have one default file, and a keymap that might differ from this default. This is the current blender design. A config for a config. And our keymap is based at the blender_default.py

There was a task to write a bforartists default file too. But i had to give up at it. It was simply not doable. And yes, this concept is crazy. And fubar. But we have to live with it. And this means that this task might not be achievable.

**Comment by Blenux** [comment]
![bforartists_zKPeUqvjJo](https://user-images.githubusercontent.com/25260650/222937675-3bb303f0-8522-4428-b6bd-61d77c0f0187.gif)

**Comment by Draise14** [comment]
Wait... You solved it. I had no idea this was an option.

**Comment by ReinerBforartists** [comment]
Please assign and fix :)

**Comment by Draise14** [comment]
Will merge after next weekly merge.
