### ISSUE TITLE
Hotkeys - Add select linked CTRL+L like in Blender

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#3467]
Draise had the wish to add select linked hotkey everywhere. I'm honestly a bit unhappy with it. Goal of BFA keymap is to have as few default hotkeys as possible so that users can customize the keymap.

But we can at least talk about. And it's not this much hotkeys.

![linked](https://user-images.githubusercontent.com/13919702/227731879-e13d03c5-4aa9-49d7-8505-939ecfec3688.jpg)

**Comment by Draise14** [comment]
I have this with my personal default. I haven't found any conflicts as of yet.

**Comment by ReinerBforartists** [comment]
As told, i am a bit biased here. For consistency reasons we should. For BFA design rules we should not.

Do as ever you wish :)

**Comment by Draise14** [comment]
I think.. seeing what I found I could do with the select linked in the image editor in the #3204 task, maybe we can add this floating panel button to the GUI on all sub-menus so you can quickly "right click and assign hotkey" to any floating menu a user may want to use then we wouldn't need to assign any hotkeys - leave it up to the user. 

Alternatively, though we are minimal by design in hotkeys per default, sometimes customizing this keymap is going to the hotkey manager, finding the editor section, the mode, then adding, then finding the call menu operator, then guessing the floating panel name directly from the Python code.
