### ISSUE TITLE
Bug - Missing CURVES icon

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3576]
![WindowsTerminal_eqVg3mXfn6](https://github.com/Bforartists/Bforartists/assets/35357409/6d6d57c8-a5e8-4516-90f5-e7c372cb6a35)
Looks like an addon found an icon we don't have that Blender does, the CURVES icon.

**Comment by ReinerBforartists** [comment]
Interesting catch.

**Comment by ReinerBforartists** [comment]
Ah, Blender devs have at one point thrown out the hair icon, and replaced it by a curves icon. Which was nonsense, since it is not a curve icon, but a hair icon, in look and in functionality. It has nothing to do with the bezier curves besides that it is used for hairs. And so we kept the hair icon. And pay a price now ...

Question is if we rename our hair icon to curves icon, or if we add a additional curves icon with the look of the hair icon. The one in the c files was easy to catch. I just have no idea where we use the hair icon in the python files, there it is not so easy to catch.

source\blender\makesrna\intern\rna_material.c is one place where we have the old hair icon. 

![hair](https://github.com/Bforartists/Bforartists/assets/13919702/4687953c-b9f2-4e47-944c-f36bcffa0904)

**Comment by ReinerBforartists** [comment]
Toolshelf has the hair icon four times. And space_view3d one time.

Now let's check if Blender has a hair icon so that we don't run into a conflict here.

![hair2](https://github.com/Bforartists/Bforartists/assets/13919702/d5c425dd-a886-431e-afa5-7c5742a4c9cc)
![icon](https://github.com/Bforartists/Bforartists/assets/13919702/9fea6af2-fd13-4b04-91f9-47ec1f70b382)

**Comment by ReinerBforartists** [comment]
Narp, no Hair icon. I vote to rename our icon then.

**Comment by ReinerBforartists** [comment]
I should have catched them all. Fingers crossed.
