### ISSUE TITLE
3D View - Make Subdivisions operators update Render Subdivisions, instead of only viewport

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3645]
![bforartists_uwXED3q6yb](https://github.com/Bforartists/Bforartists/assets/35357409/611b5ec1-ff6a-48e1-8cbe-3cf973d9131a)

Right now when you use the Subdivide operators on a mesh in object mode, CTRL+1-9, then the viewport subdivisions update, but not the render subdivisions. A user reported this has ruined good renders often. I wonder why when CTRL+1 and CTRL+2 does update render subdivision, but not the others... seems broken. Might be worth taking a look into it. 

These are the operators. 
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f1e24889-19bb-48aa-8783-d51cfa7b78ec)

**Comment by ReinerBforartists** [comment]
Well, the hotkeys are not for the render resolution, but the viewport resolution. That's the same in Blender. 

I think this feature request is best done at Rightclickselect and for Blender. Since i don't even see a way to do so. It's two different operators. And this means we would need to use other hotkeys. Since the same hotkeys would simply override each other. It is not possible to use the same hotkey for two operators.

What we could do is to add our own operator that performs both operations simultaneously. But then we would have another fraction moan why we can't have a lower sds setting for the viewport like in Blender.

![levels](https://github.com/Bforartists/Bforartists/assets/13919702/4eafe41e-7fd7-4353-a3f4-1d16d6b6887e)

**Comment by Draise14** [comment]
Hm... yeah might need to be reported upstream.

My counter argument is this though: **WYSIWYG** is a better UX. If you want less SDS levels from render in viewport to optimize, then you can set that in the Simplify panel per scene in the render settings or optimize the viewport SDS objects when needed - as opt-in. 

**Use Case Stories:**
When you model, you want what you set with the hotkey ready for render to post to socials or to share with peers - so that what you have in viewport as the final result for a final render, these days most hardware can handle it so if I really want to optimize. YouI would be using Simplify settings or intentionally optimizing it after setting the fact, or noticing a performance hit and optimizing. De-linking render from viewport should be opt-out, not opt-in. 

You have a performant viewport, simplify is off. Everything looks ok. Your scene is filled with hundreds of meshes. But on render, your tri count is going up, ram is hitting a cieling. You're not sure why. You can't cap simplify on everything, you need a few with higher render SDS's than others - but now you have to comb through 100s of objects you applied the SDS to to find the meshes that would optimize the scene with the correct render levels. Or vice versa, you hit render and the quality is not he same as the viewport. There are also cases where you had no idea your render SDS was too high or low since in viewport it was dis-connect , and thus extends render times and/or scene preparation for consistency.  

Another example is when speed running block-out or layout, you quickly set different SDS levels on the meshes, but at the end of the day to show your supervisor the work - you have to set the render setting one by one even though you blocked out dozens of objects with SDS modifiers in a matter of minutes. You resort to a screen capture. Not all of them have the same level of SDS so using `ALT `to apply the same render settings to all selected is no-longer applicable - getting to a render level then becomes tedious as you have to go through dozens of objects you added in a matter of minutes before you can do a final render to review... 

Another use case, you created a character, it's looking good in viewport, you animate it, then render overnight. Then you find out you forgot to update the render setting to the right levels in the the SDS modifier, since you thought it was fine. This is yet another render checklist to wrangle to avoid wasted renders, which is not a fun UX and shouldn't be a requirement before hitting the render sequence button. _This has happened to me.. often, and to the user who has reported this request - a creative director or Reddit himself!_ 


**Alternative solutions:**
- Create a new operator to "Match SDS with Render" or "Match SDS with Viewport" in my Match Render visibility addon, include it in Bforartists?

With 240 pull requests and 5500 open issues in Blender, yeah, this new operator won't come in years.

**Comment by ReinerBforartists** [comment]
I didn't think about if Blender has the capacity to do so. I thought about the UX design. I am with Blender here.

It can and will also work the other way around. You model, change the resolution while modeling, and whoosh, in the render result you have the wrong sds resolution. And then you have the same complaint, just the other way around. Hey, i just modeled, why does the final setting change? That's why i think we should keep them separated under all circumstances. I am more than fine with the current system. And we have more than just SDS where we have render settings and final settings.

I don't see any useful UX that could speed things really up. Every "solution" just adds yet another layer of complexity and introduces more trouble.

A match sds addon makes imo not much sense therefore, it is such a new layer of complexity. Whoah, this exists? Is it on? Is it off? Hey, i just modeled, why has the final sds setting changed ...

**Comment by ReinerBforartists** [comment]
> What we could do is to add our own operator that performs both operations simultaneously.

As told, i see this as a possible solution. Then let the user decide which operators he wants to use.

**Comment by Draise14** [comment]
Opt-in, I like the sounds of that.

**Comment by Draise14** [comment]
For 4.1

**Comment by Draise14** [comment]
One for the Power User Tools addon.

**Comment by Blenux** [comment]
How about this?

https://github.com/user-attachments/assets/1e7500f0-7b89-4db7-b409-d7cc13e67cd8

**Comment by esnosy** [comment]
It is better in my opinion to modify the existing operator, I'm 100% sure the change is easy
@Blenux

**Comment by Draise14** [comment]
Good work. The label may need work but the UX is fine. 

As Reiner pointed out, an opt in or out has its use cases. So modifying the base operator is a no go.

**Comment by Blenux** [comment]
Yeah I read all the earlier comments, and yeah what label should we use?

**Comment by Draise14** [comment]
"Combine Viewport/Render Subdivision Levels operators"

5 to 7 words
Changed to "active action" to toggle into

**Comment by Blenux** [comment]
Hows this?

![image](https://github.com/user-attachments/assets/35bdaf3a-eb08-4247-ae27-3201ad995ebc)

**Comment by Draise14** [comment]
Perfect, let's go!

**Comment by Blenux** [comment]
Small issue, the user will need to restart bforartists on diabling the addon custom operator to re-enable the original subdivision operator in object.py, can't seem to find a work around :(

**Comment by Draise14** [comment]
Force reload scripts operator when toggling off? This reloads all GUI scripts. 

![image](https://github.com/user-attachments/assets/2c47a08f-c577-4b30-810a-0a4fed9e7a18)

**Comment by Blenux** [comment]
Was thinking that, but not sure if it was appropriate to use.

**Comment by Blenux** [comment]
Found another way, much cleaner, though does mean adding in a few lines of code into the SubdivisionSet operator in the object.py if that is ok?

**Comment by Blenux** [comment]
Finding the power user tools addon code a bit wonky, put it in the user settings addon and works fine, now trying to put put back in power user tool.

(omg brain is just nope today)
