### ISSUE TITLE
3D View - Weight Paint mode - Exposed Legacy operators should be consistently organized

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3668]
![image](https://github.com/Bforartists/Manual/assets/35357409/e485aa65-d89e-4c9e-96e1-71a99ac90312)

Blender exposed these operators to GUI. I had no idea they existed, but they are redundant ones since they exist in the toolbar, ei.. they are Legacy. We have repeat operators exposed in GUI under a legacy folder, so let's do it for these four too.

They may also need iconography and documentation.

**Comment by ReinerBforartists** [comment]
Needs icons too then.

**Comment by ReinerBforartists** [comment]
This menu is something very odd. It has a second def draw at the end. And when i remove this second draw then BFA errors out at places that has absolutely nothing to do with this menu.

And because of this very special draw class i was also not able to create a working legacy menu so far. Hm.

Either way, at least we have icons now.

![erroringout](https://github.com/Bforartists/Bforartists/assets/13919702/b51ac82e-dd69-4a18-82a7-3c9176601132)

![LEGACY](https://github.com/Bforartists/Bforartists/assets/13919702/67fc183c-8022-436c-8035-9e76d9119908)

**Comment by ReinerBforartists** [comment]
Updating the manual ...

**Comment by ReinerBforartists** [comment]
Whoopsie, forgot to uncomment the def draw again.

**Comment by ReinerBforartists** [comment]
Hm, the manual is everything but up to date. Must be a shot and the info from Blender 2.8 times. May i remind to always update the manual too when finishing a task?

**Comment by ReinerBforartists** [comment]
Manual is updated. Legacy menu is something for after the 3.6.1 release then.

**Comment by ReinerBforartists** [comment]
Second try ...

**Comment by ReinerBforartists** [comment]
Seems that i simply had the dumb yesterday. Now it works.

![working](https://github.com/Bforartists/Bforartists/assets/13919702/5af9e6da-cf34-475d-a4fa-1f336b8f8bdb)
