### ISSUE TITLE
Dopesheet/Graph Editor - Regression - Toggle editor in view menu is redundant

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#3791]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/550f8f6a-1985-406e-8906-ff12156ac2f7)

Accidentally added these back in the merge, will remove again. These are not necessary, though it is a hidden operator in a hotkey in Blender. 

Beware, some code for the toggle is in the Fcurve editor too.

**Comment by ReinerBforartists** [comment]
This task is invalid.

The entries might look redundant at the first look. But we promised to deliver the same functionality than Blender. This entry shows that this functionality exists, and this entry can be hotkeyed to switch between dope sheet and graph editor quickly. That's why we once decided to add it to the menus at all. In Blender it is a hotkey only tool. And so this tool has in fact a hotkey.

![asfd](https://github.com/Bforartists/Bforartists/assets/13919702/7c5c43d9-1b9a-43e5-b674-3b4bdd47cfcf)
