### ISSUE TITLE
In Edit mode, if we switch to Vertex mode, the Bevel tool also should switch to vertex mode automatically 

### ISSUE THREAD

**Issue by raindropsfromsky** [Bforartists/Bforartists#3857]
**Is your feature request related to a problem? Please describe.**
1. Switch to Edit mode > Vertex mode.
 2. Select a vertex on an object
 3. Press CTRL+B to launch the Bevel tool.
 4. Drag. Nothing happens.
     We cannot see the extent of beveling while we drag the mouse.
 5. Click. Apparently we finished the bevel operation, but still no result is visible.
 6. We have to click on the operator panel and switch the Bevel tool's mode to vertex mode explicitly.
 7. We have to adjust the extent of beveling only by adjusting the parameters in the operator panel.
     That means that in the vertex mode, we can't bevel visually at all!
     
Compared to this, the beveling is straightforward in Edge mode: You can see the live effect as you drag the mouse.
This inconsistency between the vertex mode and edge mode is confusing!

**Describe the solution you'd like**
In Edit mode, as soon as we switch between the vertex/edge/face modes, the Bevel tool should automatically switch to the same mode. In other words, B4A should show the live effect of beveling as we drag the mouse.

**Describe alternatives you've considered**

**Additional context**

**Comment by ReinerBforartists** [comment]
Hey raindropsfromsky,
Thanks for the idea. But this is unfortunately nothing that we can fix at our end. This is best reported to Blender directly since it is a bug in the Blender design. Or better said a flaw. And i am not sure if they will even fix it. Initially the Bevel tool was made to smooth edges, not vertices. And the workaround for this special case with having just one vertice selected is to switch to Affect Vertices in the adjust last operator panel. But the report might be worth a s hot.
Kind regards
Reiner
