### ISSUE TITLE
Addon - Plasticity Blender Link Addon is not working on BFA 4.0.2 Apple Silicon Version

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#4024]
Digimooses has reported that the Blender Link Addon does not work with Bforartists, but does with Blender.

See here: https://www.bforartists.de/forums/topic/plasticity-blender-link-addon-is-not-working-on-bfa-4-0-2-apple-silicon-version/

Addon installs and activates fine, so not sure if we can help at all.

**Comment by Draise14** [comment]
Since this is a paid software and addon, there isn't much we can do. If anything, you should probably contact the developer of plasticity at their github directly and report there. You will have to join their server if you have paid, then report there.

https://github.com/nkallen/plasticity

I assume the addon may be looking for the blender.exe but we is a bforartists.exe - or you may need to configure the addon, or see if the console is spamming some kind of error. I don't have a purchase of the software thus no access to the addon nor access to the discord server to report or work with the dev, so will leave this as a known issue.

**Comment by ReinerBforartists** [comment]
I will close this task now since there is no way to resolve it at our end.
