### ISSUE TITLE
Info: Registering menu class: 'ALL_MT_editormenu', bl_idname 'ALL_MT_editormenu' has been registered before, unregistering previous

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4045]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/4438b46a-7e98-4928-8b89-bd02f924b23b)

Console issue spanning from our `ALL_MT_editormenu` system. Might be new warning code in there and we had it wrong a while.

**Comment by Draise14** [comment]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/b341b5d1-b227-4f36-94cb-f256739d529d)

I think it is because every document is registering the same class 15 times more in 15 additional documents. They must have added a new checker system, or maybe we can reference the same class from somewhere common and remove the multiple registries from other documents?

**Comment by Draise14** [comment]
Did a quick test, removed one of the registries in a document, it removed the warning - no broken changes.

**Comment by ReinerBforartists** [comment]
Be careful with this one. I once needed to add the class to every editor to get it working. It is the show hide editor type menu

**Comment by Draise14** [comment]
The clip editor I tested on appeard to continue to work, so will.. branch and test before merging to master if I do manage a fix.

**Comment by ReinerBforartists** [comment]
This is what happens when you remove the class from one file. I did this here in the console editor.

Well, it worked for eight years or so to have the same class in the different files. Long enough i guess. Interesting would be to know the commit that made our previous working method uselsess. But we need a solution.

What we can do is to make every class unique now. The one for the console becomes then ALL_MT_editormenu_console, the one from the 3d view ALL_MT_editormenu_3dview, and so on. Then the error should vanish.

![removing](https://github.com/Bforartists/Bforartists/assets/13919702/445800e3-fd8e-439f-91a5-a384c7d77377)

**Comment by Blenux** [comment]
Changes were made here, has above best to just add a editor suffix in each own file.

[116374](https://projects.blender.org/blender/blender/pulls/116374)

[116370](https://projects.blender.org/blender/blender/issues/116370)

**Comment by ReinerBforartists** [comment]
So when two addon developers chooses the same class name the console will be spammed with error messages now, and slow down Blender? This change is crazy ...
