### ISSUE TITLE
Preferences - Double Save Preferences operators

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4266]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/f001ad44-abe5-425c-8d50-a5734b580f4f)

One was move up a level, which I like, but now it's double. Could add the icon to one, then remove the other. it conveniently shows there are unsaved changes.

**Comment by ReinerBforartists** [comment]
This was a customization from us ...

**Comment by ReinerBforartists** [comment]
Um, there is no double. This task is invalid. The button does not exist yet. Was this a customization at your end?

It is usually not longer needed to save preferences manually since every little change automatically saves the preferences. So i don't know if we should even put the button top level UI. It is visual noise for 99.99 % of all cases.

![nope](https://github.com/Bforartists/Bforartists/assets/13919702/bd22103e-cf30-4744-8d68-f479455f8291)

**Comment by ReinerBforartists** [comment]
I will close this issue.
