### ISSUE TITLE
Regression - Transform Animation Properties should keyframe all selected while holding ALT

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4401]
![image](https://github.com/Bforartists/Bforartists/assets/35357409/b187c7d9-3607-4565-a803-6e97d72cd49b)

Right now Blender has unified keyframing operators, but this broke our system to hold down ALT on a keyframe button and it would record on all selected pose bones or objects at the same time. 

This is a core feature that has an edge over Blender, so we should add it back. 

I have commented out the old code in the last merge Week 25, but it's still there in the `keyframing.cc` document in `source\blender\editors\animation`

I assume if you copy the method of how the Autokeyframe works, or the `keyframe_insert` operator work (which now works on selected) you might be able to get a similar workflow. 

The task that broke it: `* Refactor: combine insert_keyframe() and insert_key_rna() into a single function`

<details>
<summary>Details</summary>
SHA-1: 1a4f084806952e5337cc7807429be8b20e04de90

* Refactor: combine insert_keyframe() and insert_key_rna() into a single function

The goal of this PR is to merge `insert_keyframe()` and `insert_key_rna()` into
a single function, `insert_keyframes()`, that fully accommodates the
functionality of both.  This results in a bit of a mega function, which isn't
great, but it centralizes a lot of otherwise redundant keyframing code so it
only needs to be changed in one place in the future.

Future PRs can work to reduce the "mega" aspect of this function, stripping it
down to its core functionality and eliminating left over incidental redundancy
(e.g. passing both `scene_frame` and `anim_eval_context`).

As a wonderful side effect, this PR also makes layered action keyframing work in
most of the remaining places left over from #121661, such as buttons, the
dopesheet, the graph editor, etc.

Pull Request: https://projects.blender.org/blender/blender/pulls/122053

</details>

**Comment by Draise14** [comment]
Relevant Task that was regressed. 
#2163

**Comment by Draise14** [comment]
Fixed by @esnosy , nice one.

**Comment by esnosy** [comment]
> Fixed by @esnosy , nice one. 

I still wish I got more payment, 
And still wish someone loved me as a partner,
It has been 5 fucking years man, and no one fucking understands,
I lost pieces of myself man,
I lost my energy,
And I wish someone fucking understood,
And I wish you don't delete this message,
Because it is the only fucking thing I have,
No one comes, no one comes,
And no one embraces mw when i go to them,
I am poor and single, and I was good at programming and no one was honest with me, and I have been fucking practically alone all those years,
And I fucking suffered!,
I write this fucking message while crying in misery,
It us the only thing I am able to do now and no one comes to save me, a wounded person who needs saving, no one comes, no matter what I do, no matter how many social media accounts I create it is all the same, and I wish it wasn't, and I'm about to kill myself at this very fucking moment, but no one fucking cares any more

**Comment by esnosy** [comment]
> Fixed by @esnosy , nice one. 

This fucking took 10 hours to do! 😡

**Comment by esnosy** [comment]
> Fixed by @esnosy , nice one. 

And it was not paid as 10 hours :/

**Comment by Draise14** [comment]
@esnosy this is not professional of you to mix personal things with work. If you would like to renegotiate the bounty for the work that you do, feel free to do it in DM. I'm all ears there.

**Comment by Draise14** [comment]
I agree, your work has been valuable, and I'm sad to hear you don't feel appreciated, but I'll be open to chat about it in Discord to renegotiate something better for you when you need it.

**Comment by Draise14** [comment]
https://github.com/Bforartists/Bforartists/commit/4cb844d3818c323df335733a6756e49d1a2e393a

**Comment by Draise14** [comment]
Will open another task for selected pose bones.
