### ISSUE TITLE
User Interface - Adjust Icons

### ISSUE THREAD

**Issue by Blenux** [Bforartists/Bforartists#4513]
Notice that some of the icons need some updating after the new icon format, (small, not centred, pixelated etc), icons that were adjusted are, 

disclosure_tri_down
disclosure_tri_right
group_bright
group
view_ortho

Some others still need some changes, but these were the most noticeable.

![icons](https://github.com/user-attachments/assets/53490394-f4a5-42d8-8a17-e19b062a628e)

**Comment by Draise14** [comment]
Group icons had to be redesigned since the entire draw system changed. So those stay. Though alignment could be improved. 

Disclosure icon is now the same size and shape as the other ones, more consistent. (Compare with collapsed menus of the properties editor)

The view gizmos should be in color (black outline) so those could be reviewed. Otherwise removing the lineart might fix it. Was an attempt to make those consistent with the camera icon.

**Comment by Draise14** [comment]
Will open another ask for view gizmo in color consistency.
