### ISSUE TITLE
Keymap: Can't drag a node without clicking on it at first

### ISSUE THREAD

**Issue by hitkeydel** [Bforartists/Bforartists#4612]
**Describe the bug**
Can't drag a node without clicking on ot at first, the previous selection will work instead. This strange behaviour can be reproduced if you use BFA and blender( left click select) keymaps.

**Desktop (please complete the following information):**
win 10, bfa 4.2.2

**Screenshots, Example Files**
attached a file.
[bfa422.zip](https://github.com/user-attachments/files/16801090/bfa422.zip)

**Comment by ReinerBforartists** [comment]
Hi hitkeydel,

Thanks for the report. I can unfortunately not reproduce what you describe here. Works just fine, i can drag the nodes around without an extra click. Could you please be so kind to remove the appdata content? It can be that old Bforartists settings makes fun here.

Kind regards Reiner

**Comment by Draise14** [comment]
Yeah, double tested, removed the app data, and default is identical to previous versions. 
![bforartists_XXzgZn3TNn](https://github.com/user-attachments/assets/4fb12afa-ebc8-40f3-81bc-a9544261fc2c)

**Comment by Draise14** [comment]
But the file is broken for some reason...

**Comment by Draise14** [comment]
Ah, your scene is using tweak in the node editor, not box select. 
https://github.com/user-attachments/assets/adcca657-3735-4de4-b411-fdf38d6e5ce0

**Comment by Draise14** [comment]
Dug deeper, the box select has a "tweak" setting, but the select and move operators are two seperate. If we change select to press, it will deselect everytime you click on something, meaning you can't move groups (breaks). Click drag also is used to move nodes, but it has no setting to select under the click - so it is "intended by design" or flaw.. where box has tweak, and tweak is like box, but with select first. 

So, press B or select box mode in the file and you'll get previous working method of using tweak and box select on nodes.
