### ISSUE TITLE
Asset Shelf - Add view pre-set sizes for thumbnails

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#4670]
![bforartists_xPrRK7CIPf](https://github.com/user-attachments/assets/de40bc8c-be35-4d1e-af84-e59f21b123bc)

Part of the asset shelf workflow requires a round trip to the asset browser to change settings, so the UX is limiting or disconnect. We should add the asset browser options to the header of the asset shelves. 

# Task
- Add view pre-set sizes for thumbnails like in the file browser and asset browser. 
![image](https://github.com/user-attachments/assets/d351617f-99a1-4ac2-8990-1db4aeb03246)

**Comment by Quackarooni** [comment]
Did a bit of looking into this, there's a bit of a hangup, since it seems like `AssetShelf` doesn't have a preset thumbnail size property like `FileSelectParams` does, it only has the integer property. For context, `FileSelectParams` is what is used by both the Asset & File Browser.

| Asset Shelf | Asset & File Browser |
|---|---|
|![image](https://github.com/user-attachments/assets/aa33dbbd-074a-4dbe-827e-5a5b2b16cad5)| ![image](https://github.com/user-attachments/assets/d7df8a6b-a5cb-4793-879d-fd47eaaa1a3a)|

**Comment by Quackarooni** [comment]
Was actually just gonna ask if I could do that, lol. 

Since altering the `AssetShelf` struct in the C++ code itself, is way outside my wheelhouse. But handling that stuff with buttons that just automatically update the integer value under the hood is something I think I can handle.

**Comment by Draise14** [comment]
Yeah, UX is the end game, no worries bout the backend. Python with existing API is easier to maintain anyway.

**Comment by Draise14** [comment]
Will be documented with the new asset shelf chapter I think.
