### ISSUE TITLE
Freezed while running of modelling productivity.

### ISSUE THREAD

**Issue by foliagetree23** [Bforartists/Bforartists#4861]
**Describe the bug**
Im just a beginner and artist for this software, software become freeze and we just need to close it for more modelling activity once. I have to use this software because it's simple, easy navigation, more user friendly. I had use that for a while a long of time since i moving to Linux but Windows also become crash but Linux is much there's i use another version.

For Linux first time i use latest and i found such that (Freeze) so i moving to more to less that version until 2.9.3 Okay that's okay no other freeze. but now i found that again, i don't know what trouble is.

**Desktop (please complete the following information):**
Linux Mint 21.3 Cinnamon, Intel Corporation HD Graphics 620 (Default manufacture), Intel© Core™ i5-7300U CPU @ 2.60GHz × 2, X11, RAM 8GB.

**Screenshots, Example Files**
![Screenshot from 2024-12-27 13-52-42](https://github.com/user-attachments/assets/95abe6f6-41f9-4431-9d76-8881fba86209)
![Screenshot from 2024-12-27 13-52-19](https://github.com/user-attachments/assets/576b31e0-4fe6-43ed-9c8b-a21f30cd3339)

**Comment by ReinerBforartists** [comment]
Hi @foliagetree23 ,

Many thanks for the report

The issue seems to be your non-existent graphics card and the age of your laptop. Your laptop is simply too outdated from a technical perspective. It’s from 2016. Additionally neither Blender nor Bforartists officially supports onboard graphics. Your system does simply not meet the current system requirements for the latest versions of Blender or Bforartists. I’m surprised it runs at all.

You can find the system requirements here. Bforartists has the same requirements as Blender: https://www.blender.org/download/requirements/

Unfortunately, there’s nothing we can do about this. The "bug" here is that you simply need more up-to-date hardware. Unfortunately, adding a better graphics card to a laptop isn’t really an option. So, your only alternatives are to either revert to an older version of Bforartists/Blender that works better with your current hardware or to upgrade by purchasing a new laptop. :)

Hope that helps :)

Closing this issue. As told, there is nothing to fix for us here.

Kind regards
Reiner
