### ISSUE TITLE
Hotkey conflict with hotkey e for rotate and trackball navigation

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#65]
Hotkey E. You tap once and you rotate the selection. You tap the key twice and you can rotate in trackball navigation style.

The problem is when you hold down the key, then it flickers between the two modes.

**Comment by ReinerBforartists** [comment]
Have reported this one to Blender too. Let's first wait what they say

https://developer.blender.org/T54297

**Comment by ReinerBforartists** [comment]
The bug report gots declined. And so we will keep this unfixed too. At least for now. A bug fix would introduce too many differences in the behaviour between Blender and Bforartists.

Brecht mentioned to have deeper changes at the keymap for 2.8. Let's see with what they come up there.

**Comment by Draise14** [comment]
I think this is a feature that would need to be added to Blender as "sticky" hotkeys, or "Hold" feature added to the api. At the moment the conflict exists because Press, Release, click, Double click and the rest don't have a "Hold" attribute - so they continuously toggle if held down. Shame they won't want to develop that - but we'll see what they do with 2.8 yeah!

**Comment by ReinerBforartists** [comment]
I am also not this happy about this behaviour. But it would be lots of changes. And it would behave different than Blender then. With the danger that we will get bug reports about this different behaviour.

We might resurrect this one when we come to the pie menus, and at a case by case base then. But for now it's imho better not to touch this.
