### ISSUE TITLE
Video Sequencer - Strip menu - Seperate Swap Tooltips

### ISSUE THREAD

**Issue by Draise14** [Bforartists/Bforartists#844]
![bforartists_2019-05-02_15-15-05](https://user-images.githubusercontent.com/35357409/57104127-2e384780-6ced-11e9-82a1-f9e5387b4d3f.png)

Right now the Swap Strip operators are enumerated and both Left and Right have the same tooltip. I have done a draft to change the tooltip to make sense for both... but there must be a better way. 

## Question
How do you add different tooltips for enumerated operator/menu items?

**Comment by ReinerBforartists** [comment]
Yes, make a own python operator with own tooltip that calls this operators. I have done this a few times in the 3d view. Have a look for the # Workaround to separate the tooltips classes in the space_view3d.py file

Alternatively you could modify the tooltip in the C part to explain both cases. A \n adds a new line in the tooltip. This would be my favourite here, since the difference is not this big. It's just left or right, and does basically the same.

The third case is to create a own C operator. Have done this once, it's a bit hairy though. And makes the code harder to maintain when merging with the Blender codebase.

**Comment by Draise14** [comment]
Ah ok. I changed the C to have the tooltip explain both R and L. It's already in the pull #848. Sorry for being so messy. 

_Will stick to one task at a time now, please do not assign me another task once I've got one already! =P_
