### ISSUE TITLE
Toolshelf - Make the Select method Select the default method, separate it into own button

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#856]
One of the nastiest behaviours with the new tool system is that you always end in box selection after you used something. You create a cube, you end in box select. And need to switch to select method Select to move it around. You use a tool, to extrude for example, and end in Box select. To select what? The already selected vertice that you want to MOVE around now? Again  you need to switch to the hidden select method select ...

Make select method Select the default method, move it out of the sub menu, so that it is always reachable with ONE click.

![select](https://user-images.githubusercontent.com/13919702/57314533-1cdaab00-70f2-11e9-8343-f9da8cb33b4e.jpg)

**Comment by ReinerBforartists** [comment]
Party on!

**Comment by ReinerBforartists** [comment]
Good lord, what a hack ...

And can please somebody explain those developers what comments are good for? -.-

**Comment by ReinerBforartists** [comment]
Okay, managed to separate the select button from the group. But that's just half of the show. The default state is defined in the startup.blend. For all object types and all modes from what i can see :/

And there is more than just making this button separated. There should be a way to end the current tool and jump back to select with one action. Moving the mouse is not the best solution for that.

The whole system is flawed. And i am not sure if we can fix that. First step would be to add comments to this weird code i guess ...

Either way, let's continue with this task first. Then have a look for the rest. 

![separated](https://user-images.githubusercontent.com/13919702/60255210-9b242400-98cf-11e9-8780-47b7cb7afed8.jpg)

**Comment by ReinerBforartists** [comment]
Postponing until after the 2.80 release. Needs further thinking.

**Comment by Draise14** [comment]
My solution to this was to activate the widget transform tools automatically with WER hotkeys rspectively (and the instant transform with modals on drag at 1px - super responsive), then use box select with a hotkey modifier on Lclick or hotkey. I also tried out Double Lclick to activate the transform mode or double WW EE RR to go back to normal non-widget transform mode. It made work quick and actually I prefer it over BFA1 now. 

The issue here is that these toolshelf systems are operator toggles (on/modify/stay on), not a hot on/modify/off operator as done traditionally from 2.79 or BFA1. It is debatable what is better and more fluid as a UX - but all in all the box select and transform/select system is still broken from all the 2.8 efforts to try fusion it with transformations (unlike the Node Editor). 


**So my solution:**
[Watch an example here](https://youtu.be/VhOUzeJ-aYA)

1. WER is double assigned to the transform widget toggles of the toolshelf to add a better UX and visual feedback
2. WER with drag (1px) is assigned to the traditional on/off transforms with modals for instant workflows that don't need widgets but hotkey modals (to quick switch transform modes without needing to switch mode THEN move)
3. W double tap goes to transform/select mode for quick transforms without selection (vertex pushing, etc) _this can be anything really_
4. CTRL (box select set) L mouse tweak / CTRL (lasso select set) R mouse tweak _now consistent with lasso select hotkeys of BFA, and considerable easier with box select_
5. SHIFT (box select exclude) L mouse tweak  / SHIFT (lasso select exclude) R mouse tweak - _probably should be swapped with CTRL, as SHIFT is usually add selection in Blender for some reason_
6. CTRL + SHIFT (box select extend) L mouse tweak  / CTRL+SHIFT (lasso select extend) R mouse tweak

I made this true in all editors in most of the UI, for the box select and transform widgets/modal systems _(still working on the Node editor system as that is the only inconsistent one and has a weird system I'm still trying to understand how it works)_

**Key idea:**
- The box select would now be consistent in it's method of use in the UI and activated regardless of the tool (right now only the Node Editor has transform AND box select fusioned like most software, and right now it's inconsistent)
- The transformation in the 3D View has visual feedback, works both with toggle and traditional on/modify/off systems - now just sticking to the mode you switched to. 
- There is still a way to assign an easy method to go to select/transform mode that still can be defined that won't need to re-write the entire system of toggle tools to on/modify/off tools in the toolshelf and create bugs, inconsistencies and assumptions that people want to stick to one particular mode over another, when they activated a mode by hotkey once, by the toolshelf once, stay on that operator mode.

**Comment by Draise14** [comment]
Just realized this is not really part of this task, more a feature request for another task.

1. Move select/transform operator up one (YES)
2. Make it default in all modes (YES, but with the accessibility to Box Select added to the general UI as suggested above)

**Comment by ReinerBforartists** [comment]
Yes, this would be another task ^^

**Comment by ReinerBforartists** [comment]
Fixed in toolshelf branch.

It remains flawed though since we run into the *cannot save state of the tool shelf in startup.blend file* bug here. It starts in single row. The other templates works fine. But not the default.
