### ISSUE TITLE
Put options props from the view menu into a settings menu

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#921]
I am unhappy with these props in the view menu. Options should not be in a text menu. But am not really sure where to put this functionality.

Needs further thinking.

![settings](https://user-images.githubusercontent.com/13919702/58616060-fce77300-82bc-11e9-963a-2e1d33e03dca.jpg)

**Comment by ReinerBforartists** [comment]
Maybe we can put at least two of them into one of the panels at the right ...

**Comment by Draise14** [comment]
Maybe toggle buttons with icons in the header similar to the Properties/outliner toggles view? 

If it's in the sidebar then the toggles hide making them unaccessible by mouse till you manually pull out the properties shelf again.

**Comment by ReinerBforartists** [comment]
That's imho no good idea. Why pollute the header with toggles that you click once a year? 

Hm, i think to put at least two of them into the Viewport Gizmos . Tool settings and Adjust last operation could fit right under the Navigate chapter.

![viewportgizmos](https://user-images.githubusercontent.com/13919702/58645292-5a061780-8303-11e9-8127-5f2743a3ccdb.jpg)

**Comment by ReinerBforartists** [comment]
This all doesn't make me happy ...

I'll postpone this one until i have an idea what to do here.

**Comment by Draise14** [comment]
The issue with this is that these shelf/toolbar toggles are EVERYWHERE. If you move them to the Gizmo dropdown in the 3D View, it will make the rest of the UI inconsistent and you will still have checkboxes for shelves in a header sub-menu elsewhere (VSE, Node Editor, Image Editor, etc).

I do think, if you are going to move them, that they all should be in a similar location throughout the UI everywhere (eg. in the header exclusively by the view toggle button for quick easy access). If you move these to the Gizmo dropdown, it will make the rest of the UI inconsistent as not all editors have a gizmo dropdown.  

### Here is my suggestion - take2:

![PureRef_2019-05-31_13-54-42](https://user-images.githubusercontent.com/35357409/58728997-d2c1ae00-83ad-11e9-9620-431022f45af1.png)


**Suggestion 1.** Move these View toggle tick boxes up into the header, location: by the view toggle (first place in the header if toggle hidden). 

Reason: it would be consistent with the outliner/properties toggle button and adds iconology to these features, and it would be consistent throughout the entire editor scheme. 

Argument: they are not used often (though I do personally) and pollutes the header. 

**Suggestion 2.** do the same, but to the right, instead of left. 



![bforartists_2019-05-31_14-03-14](https://user-images.githubusercontent.com/35357409/58728972-b9b8fd00-83ad-11e9-9b4f-59d6759cba0e.png)
**Suggestion 3.** move them to a button with a dropdown in ALL headers and place it by the Editor toggle or to the right of all headers. (favorite solution) Create an icon for editor shelf toggles. 

Argument: this would make sense as viewport toggles seem to be in dropdown floating checkbox menu's in the 3D Viewport, so.. why not make all these shelf toggles also a dropdown floating checkbox menu for all editors? Also, the one icon for the dropdown would still keep them hidden and frees up the header menu's.

**Comment by ReinerBforartists** [comment]
We could also simply leave it where it is. Blender users would hate us ^^

**Comment by ReinerBforartists** [comment]
Hm. It's just the Tool Settings and Adjust Last Operatio checkbox that needs a move.

**Comment by ReinerBforartists** [comment]
I have thought about it for a pretty while now. I will leave it the way it is. These four checkboxes doesn't really disturb. Moving them to elsewhere would lead to confusion for Blender users, and wouldn't be an improvement at all. Since there is no place that makes more sense. And putting them into a sub menu would mean to have a sub menu for two menu items in many other editors for consistency reasons.
