### ISSUE TITLE
Switching from properties editor to outliner - starting in wrong mode

### ISSUE THREAD

**Issue by ReinerBforartists** [Bforartists/Bforartists#943]
When we switch the properties editor to outliner, then the outliner starts in top hierarchy. Scenes mode. But the outliner in the default layout is in view layer mode. Inconsistent. 

Let's have a look if we can do something with the workspaces here.

![switchingtooutliner](https://user-images.githubusercontent.com/13919702/59021951-1fddce00-884d-11e9-99b1-e9fc6e85068a.jpg)

**Comment by Draise14** [comment]
I like this flaw. I thought it was intentional. This has been a system from BFA 1. 

I personally, since BFA 1,I had the top be visible/current scene outliner, and the botton all scenes/groups outliner on toggle. I sometimes work with multiple scenes a lot, specially for layout and animation projects, so having a quick toggle to access scenes without a dropdown hidden away in a tab or toolbar for scene navigation, I thought, was a good design default and is/was very strong feature in Bforartists/Blender that a lot of software don't have - one click overview multi-scene workflows. 

Making the toggles now somewhat redundant on toggle (why have two of the same outliner views open?) doesn't.. seem logical to me. It's like having two identical toolbars or two identical property panels in the same workspace.. for no reason? Why use the toggle now if they are the same? To just to swap views from top to bottom with a two click process or to add extra steps for outliner/multi-scene workflows? Now we make scene toggling a hidden away dropdown menu system exclusively from default? 

Not a big fan of this task, sorry...

**Comment by ReinerBforartists** [comment]
The point here was that as an advanced user you can simply close the outliner at the top. And work with just one editor here. Switching between outliner and properties editor as required.

**Comment by Draise14** [comment]
Which.. is still an odd workflow. If you have the outliner already open at the top, you'd just merge the top outliner editor to the bottom properties editor to maximize (with the default outliner view naturally), then switch to properties when needed via the toggle. Goal: maximize outliner, switch to properties occasionally while building and layout. 

If you expand from the bottom, yes, you have your consistency issue, but not from the top - and you cut away what I consider more a power user functionality = one click scene management, and real scene structure/hierachy (collections view doesn't have this true hierachy as you can parent a child and have it in another collection). 

Maybe the issue is access to a consistent outliner editor dimension and this task: #915 would be best to fix the need this tries to solve: consistent outliner experience for toggling to properties. 

Can it please be like this?:
Top Toggle = Collection Hierachy's (not even true scene hierachy, more like the old "groups" outliner hierachy)
Bottom Toggle = Scene Hierachy's

User can choose what he maximizes and toggles from top to bottom, or bottom to top. 

Being initially stuck on the default collections view that doesn't show true scene hierachy on default is going to kill me (not literally).

**Comment by ReinerBforartists** [comment]
Woah, we want to simplify things, not make it even more complicated :D

**Comment by Draise14** [comment]
If they need to be the same, I would prefer the scene view in both. The default collections view is not simple. And now having both in collections view makes it more complicated to work in a simple scene based hierachy. Collections don't show hierachy without a complicated ghosting system, it's only good for visibility toggling and all things viewport related like rendering, and on first open you want to model and do layout and rig, long before lookdev, scene layout rendering with animation. I guess this will have to be another feature request task as that kind of request has nothing to do with this task. 

Collections on default is not simple.

**Comment by ReinerBforartists** [comment]
But the scene objects are in the collections. So you better start at collection level.

**Comment by Draise14** [comment]
Newly created objects are placed outside of a collection if no collection is selected, there is no default collection, there is no "scene collection" with visibility toggles. You can loose objects and you can't tell what is where because they are in multiple places in a view collections, not according to their parents or children (unless it's ghosted, then where is the original? Now dig.) 

In the scene hierachy, you have a collection list like a layer list, and the true hierachy of a scene. New objects are placed in the scene hierachy, and you can add to the collections later from the scene outliner - it is more realistic and predictable to what an object hierarchy should be. When it comes to rendering and scene layout with instances, sure, switch over to collections, but only after having completed building the scene assets and rigs. 

![bforartists_2019-06-06_12-14-35](https://user-images.githubusercontent.com/35357409/59052413-ad70ec00-8854-11e9-84aa-ba8a1da0879f.png)

**Comment by Draise14** [comment]
I guess all collections is ok as a default. It's the most filtered advanced version of the outliner, and you can turn off collections to get the scene hierarchy like in the scene view with the added filters. You loose scene management and you risk early confusion with the collection system, but it works.. meh. The latter works for both collection visibility, assignment and scene hierarchy with scene management, and it's simpler - but you loose the filters and collection visual indicators as to where the one object resides in multiple.

**Comment by ReinerBforartists** [comment]
Draise, i understand what you mean, but this is a completely different problem ^^

**Comment by ReinerBforartists** [comment]
Fixed in master
